//! The shared test vectors, run here by the Rust codecs and by the generated Elixir codec on
//! beamlet (redoubt/wire/elixir/run-vectors). Formats are described at the top of each file.
//!
//! - `vectors/example.txt`: typed messages of the fixture protocol, written by hand. Every
//!   accepted line must decode to the next message of the hand-built lists below, so a change
//!   in the codec cannot slip past by rewriting the file.
//! - `vectors/example-generated.txt`: a few thousand pseudo-random and hostile inputs with the
//!   Rust codec's verdict on each, so the Elixir codec is checked against Rust's behaviour
//!   well beyond the hand-written cases. Regenerated by this test with `WIRE_BLESS=1`; the
//!   test fails if it differs.
//! - `vectors/9p.txt`: 9P2000, for servers' conformance tests too.

use std::fmt::Write as _;

use redoubt_wire::ninep::{self, Body, Message as NineP, Names, Qid, Qids, Stat};
use redoubt_wire::proto::example::*;
use redoubt_wire::typed::Words;
use redoubt_wire::{Error, MSIZE};

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn unhex(s: &str) -> Vec<u8> {
    if s == "-" {
        return Vec::new();
    }
    assert!(s.len().is_multiple_of(2), "odd hex {s}");
    (0..s.len()).step_by(2).map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap()).collect()
}

fn path(name: &str) -> String {
    format!("{}/vectors/{name}", env!("CARGO_MANIFEST_DIR"))
}

/// Lines that are not blank or comments, split into fields.
fn lines(text: &str) -> Vec<Vec<&str>> {
    text.lines().filter(|l| !l.trim().is_empty() && !l.starts_with('#')).map(|l| l.split_whitespace().collect()).collect()
}

fn words(fields: &[&str]) -> Words {
    let mut w = [0u64; 4];
    for (slot, f) in w.iter_mut().zip(fields) {
        *slot = u64::from_str_radix(f, 16).unwrap();
    }
    w
}

fn s(v: &str) -> String {
    format!("s:{}", hex(v.as_bytes()))
}

fn b(v: &[u8]) -> String {
    format!("b:{}", hex(v))
}

/// `NAME FIELD=VALUE ...` as in the vector files (and as the Elixir runner renders them).
fn render_message(m: &Message<'_>) -> String {
    match m {
        Message::Ping(_) => "ping".into(),
        Message::Pong(m) => format!("pong seq={} flags={}", m.seq, m.flags),
        Message::Small(m) => format!("small a={} b={}", m.a, m.b),
        Message::Wide(m) => format!("wide a={} b={} c={}", m.a, m.b, m.c),
        Message::Named(m) => format!("named id={} name={}", m.id, s(m.name)),
        Message::Blob(m) => format!("blob offset={} data={} label={}", m.offset, b(m.data), s(m.label)),
        Message::Grant(m) => format!("grant pages={}", m.pages),
        Message::Read(m) => format!("read offset={} count={}", m.offset, m.count),
        Message::Last(m) => format!("last note={}", s(m.note)),
    }
}

fn render_reply(r: &Reply<'_>) -> String {
    match r {
        Reply::Ping(_) => "ping".into(),
        Reply::Small(r) => format!("small c={}", r.c),
        Reply::Wide(_) => "wide".into(),
        Reply::Named(r) => format!("named id={}", r.id),
        Reply::Grant(_) => "grant".into(),
        Reply::Read(r) => format!("read data={}", b(r.data)),
        Reply::Last(r) => format!("last n={} m={}", r.n, r.m),
    }
}

fn error_name(e: ErrorCode) -> &'static str {
    match e {
        ErrorCode::NotFound => "not_found",
        ErrorCode::Denied => "denied",
        ErrorCode::LastError => "last_error",
    }
}

fn buffer_field(buf: &[u8]) -> String {
    if buf.is_empty() { "-".into() } else { hex(buf) }
}

fn words_field(w: &Words) -> String {
    format!("{:x} {:x} {:x} {:x}", w[0], w[1], w[2], w[3])
}

/// The line for a received request, reply (`request` is the opcode it answers) or file.
enum Case {
    Request { handles: usize, words: Words, buf: Vec<u8> },
    Reply { request: u32, handles: usize, words: Words, buf: Vec<u8> },
    File(Vec<u8>),
}

/// The line the Rust codec's verdict on `case` makes.
fn line(case: &Case) -> String {
    match case {
        Case::Request { handles, words, buf } => {
            let head = format!("{handles} {} {}", words_field(words), buffer_field(buf));
            match Message::decode(words, buf, *handles) {
                Ok(m) => format!("ok {head} {}", render_message(&m)),
                Err(e) => format!("bad {head} {e:?}"),
            }
        }
        Case::Reply { request, handles, words, buf } => {
            let head = format!("{request:x} {handles} {} {}", words_field(words), buffer_field(buf));
            match Reply::decode(*request, words, buf, *handles) {
                Ok(Ok(r)) => format!("reply {head} {}", render_reply(&r)),
                Ok(Err(e)) => format!("failed {head} {}", error_name(e)),
                Err(e) => format!("badreply {head} {e:?}"),
            }
        }
        Case::File(bytes) => match Message::decode_file(bytes) {
            Ok(m) => format!("file {} {}", buffer_field(bytes), render_message(&m)),
            Err(e) => format!("badfile {} {e:?}", buffer_field(bytes)),
        },
    }
}

/// Parses a vector line back into the case it describes.
fn case(f: &[&str]) -> Case {
    match f[0] {
        "ok" | "bad" => Case::Request { handles: f[1].parse().unwrap(), words: words(&f[2..6]), buf: unhex(f[6]) },
        "reply" | "failed" | "badreply" => Case::Reply {
            request: u32::from_str_radix(f[1], 16).unwrap(),
            handles: f[2].parse().unwrap(),
            words: words(&f[3..7]),
            buf: unhex(f[7]),
        },
        "file" | "badfile" => Case::File(unhex(f[1])),
        other => panic!("unknown line kind {other}"),
    }
}

/// Checks every line of a typed-message vector file against the Rust codec: the line must
/// be exactly the codec's verdict, and accepted inputs must re-encode to what arrived.
/// Returns the count of each line kind.
fn check_file(name: &str) -> std::collections::BTreeMap<String, usize> {
    let text = std::fs::read_to_string(path(name)).unwrap();
    let mut counts = std::collections::BTreeMap::new();
    for f in lines(&text) {
        let c = case(&f);
        assert_eq!(line(&c), f.join(" "), "{name}: the codec's verdict differs");
        let mut out = vec![0u8; MSIZE];
        match (&c, f[0]) {
            (Case::Request { handles, words, buf }, "ok") => {
                let again = Message::decode(words, buf, *handles).unwrap().encode(&mut out).unwrap();
                assert_eq!(&again, words, "{f:?}");
                // A buffer message re-encodes to the first word-1 bytes of what arrived.
                let len = if buf.is_empty() { 0 } else { words[1] as usize };
                assert_eq!(out[..len], buf[..len], "{f:?}");
            }
            (Case::Reply { request, handles, words, buf }, "reply" | "failed") => {
                let again = match Reply::decode(*request, words, buf, *handles).unwrap() {
                    Ok(r) => r.encode(&mut out).unwrap(),
                    Err(e) => e.encode(),
                };
                assert_eq!(&again, words, "{f:?}");
                if f[0] == "reply" {
                    let len = if buf.is_empty() { 0 } else { words[1] as usize };
                    assert_eq!(out[..len], buf[..len], "{f:?}");
                }
            }
            (Case::File(bytes), "file") => {
                let n = Message::decode_file(bytes).unwrap().encode_file(&mut out).unwrap();
                assert_eq!(&out[..n], &bytes[..], "{f:?}");
            }
            _ => {}
        }
        *counts.entry(f[0].to_string()).or_insert(0) += 1;
    }
    counts
}

fn hand_built_requests() -> Vec<Message<'static>> {
    vec![
        Message::Ping(Ping {}),
        Message::Pong(Pong { seq: 0x0102_0304_0506_0708, flags: 0xdead_beef }),
        Message::Pong(Pong { seq: u64::MAX, flags: u32::MAX }),
        Message::Small(Small { a: 0xab, b: 0x1234 }),
        Message::Wide(Wide { a: 1, b: 2, c: 3 }),
        Message::Named(Named { id: 42, name: "fsd:data" }),
        Message::Named(Named { id: 0, name: "" }),
        Message::Named(Named { id: 7, name: "h\u{e9}llo \u{1f600}" }),
        Message::Blob(Blob { offset: 1 << 40, data: &[0, 1, 2, 0xff], label: "x" }),
        Message::Blob(Blob { offset: 0, data: &[], label: "" }),
        Message::Grant(Grant { pages: 16 }),
        Message::Read(Read { offset: 4096, count: 512 }),
        Message::Last(Last { note: "max opcode" }),
        // A lent buffer longer than the message (the last `ok` line).
        Message::Named(Named { id: 0, name: "" }),
    ]
}

fn hand_built_replies() -> Vec<Result<Reply<'static>, ErrorCode>> {
    vec![
        Ok(Reply::Ping(PingReply {})),
        Ok(Reply::Small(SmallReply { c: 0xdead_beef })),
        Ok(Reply::Wide(WideReply {})),
        Ok(Reply::Named(NamedReply { id: 42 })),
        Ok(Reply::Grant(GrantReply {})),
        Ok(Reply::Read(ReadReply { data: b"hello" })),
        Ok(Reply::Last(LastReply { n: u64::MAX, m: 7 })),
        Err(ErrorCode::NotFound),
        Err(ErrorCode::Denied),
        Err(ErrorCode::LastError),
        // An error reply ignores the buffer.
        Err(ErrorCode::NotFound),
    ]
}

fn hand_built_files() -> Vec<Message<'static>> {
    vec![
        Message::Pong(Pong { seq: 1, flags: 2 }),
        Message::Small(Small { a: 1, b: 2 }),
        Message::Named(Named { id: 42, name: "tcp!10.0.0.1!443" }),
        Message::Blob(Blob { offset: 0, data: &[1, 2], label: "" }),
        Message::Read(Read { offset: 4096, count: 512 }),
        Message::Ping(Ping {}),
    ]
}

#[test]
fn example_vectors() {
    let counts = check_file("example.txt");
    let want: Vec<(&str, usize)> =
        vec![("bad", 24), ("badfile", 7), ("badreply", 12), ("failed", 4), ("file", 6), ("ok", 14), ("reply", 7)];
    let got: Vec<(&str, usize)> = counts.iter().map(|(k, v)| (k.as_str(), *v)).collect();
    assert_eq!(got, want);

    // The accepted lines are exactly the hand-built values, in order.
    let text = std::fs::read_to_string(path("example.txt")).unwrap();
    let all = lines(&text);
    let mut requests = hand_built_requests().into_iter();
    let mut replies = hand_built_replies().into_iter();
    let mut files = hand_built_files().into_iter();
    for f in &all {
        match case(f) {
            Case::Request { handles, words, buf } if f[0] == "ok" => {
                assert_eq!(Message::decode(&words, &buf, handles), Ok(requests.next().unwrap()), "{f:?}");
            }
            Case::Reply { request, handles, words, buf } if f[0] != "badreply" => {
                assert_eq!(Reply::decode(request, &words, &buf, handles), Ok(replies.next().unwrap()), "{f:?}");
            }
            Case::File(bytes) if f[0] == "file" => {
                assert_eq!(Message::decode_file(&bytes), Ok(files.next().unwrap()), "{f:?}");
            }
            _ => {}
        }
    }
    assert!(requests.next().is_none() && replies.next().is_none() && files.next().is_none(), "a hand-built value has no line");
}

/// Spelled out from WIRE.md by hand, independent of the encoder.
#[test]
fn layouts_by_hand() {
    let pong = Message::Pong(Pong { seq: 0x0102_0304_0506_0708, flags: 0xdead_beef });
    assert_eq!(pong.encode(&mut []).unwrap(), [2, 0x0506_0708, 0x0102_0304, 0xdead_beef]);
    let mut buf = [0u8; 16];
    let named = Message::Named(Named { id: 42, name: "ab" });
    assert_eq!(named.encode(&mut buf).unwrap(), [5, 8, 0, 0]);
    assert_eq!(buf[..8], [42, 0, 0, 0, 2, 0, b'a', b'b']);
    // Too small an output buffer is an error, not a truncation, and leaves nothing.
    let mut short = [0u8; 7];
    assert_eq!(named.encode(&mut short), Err(Error::TooLarge));
    assert_eq!(short, [0; 7]);
    // A read is buffer-shaped (its reply carries data), though its request is 12 bytes.
    let read = Message::Read(Read { offset: 1, count: 2 });
    assert_eq!(read.encode(&mut buf).unwrap(), [8, 12, 0, 0]);
    let data = Reply::Read(ReadReply { data: b"hi" });
    assert_eq!(data.encode(&mut buf).unwrap(), [0, 6, 0, 0]);
    assert_eq!(buf[..6], [2, 0, 0, 0, b'h', b'i']);
    // An inline reply: status 0 in word 0, fields in words 1..=3.
    assert_eq!(Reply::Small(SmallReply { c: 9 }).encode(&mut []).unwrap(), [0, 9, 0, 0]);
    assert_eq!(ErrorCode::Denied.encode(), [2, 0, 0, 0]);
    // The file framing: opcode, then the fields, even for an inline message.
    let n = Message::Small(Small { a: 1, b: 0x0302 }).encode_file(&mut buf).unwrap();
    assert_eq!(buf[..n], [3, 0, 0, 0, 1, 2, 3]);
    // Messages with handles cannot be written into a file; files are at most 64 KiB.
    assert_eq!(Message::Grant(Grant { pages: 1 }).encode_file(&mut buf), Err(Error::BadHandles));
    assert_eq!(Message::decode_file(&vec![0u8; MSIZE + 1]), Err(Error::TooLarge));
    let big = vec![0u8; MSIZE];
    let mut out = vec![0u8; 2 * MSIZE];
    assert_eq!(Message::Blob(Blob { offset: 0, data: &big, label: "" }).encode_file(&mut out), Err(Error::TooLarge));
}

/// A small deterministic generator (xorshift), so the generated vectors are reproducible.
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 7;
        self.0 ^= self.0 << 17;
        self.0
    }

    fn below(&mut self, n: u64) -> u64 {
        self.next() % n
    }

    fn word(&mut self) -> u64 {
        match self.below(8) {
            0 => 0,
            1 => self.next() & 0xff,
            2 => self.next() & 0xffff_ffff,
            3 => self.next(),
            _ => self.next() & 0x3f,
        }
    }

    fn bytes(&mut self, max: u64) -> Vec<u8> {
        let n = self.below(max + 1);
        (0..n).map(|_| self.next() as u8).collect()
    }

    /// A plausible field encoding: a mix of small integers, strings and byte arrays, some
    /// of them truncated or with bad UTF-8.
    fn body(&mut self) -> Vec<u8> {
        let mut out = Vec::new();
        for _ in 0..self.below(4) {
            match self.below(5) {
                0 => out.extend((self.next() as u32).to_le_bytes()),
                1 => out.extend(self.next().to_le_bytes()),
                2 | 3 => {
                    let n = self.below(8) as usize;
                    let long = self.below(2) == 0;
                    if self.below(2) == 0 {
                        out.extend((n as u16).to_le_bytes());
                    } else {
                        out.extend((n as u32).to_le_bytes());
                    }
                    let fill = if self.below(6) == 0 { 0xc3 } else { b'a' };
                    out.extend(std::iter::repeat_n(fill, if long { n } else { n.saturating_sub(1) }));
                }
                _ => out.push(self.next() as u8),
            }
        }
        out
    }
}

const OPCODES: [u64; 12] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0xffff_ffff, 1 << 32];
const STRINGS: [&str; 5] = ["", "a", "fsd:data", "h\u{e9}llo", "tcp!10.0.0.1!443"];
const BYTES: [&[u8]; 4] = [b"", b"\0", b"hello", &[0xff; 9]];

impl Rng {
    fn int(&mut self) -> u64 {
        [0, 1, 0xff, 0xffff_ffff, u64::MAX, self.next()][self.below(6) as usize]
    }

    fn string(&mut self) -> &'static str {
        STRINGS[self.below(STRINGS.len() as u64) as usize]
    }

    fn data(&mut self) -> &'static [u8] {
        BYTES[self.below(BYTES.len() as u64) as usize]
    }

    fn message(&mut self) -> Message<'static> {
        match self.below(9) {
            0 => Message::Ping(Ping {}),
            1 => Message::Pong(Pong { seq: self.int(), flags: self.int() as u32 }),
            2 => Message::Small(Small { a: self.int() as u8, b: self.int() as u16 }),
            3 => Message::Wide(Wide { a: self.int(), b: self.int() as u32, c: self.int() as u8 }),
            4 => Message::Named(Named { id: self.int() as u32, name: self.string() }),
            5 => Message::Blob(Blob { offset: self.int(), data: self.data(), label: self.string() }),
            6 => Message::Grant(Grant { pages: self.int() as u32 }),
            7 => Message::Read(Read { offset: self.int(), count: self.int() as u32 }),
            _ => Message::Last(Last { note: self.string() }),
        }
    }

    /// A reply and the opcode of its request.
    fn reply(&mut self) -> (u32, Reply<'static>) {
        match self.below(7) {
            0 => (1, Reply::Ping(PingReply {})),
            1 => (3, Reply::Small(SmallReply { c: self.int() as u32 })),
            2 => (4, Reply::Wide(WideReply {})),
            3 => (5, Reply::Named(NamedReply { id: self.int() as u32 })),
            4 => (7, Reply::Grant(GrantReply {})),
            5 => (8, Reply::Read(ReadReply { data: self.data() })),
            _ => (0xffff_ffff, Reply::Last(LastReply { n: self.int(), m: self.int() as u32 })),
        }
    }

    /// Sometimes changes one word, the handle count, or one byte of the buffer.
    fn mutate(&mut self, handles: &mut usize, words: &mut Words, buf: &mut Vec<u8>) {
        match self.below(6) {
            0 => words[self.below(4) as usize] = self.word(),
            1 => *handles = self.below(5) as usize,
            2 if !buf.is_empty() => {
                let i = self.below(buf.len() as u64) as usize;
                buf[i] = self.next() as u8;
            }
            3 => buf.push(self.next() as u8),
            _ => {}
        }
    }
}

/// An encoded message: its words and the first word-1 bytes of `buf` if it is a buffer
/// message (an inline message encodes without touching an empty buffer).
fn framed(words: Words, buf: &[u8], inline: bool) -> (Words, Vec<u8>) {
    let len = if inline { 0 } else { words[1] as usize };
    (words, buf[..len].to_vec())
}

fn generated_cases() -> Vec<Case> {
    let mut rng = Rng(0x9e37_79b9_7f4a_7c15);
    let mut cases = Vec::new();
    let mut out = vec![0u8; MSIZE];
    for _ in 0..2000 {
        if rng.below(2) == 0 {
            let m = rng.message();
            let (mut words, mut buf) = framed(m.encode(&mut out).unwrap(), &out, m.encode(&mut []).is_ok());
            let mut handles = m.handle_names().len();
            rng.mutate(&mut handles, &mut words, &mut buf);
            cases.push(Case::Request { handles, words, buf });
            continue;
        }
        let op = OPCODES[rng.below(OPCODES.len() as u64) as usize];
        let mut words = [op, rng.word(), rng.word(), rng.word()];
        let mut buf = if rng.below(3) == 0 { rng.bytes(24) } else { Vec::new() };
        if rng.below(2) == 0 {
            // A well-framed buffer message: the length in word 1, words 2 and 3 zero.
            buf = rng.body();
            words = [op, buf.len() as u64, 0, 0];
            if rng.below(4) == 0 {
                buf.extend(rng.bytes(4)); // a lend longer than the message
            }
        }
        let handles = [0, 0, 1, 2, 3, 5][rng.below(6) as usize];
        cases.push(Case::Request { handles, words, buf });
    }
    for _ in 0..1000 {
        if rng.below(2) == 0 {
            let (request, r) = rng.reply();
            let (mut words, mut buf) = framed(r.encode(&mut out).unwrap(), &out, r.encode(&mut []).is_ok());
            let mut handles = r.handle_names().len();
            if rng.below(3) == 0 {
                let code = [ErrorCode::NotFound, ErrorCode::Denied, ErrorCode::LastError][rng.below(3) as usize];
                (words, handles) = (code.encode(), 0);
            }
            rng.mutate(&mut handles, &mut words, &mut buf);
            cases.push(Case::Reply { request, handles, words, buf });
            continue;
        }
        let request = OPCODES[rng.below(OPCODES.len() as u64) as usize] as u32;
        let status = [0, 0, 0, 1, 2, 3, 0xffff_ffff, 1 << 32][rng.below(8) as usize];
        let mut words = [status, rng.word(), rng.word(), rng.word()];
        let mut buf = if rng.below(3) == 0 { rng.bytes(24) } else { Vec::new() };
        match rng.below(3) {
            0 => {
                buf = rng.body();
                words = [status, buf.len() as u64, 0, 0];
            }
            1 => words = [status, 0, 0, 0],
            _ => {}
        }
        let handles = [0, 0, 1, 2][rng.below(4) as usize];
        cases.push(Case::Reply { request, handles, words, buf });
    }
    for _ in 0..500 {
        let mut bytes = match rng.message() {
            m if rng.below(2) == 0 && m.handle_names().is_empty() => {
                let n = m.encode_file(&mut out).unwrap();
                out[..n].to_vec()
            }
            _ => {
                let op = OPCODES[rng.below(OPCODES.len() as u64) as usize] as u32;
                let mut bytes = op.to_le_bytes().to_vec();
                bytes.extend(rng.body());
                bytes
            }
        };
        if rng.below(3) == 0 {
            bytes.truncate(rng.below(bytes.len() as u64 + 2) as usize + 2);
        }
        cases.push(Case::File(bytes));
    }
    cases
}

#[test]
fn generated_vectors_are_current() {
    let mut text = String::from(
        "# Generated by redoubt/wire/tests/vectors.rs (WIRE_BLESS=1 cargo test -p redoubt-wire --test vectors):\n\
         # pseudo-random and hostile inputs with the Rust codec's verdict on each, in the format of\n\
         # example.txt. The Elixir codec must agree with every line.\n",
    );
    for c in generated_cases() {
        let _ = writeln!(text, "{}", line(&c));
    }
    let file = path("example-generated.txt");
    if std::env::var_os("WIRE_BLESS").is_some() {
        std::fs::write(&file, &text).unwrap();
    }
    assert!(std::fs::read_to_string(&file).unwrap() == text, "{file} is stale: rerun with WIRE_BLESS=1");
    let counts = check_file("example-generated.txt");
    // Enough of every kind that the differential means something.
    for kind in ["ok", "bad", "reply", "failed", "badreply", "file", "badfile"] {
        assert!(counts.get(kind).copied().unwrap_or(0) >= 50, "{kind}: {counts:?}");
    }
}

fn ninep_messages() -> Vec<NineP<'static>> {
    const STAT: Stat<'static> = Stat {
        kind: 0,
        dev: 0,
        qid: Qid { kind: 0x80, version: 3, path: 0x1234 },
        mode: 0x8000_01ed,
        atime: 1_700_000_000,
        mtime: 1_700_000_001,
        length: 0,
        name: "home",
        uid: "",
        gid: "",
        muid: "",
    };
    let qid = Qid { kind: 0, version: 1, path: 99 };
    let m = |tag, body| NineP { tag, body };
    vec![
        m(ninep::NOTAG, Body::Tversion { msize: MSIZE as u32, version: ninep::VERSION }),
        m(ninep::NOTAG, Body::Rversion { msize: MSIZE as u32, version: ninep::VERSION }),
        m(1, Body::Tauth { afid: 5, uname: "alice", aname: "" }),
        m(1, Body::Rauth { aqid: qid }),
        m(2, Body::Tattach { fid: 0, afid: ninep::NOFID, uname: "alice", aname: "/home/alice" }),
        m(2, Body::Rattach { qid: STAT.qid }),
        m(3, Body::Rerror { ename: "file does not exist" }),
        m(4, Body::Tflush { oldtag: 3 }),
        m(4, Body::Rflush),
        m(5, Body::Twalk { fid: 0, newfid: 1, wnames: Names::new(&["notes", "todo.txt"]).unwrap() }),
        m(5, Body::Rwalk { qids: Qids::new(&[STAT.qid, qid]).unwrap() }),
        m(6, Body::Twalk { fid: 0, newfid: 2, wnames: Names::new(&[]).unwrap() }),
        m(6, Body::Rwalk { qids: Qids::new(&[]).unwrap() }),
        m(7, Body::Topen { fid: 1, mode: 0 }),
        m(7, Body::Ropen { qid, iounit: (MSIZE - ninep::IOHDRSZ) as u32 }),
        m(8, Body::Tcreate { fid: 1, name: "new", perm: 0o644, mode: 1 }),
        m(8, Body::Rcreate { qid, iounit: 0 }),
        m(9, Body::Tread { fid: 1, offset: 0, count: 8192 }),
        m(9, Body::Rread { data: b"hello\n" }),
        m(10, Body::Twrite { fid: 1, offset: 1 << 33, data: &[0, 0xff] }),
        m(10, Body::Rwrite { count: 2 }),
        m(11, Body::Tclunk { fid: 1 }),
        m(11, Body::Rclunk),
        m(12, Body::Tremove { fid: 2 }),
        m(12, Body::Rremove),
        m(13, Body::Tstat { fid: 0 }),
        m(13, Body::Rstat { stat: STAT }),
        m(14, Body::Twstat { fid: 0, stat: Stat { name: "", mode: u32::MAX, ..STAT } }),
        m(14, Body::Rwstat),
    ]
}

#[test]
fn ninep_vectors() {
    let text = std::fs::read_to_string(path("9p.txt")).unwrap();
    let mut expected = ninep_messages().into_iter();
    let (mut ok, mut bad) = (0, 0);
    for f in lines(&text) {
        match f[0] {
            "ok" => {
                let bytes = unhex(f[1]);
                let m = NineP::decode(&bytes).unwrap_or_else(|e| panic!("{f:?}: {e:?}"));
                assert_eq!(Some(m), expected.next(), "{f:?}");
                let mut out = vec![0u8; MSIZE];
                let n = m.encode(&mut out).unwrap();
                assert_eq!(hex(&out[..n]), f[1]);
                ok += 1;
            }
            "bad" => {
                let e = NineP::decode(&unhex(f[1])).expect_err(&format!("{f:?} decoded"));
                assert_eq!(format!("{e:?}"), f[2], "{f:?}");
                bad += 1;
            }
            _ => panic!("bad line {f:?}"),
        }
    }
    assert_eq!(expected.next(), None, "a hand-built 9P message has no vector");
    assert_eq!((ok, bad), (29, 13));
}

/// Prints the lines for the hand-built values; used to write example.txt, and to show what
/// changed if the tests above fail. `cargo test -p redoubt-wire --test vectors -- --ignored --nocapture`
#[test]
#[ignore]
fn print_hand_built_lines() {
    let mut buf = vec![0u8; MSIZE];
    for m in hand_built_requests() {
        let w = m.encode(&mut buf).unwrap();
        let len = if m.encode(&mut []).is_ok() { 0 } else { w[1] as usize };
        let c = Case::Request { handles: m.handle_names().len(), words: w, buf: buf[..len].to_vec() };
        println!("{}", line(&c));
    }
    let ops = [1, 3, 4, 5, 7, 8, 0xffff_ffff, 1, 8, 0xffff_ffff, 1];
    for (r, op) in hand_built_replies().into_iter().zip(ops) {
        let (w, len, handles) = match r {
            Ok(r) => {
                let w = r.encode(&mut buf).unwrap();
                let len = if r.encode(&mut []).is_ok() { 0 } else { w[1] as usize };
                (w, len, r.handle_names().len())
            }
            Err(e) => (e.encode(), 0, 0),
        };
        println!("{}", line(&Case::Reply { request: op, handles, words: w, buf: buf[..len].to_vec() }));
    }
    for m in hand_built_files() {
        let n = m.encode_file(&mut buf).unwrap();
        println!("{}", line(&Case::File(buf[..n].to_vec())));
    }
}
