# Typed messages of the `blkd` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `planning/redoubt/IO-ARCHITECTURE.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Proto.Blkd do
  @moduledoc """
  Codec for the `blkd` protocol. A request or reply is `{name, fields}`, with `fields` a
  map holding exactly the table's non-handle fields; an error reply decodes to
  `{:failed, error}`; `:malformed` (code 1) is every protocol's error for a request that
  does not decode. Framing and errors: `Redoubt.Wire`.
  """
  alias Redoubt.Wire, as: W

  # opcode => {name, shape, handles}; replies are keyed by their request's opcode.
  @requests %{
    1 => {:info, :buffer, 0},
    2 => {:read, :buffer, 0},
    3 => {:write, :buffer, 0},
    4 => {:flush, :inline, 0},
    5 => {:grant, :buffer, 0},
    6 => {:release, :inline, 0}
  }
  @replies %{
    1 => {:info, :buffer, 0},
    2 => {:read, :buffer, 0},
    3 => {:write, :buffer, 0},
    4 => {:flush, :inline, 0},
    5 => {:grant, :buffer, 1},
    6 => {:release, :inline, 0}
  }
  @errors %{
    1 => :malformed,
    2 => :not_permitted,
    3 => :out_of_range,
    4 => :too_many,
    5 => :failed
  }

  @doc """
  A message's layout: `{opcode, shape, fields, handles, reply}`, where `fields` lists
  `{name, type}` in order, `handles` lists the handles' names by slot, and `reply` is
  `{fields, handles}`.

  Handle kinds, from the table: documentation, checked by use (a handle of the wrong kind
  gets `WrongObject` on first use).

  - `grant` reply: `range` (slot 0, endpoint)
  """
  def layout(:info), do: {1, :buffer, [], [], {[{:sectors, :u64}, {:sector_size, :u32}, {:read_only, :u32}], []}}
  def layout(:read), do: {2, :buffer, [{:sector, :u64}, {:count, :u32}], [], {[{:data, :bytes}], []}}
  def layout(:write), do: {3, :buffer, [{:sector, :u64}, {:data, :bytes}], [], {[], []}}
  def layout(:flush), do: {4, :inline, [], [], {[], []}}
  def layout(:grant), do: {5, :buffer, [{:sector, :u64}, {:count, :u64}], [], {[{:id, :u64}], [:range]}}
  def layout(:release), do: {6, :inline, [{:id, :u64}], [], {[], []}}
  def layout(_), do: nil

  @doc "Encodes a request: `{:ok, words, buffer}` or `{:error, reason}`."
  def encode(message), do: W.encode(message, @requests, &enc(:request, &1, &2))

  @doc "Encodes a successful reply (status 0): `{:ok, words, buffer}` or `{:error, reason}`."
  def encode_reply(reply), do: W.encode_reply(reply, @replies, &enc(:reply, &1, &2))

  @doc "The words of an error reply: `{:ok, words, <<>>}` or `{:error, :bad_message}`."
  def encode_error(error), do: W.encode_error(error, @errors)

  @doc "Encodes a request for writing into a 9P file: `{:ok, bytes}` or `{:error, reason}`."
  def encode_file(message), do: W.encode_file(message, @requests, &enc(:request, &1, &2))

  @doc "Decodes a request from its four words, its buffer and its handle count."
  def decode(words, buffer, handles), do: W.decode(words, buffer, handles, @requests, &read(:request, &1, &2))

  @doc "Decodes the reply to the request with `opcode`: `{:ok, reply}`, `{:failed, error}` or `{:error, reason}`."
  def decode_reply(opcode, words, buffer, handles),
    do: W.decode_reply(opcode, words, buffer, handles, @replies, @errors, &read(:reply, &1, &2))

  @doc "Decodes a request written into a 9P file."
  def decode_file(bytes), do: W.decode_file(bytes, @requests, &read(:request, &1, &2))

  defp enc(:request, :info, %{} = f) when map_size(f) == 0, do: {1, []}
  defp enc(:reply, :info, %{sectors: v_sectors, sector_size: v_sector_size, read_only: v_read_only} = f) when map_size(f) == 3, do: {1, [W.u(v_sectors, 64), W.u(v_sector_size, 32), W.u(v_read_only, 32)]}
  defp enc(:request, :read, %{sector: v_sector, count: v_count} = f) when map_size(f) == 2, do: {2, [W.u(v_sector, 64), W.u(v_count, 32)]}
  defp enc(:reply, :read, %{data: v_data} = f) when map_size(f) == 1, do: {2, [W.bytes(v_data)]}
  defp enc(:request, :write, %{sector: v_sector, data: v_data} = f) when map_size(f) == 2, do: {3, [W.u(v_sector, 64), W.bytes(v_data)]}
  defp enc(:reply, :write, %{} = f) when map_size(f) == 0, do: {3, []}
  defp enc(:request, :flush, %{} = f) when map_size(f) == 0, do: {4, []}
  defp enc(:reply, :flush, %{} = f) when map_size(f) == 0, do: {4, []}
  defp enc(:request, :grant, %{sector: v_sector, count: v_count} = f) when map_size(f) == 2, do: {5, [W.u(v_sector, 64), W.u(v_count, 64)]}
  defp enc(:reply, :grant, %{id: v_id} = f) when map_size(f) == 1, do: {5, [W.u(v_id, 64)]}
  defp enc(:request, :release, %{id: v_id} = f) when map_size(f) == 1, do: {6, [W.u(v_id, 64)]}
  defp enc(:reply, :release, %{} = f) when map_size(f) == 0, do: {6, []}
  defp enc(_, _, _), do: throw({:wire, :bad_message})

  defp read(:request, 1, <<rest::binary>>), do: {:ok, :info, %{}, rest}
  defp read(:reply, 1, <<v_sectors::little-64, v_sector_size::little-32, v_read_only::little-32, rest::binary>>), do: {:ok, :info, %{sectors: v_sectors, sector_size: v_sector_size, read_only: v_read_only}, rest}
  defp read(:request, 2, <<v_sector::little-64, v_count::little-32, rest::binary>>), do: {:ok, :read, %{sector: v_sector, count: v_count}, rest}
  defp read(:reply, 2, <<n_data::little-32, v_data::binary-size(n_data), rest::binary>>), do: {:ok, :read, %{data: v_data}, rest}
  defp read(:request, 3, <<v_sector::little-64, n_data::little-32, v_data::binary-size(n_data), rest::binary>>), do: {:ok, :write, %{sector: v_sector, data: v_data}, rest}
  defp read(:reply, 3, <<rest::binary>>), do: {:ok, :write, %{}, rest}
  defp read(:request, 4, <<rest::binary>>), do: {:ok, :flush, %{}, rest}
  defp read(:reply, 4, <<rest::binary>>), do: {:ok, :flush, %{}, rest}
  defp read(:request, 5, <<v_sector::little-64, v_count::little-64, rest::binary>>), do: {:ok, :grant, %{sector: v_sector, count: v_count}, rest}
  defp read(:reply, 5, <<v_id::little-64, rest::binary>>), do: {:ok, :grant, %{id: v_id}, rest}
  defp read(:request, 6, <<v_id::little-64, rest::binary>>), do: {:ok, :release, %{id: v_id}, rest}
  defp read(:reply, 6, <<rest::binary>>), do: {:ok, :release, %{}, rest}
  defp read(_, _, _), do: {:error, :short_fields}
end
