# Typed messages of the `example` protocol.
#
# Generated by `redoubt-wire-gen` from the table in `redoubt/wire/tables/example.md`.
# Do not edit: change the table and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Proto.Example do
  @moduledoc """
  Codec for the `example` protocol: messages are `{name, fields}` with `fields` a map
  holding exactly the table's non-handle fields. See `Redoubt.Wire`.
  """
  alias Redoubt.Wire, as: W

  @doc "The layout of a message: opcode, shape, fields in order with their types, handle names."
  def layout(:ping), do: {1, :inline, [], []}
  def layout(:pong), do: {2, :inline, [{:seq, :u64}, {:flags, :u32}], []}
  def layout(:small), do: {3, :inline, [{:a, :u8}, {:b, :u16}], []}
  def layout(:wide), do: {4, :buffer, [{:a, :u64}, {:b, :u32}, {:c, :u8}], []}
  def layout(:named), do: {5, :buffer, [{:id, :u32}, {:name, :string}], []}
  def layout(:blob), do: {6, :buffer, [{:offset, :u64}, {:data, :bytes}, {:label, :string}], []}
  def layout(:grant), do: {7, :inline, [{:pages, :u32}], [:range, :reply]}
  def layout(:last), do: {4294967295, :buffer, [{:note, :string}], [:key]}
  def layout(_), do: nil

  @doc "Encodes `{name, fields}`: `{:ok, words, buffer}` or `{:error, reason}`."
  def encode({name, fields}) when is_atom(name) and is_map(fields), do: W.encoding(fn -> enc(name, fields) end)
  def encode(_), do: {:error, :bad_message}

  defp enc(:ping, %{} = f) when map_size(f) == 0, do: W.inline(1, [])
  defp enc(:pong, %{seq: v_seq, flags: v_flags} = f) when map_size(f) == 2, do: W.inline(2, [W.u(v_seq, 64), W.u(v_flags, 32)])
  defp enc(:small, %{a: v_a, b: v_b} = f) when map_size(f) == 2, do: W.inline(3, [W.u(v_a, 8), W.u(v_b, 16)])
  defp enc(:wide, %{a: v_a, b: v_b, c: v_c} = f) when map_size(f) == 3, do: W.buffer(4, [W.u(v_a, 64), W.u(v_b, 32), W.u(v_c, 8)])
  defp enc(:named, %{id: v_id, name: v_name} = f) when map_size(f) == 2, do: W.buffer(5, [W.u(v_id, 32), W.str(v_name)])
  defp enc(:blob, %{offset: v_offset, data: v_data, label: v_label} = f) when map_size(f) == 3, do: W.buffer(6, [W.u(v_offset, 64), W.bytes(v_data), W.str(v_label)])
  defp enc(:grant, %{pages: v_pages} = f) when map_size(f) == 1, do: W.inline(7, [W.u(v_pages, 32)])
  defp enc(:last, %{note: v_note} = f) when map_size(f) == 1, do: W.buffer(4294967295, [W.str(v_note)])
  defp enc(_, _), do: throw({:wire, :bad_message})

  @doc """
  Decodes a received message from its four words, its buffer (`<<>>` if none) and the
  number of handles it carried: `{:ok, {name, fields}}` or `{:error, reason}`.
  """
  def decode(words, buffer, handles) when is_binary(buffer) and is_integer(handles) do
    with {:ok, op} <- W.opcode(words),
         {:ok, name, fields, count} <- dec(op, words, buffer),
         :ok <- W.check_handles(handles, count) do
      {:ok, {name, fields}}
    end
  end

  def decode(_, _, _), do: {:error, :bad_message}

  defp dec(1, words, buffer) do
    with {:ok, body} <- W.inline_body(words, buffer),
         <<pad::binary>> <- body,
         true <- W.zero?(pad) do
      {:ok, :ping, %{}, 0}
    else
      {:error, _} = e -> e
      _ -> {:error, :malformed}
    end
  end

  defp dec(2, words, buffer) do
    with {:ok, body} <- W.inline_body(words, buffer),
         <<v_seq::little-64, v_flags::little-32, pad::binary>> <- body,
         true <- W.zero?(pad) do
      {:ok, :pong, %{seq: v_seq, flags: v_flags}, 0}
    else
      {:error, _} = e -> e
      _ -> {:error, :malformed}
    end
  end

  defp dec(3, words, buffer) do
    with {:ok, body} <- W.inline_body(words, buffer),
         <<v_a::little-8, v_b::little-16, pad::binary>> <- body,
         true <- W.zero?(pad) do
      {:ok, :small, %{a: v_a, b: v_b}, 0}
    else
      {:error, _} = e -> e
      _ -> {:error, :malformed}
    end
  end

  defp dec(4, words, buffer) do
    with {:ok, body} <- W.buffer_body(words, buffer),
         <<v_a::little-64, v_b::little-32, v_c::little-8>> <- body do
      {:ok, :wide, %{a: v_a, b: v_b, c: v_c}, 0}
    else
      {:error, _} = e -> e
      _ -> {:error, :malformed}
    end
  end

  defp dec(5, words, buffer) do
    with {:ok, body} <- W.buffer_body(words, buffer),
         <<v_id::little-32, n_name::little-16, v_name::binary-size(n_name)>> <- body,
         true <- String.valid?(v_name) do
      {:ok, :named, %{id: v_id, name: v_name}, 0}
    else
      {:error, _} = e -> e
      _ -> {:error, :malformed}
    end
  end

  defp dec(6, words, buffer) do
    with {:ok, body} <- W.buffer_body(words, buffer),
         <<v_offset::little-64, n_data::little-32, v_data::binary-size(n_data), n_label::little-16, v_label::binary-size(n_label)>> <- body,
         true <- String.valid?(v_label) do
      {:ok, :blob, %{offset: v_offset, data: v_data, label: v_label}, 0}
    else
      {:error, _} = e -> e
      _ -> {:error, :malformed}
    end
  end

  defp dec(7, words, buffer) do
    with {:ok, body} <- W.inline_body(words, buffer),
         <<v_pages::little-32, pad::binary>> <- body,
         true <- W.zero?(pad) do
      {:ok, :grant, %{pages: v_pages}, 2}
    else
      {:error, _} = e -> e
      _ -> {:error, :malformed}
    end
  end

  defp dec(4294967295, words, buffer) do
    with {:ok, body} <- W.buffer_body(words, buffer),
         <<n_note::little-16, v_note::binary-size(n_note)>> <- body,
         true <- String.valid?(v_note) do
      {:ok, :last, %{note: v_note}, 1}
    else
      {:error, _} = e -> e
      _ -> {:error, :malformed}
    end
  end

  defp dec(_, _, _), do: {:error, :bad_opcode}
end
