//! Typed messages of the `blkd` protocol.
//!
//! Generated by `redoubt-wire-gen` from the tables in `planning/redoubt/IO-ARCHITECTURE.md`.
//! Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.

use crate::codec::{Error, Reader, Writer};
use crate::typed::{self, Layout, Words};

/// `info`: opcode 1, buffer; reply [`InfoReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Info {}

/// The reply to [`Info`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InfoReply {
    pub sectors: u64,
    pub sector_size: u32,
    pub read_only: u32,
}

/// `read`: opcode 2, buffer; reply [`ReadReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Read {
    pub sector: u64,
    pub count: u32,
}

/// The reply to [`Read`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReadReply<'a> {
    pub data: &'a [u8],
}

/// `write`: opcode 3, buffer; reply [`WriteReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Write<'a> {
    pub sector: u64,
    pub data: &'a [u8],
}

/// The reply to [`Write`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WriteReply {}

/// `flush`: opcode 4, inline; reply [`FlushReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Flush {}

/// The reply to [`Flush`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FlushReply {}

/// `grant`: opcode 5, buffer; reply [`GrantReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Grant {
    pub sector: u64,
    pub count: u64,
}

/// The reply to [`Grant`].
///
/// Handle slots: `range` (slot 0, endpoint).
/// Kinds are documentation, checked by use: a handle of the wrong kind gets `WrongObject`
/// on first use.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GrantReply {
    pub id: u64,
}

/// `release`: opcode 6, inline; reply [`ReleaseReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Release {
    pub id: u64,
}

/// The reply to [`Release`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReleaseReply {}

/// Requests by opcode.
const REQUESTS: &[Layout] = &[
    Layout { opcode: 1, inline: false, handles: 0 },
    Layout { opcode: 2, inline: false, handles: 0 },
    Layout { opcode: 3, inline: false, handles: 0 },
    Layout { opcode: 4, inline: true, handles: 0 },
    Layout { opcode: 5, inline: false, handles: 0 },
    Layout { opcode: 6, inline: true, handles: 0 },
];

/// Every request of the protocol.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Message<'a> {
    Info(Info),
    Read(Read),
    Write(Write<'a>),
    Flush(Flush),
    Grant(Grant),
    Release(Release),
}

impl<'a> Message<'a> {
    /// The handles it carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Message::Info(_) => &[],
            Message::Read(_) => &[],
            Message::Write(_) => &[],
            Message::Flush(_) => &[],
            Message::Grant(_) => &[],
            Message::Release(_) => &[],
        }
    }

    /// The opcode in word 0.
    fn opcode(&self) -> u32 {
        match self {
            Message::Info(_) => 1,
            Message::Read(_) => 2,
            Message::Write(_) => 3,
            Message::Flush(_) => 4,
            Message::Grant(_) => 5,
            Message::Release(_) => 6,
        }
    }

    fn write(&self, w: &mut Writer<'_>) -> Result<(), Error> {
        match self {
            Message::Info(_) => Ok(()),
            Message::Read(m) => {
                w.u64(m.sector)?;
                w.u32(m.count)
            }
            Message::Write(m) => {
                w.u64(m.sector)?;
                w.bytes(m.data)
            }
            Message::Flush(_) => Ok(()),
            Message::Grant(m) => {
                w.u64(m.sector)?;
                w.u64(m.count)
            }
            Message::Release(m) => w.u64(m.id),
        }
    }

    fn read_inline(opcode: u32, r: &mut Reader<'_>) -> Result<Self, Error> {
        Ok(match opcode {
            4 => Message::Flush(Flush {}),
            6 => Message::Release(Release { id: r.u64()? }),
            _ => return Err(Error::BadOpcode),
        })
    }

    fn read_buffer(opcode: u32, r: &mut Reader<'a>) -> Result<Self, Error> {
        Ok(match opcode {
            1 => Message::Info(Info {}),
            2 => Message::Read(Read { sector: r.u64()?, count: r.u32()? }),
            3 => Message::Write(Write { sector: r.u64()?, data: r.bytes()? }),
            4 => Message::Flush(Flush {}),
            5 => Message::Grant(Grant { sector: r.u64()?, count: r.u64()? }),
            6 => Message::Release(Release { id: r.u64()? }),
            _ => return Err(Error::BadOpcode),
        })
    }

    /// Decodes a received request: its words, the buffer that came with it (empty if
    /// none), and how many handles it carried.
    pub fn decode(words: &Words, buf: &'a [u8], handles: usize) -> Result<Self, Error> {
        let layout = typed::layout(REQUESTS, typed::opcode(words)?)?;
        typed::decode(layout, words, buf, handles, Self::read_inline, Self::read_buffer)
    }

    /// Encodes the request: returns its words, and writes the fields into `buf` if it is
    /// a buffer message (the buffer's length is then in word 1).
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        let opcode = self.opcode();
        typed::encode(typed::layout(REQUESTS, opcode)?, opcode, buf, |w| self.write(w))
    }

    /// Decodes a request written into a 9P file: all of `bytes` is one operation.
    pub fn decode_file(bytes: &'a [u8]) -> Result<Self, Error> {
        typed::decode_file(REQUESTS, bytes, Self::read_buffer)
    }

    /// Writes the request in the file framing into the front of `out`; returns its length.
    pub fn encode_file(&self, out: &mut [u8]) -> Result<usize, Error> {
        typed::encode_file(typed::layout(REQUESTS, self.opcode())?, out, |w| self.write(w))
    }
}

/// Replies, by the opcode of their request.
const REPLIES: &[Layout] = &[
    Layout { opcode: 1, inline: false, handles: 0 },
    Layout { opcode: 2, inline: false, handles: 0 },
    Layout { opcode: 3, inline: false, handles: 0 },
    Layout { opcode: 4, inline: true, handles: 0 },
    Layout { opcode: 5, inline: false, handles: 1 },
    Layout { opcode: 6, inline: true, handles: 0 },
];

/// Every successful reply of the protocol, named after its request.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reply<'a> {
    Info(InfoReply),
    Read(ReadReply<'a>),
    Write(WriteReply),
    Flush(FlushReply),
    Grant(GrantReply),
    Release(ReleaseReply),
}

impl<'a> Reply<'a> {
    /// The handles it carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Reply::Info(_) => &[],
            Reply::Read(_) => &[],
            Reply::Write(_) => &[],
            Reply::Flush(_) => &[],
            Reply::Grant(_) => &["range"],
            Reply::Release(_) => &[],
        }
    }

    /// The opcode of the request this replies to.
    fn opcode(&self) -> u32 {
        match self {
            Reply::Info(_) => 1,
            Reply::Read(_) => 2,
            Reply::Write(_) => 3,
            Reply::Flush(_) => 4,
            Reply::Grant(_) => 5,
            Reply::Release(_) => 6,
        }
    }

    fn write(&self, w: &mut Writer<'_>) -> Result<(), Error> {
        match self {
            Reply::Info(m) => {
                w.u64(m.sectors)?;
                w.u32(m.sector_size)?;
                w.u32(m.read_only)
            }
            Reply::Read(m) => w.bytes(m.data),
            Reply::Write(_) => Ok(()),
            Reply::Flush(_) => Ok(()),
            Reply::Grant(m) => w.u64(m.id),
            Reply::Release(_) => Ok(()),
        }
    }

    fn read_inline(opcode: u32, _r: &mut Reader<'_>) -> Result<Self, Error> {
        Ok(match opcode {
            4 => Reply::Flush(FlushReply {}),
            6 => Reply::Release(ReleaseReply {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    fn read_buffer(opcode: u32, r: &mut Reader<'a>) -> Result<Self, Error> {
        Ok(match opcode {
            1 => Reply::Info(InfoReply { sectors: r.u64()?, sector_size: r.u32()?, read_only: r.u32()? }),
            2 => Reply::Read(ReadReply { data: r.bytes()? }),
            3 => Reply::Write(WriteReply {}),
            4 => Reply::Flush(FlushReply {}),
            5 => Reply::Grant(GrantReply { id: r.u64()? }),
            6 => Reply::Release(ReleaseReply {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    /// Decodes the reply to the request with `opcode` (the caller knows what it sent):
    /// `Ok(Ok(reply))`, `Ok(Err(code))`
    /// for an error reply, or `Err` if the reply is malformed.
    pub fn decode(opcode: u32, words: &Words, buf: &'a [u8], handles: usize) -> Result<Result<Self, ErrorCode>, Error> {
        let layout = typed::layout(REPLIES, opcode)?;
        if let Some(code) = typed::reply_status(words, handles)? {
            return ErrorCode::from_code(code).map(Err).ok_or(Error::BadStatus);
        }
        typed::decode(layout, words, buf, handles, Self::read_inline, Self::read_buffer).map(Ok)
    }

    /// Encodes the reply (status 0): returns its words, and writes the fields into `buf`
    /// (the caller's lend) if it is a buffer message.
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        typed::encode(typed::layout(REPLIES, self.opcode())?, 0, buf, |w| self.write(w))
    }
}

/// The protocol's error codes: word 0 of an error reply. Code 1, `Malformed`, is every
/// protocol's: a request that does not decode (WIRE.md, Errors).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ErrorCode {
    Malformed,
    NotPermitted,
    OutOfRange,
    TooMany,
    Failed,
}

impl ErrorCode {
    pub fn code(self) -> u32 {
        match self {
            ErrorCode::Malformed => 1,
            ErrorCode::NotPermitted => 2,
            ErrorCode::OutOfRange => 3,
            ErrorCode::TooMany => 4,
            ErrorCode::Failed => 5,
        }
    }

    pub fn from_code(code: u32) -> Option<Self> {
        match code {
            1 => Some(ErrorCode::Malformed),
            2 => Some(ErrorCode::NotPermitted),
            3 => Some(ErrorCode::OutOfRange),
            4 => Some(ErrorCode::TooMany),
            5 => Some(ErrorCode::Failed),
            _ => None,
        }
    }

    /// The words of the error reply (no buffer, no handles).
    pub fn encode(self) -> Words {
        typed::error_reply(self.code())
    }
}
