//! Typed messages of the `example` protocol.
//!
//! Generated by `redoubt-wire-gen` from the table in `redoubt/wire/tables/example.md`.
//! Do not edit: change the table and run `cargo run -p redoubt-wire-gen`.

use crate::codec::{Error, Reader};
use crate::typed::{self, Value, Words};

/// `ping`: opcode 1, inline.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Ping {}

/// `pong`: opcode 2, inline.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Pong {
    pub seq: u64,
    pub flags: u32,
}

/// `small`: opcode 3, inline.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Small {
    pub a: u8,
    pub b: u16,
}

/// `wide`: opcode 4, buffer.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Wide {
    pub a: u64,
    pub b: u32,
    pub c: u8,
}

/// `named`: opcode 5, buffer.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Named<'a> {
    pub id: u32,
    pub name: &'a str,
}

/// `blob`: opcode 6, buffer.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Blob<'a> {
    pub offset: u64,
    pub data: &'a [u8],
    pub label: &'a str,
}

/// `grant`: opcode 7, inline.
/// Handle slots: `range`, `reply`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Grant {
    pub pages: u32,
}

/// `last`: opcode 4294967295, buffer.
/// Handle slots: `key`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Last<'a> {
    pub note: &'a str,
}

/// Every message of the protocol.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Message<'a> {
    Ping(Ping),
    Pong(Pong),
    Small(Small),
    Wide(Wide),
    Named(Named<'a>),
    Blob(Blob<'a>),
    Grant(Grant),
    Last(Last<'a>),
}

impl<'a> Message<'a> {
    /// The opcode in word 0.
    pub fn opcode(&self) -> u32 {
        match self {
            Message::Ping(_) => 1,
            Message::Pong(_) => 2,
            Message::Small(_) => 3,
            Message::Wide(_) => 4,
            Message::Named(_) => 5,
            Message::Blob(_) => 6,
            Message::Grant(_) => 7,
            Message::Last(_) => 4294967295,
        }
    }

    /// The message's name in the table.
    pub fn name(&self) -> &'static str {
        match self {
            Message::Ping(_) => "ping",
            Message::Pong(_) => "pong",
            Message::Small(_) => "small",
            Message::Wide(_) => "wide",
            Message::Named(_) => "named",
            Message::Blob(_) => "blob",
            Message::Grant(_) => "grant",
            Message::Last(_) => "last",
        }
    }

    /// The handles the message carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Message::Ping(_) => &[],
            Message::Pong(_) => &[],
            Message::Small(_) => &[],
            Message::Wide(_) => &[],
            Message::Named(_) => &[],
            Message::Blob(_) => &[],
            Message::Grant(_) => &["range", "reply"],
            Message::Last(_) => &["key"],
        }
    }

    /// Decodes a received message: its words, the buffer that came with it (empty if
    /// none), and how many handles it carried.
    pub fn decode(words: &Words, buf: &'a [u8], handles: usize) -> Result<Self, Error> {
        let message = match typed::opcode(words)? {
            1 => {
                let bytes = typed::inline_bytes(words, buf)?;
                let r = Reader::new(&bytes);
                let m = Ping {};
                r.finish_padding()?;
                Message::Ping(m)
            }
            2 => {
                let bytes = typed::inline_bytes(words, buf)?;
                let mut r = Reader::new(&bytes);
                let m = Pong { seq: r.u64()?, flags: r.u32()? };
                r.finish_padding()?;
                Message::Pong(m)
            }
            3 => {
                let bytes = typed::inline_bytes(words, buf)?;
                let mut r = Reader::new(&bytes);
                let m = Small { a: r.u8()?, b: r.u16()? };
                r.finish_padding()?;
                Message::Small(m)
            }
            4 => {
                let mut r = Reader::new(typed::buffer_body(words, buf)?);
                let m = Wide { a: r.u64()?, b: r.u32()?, c: r.u8()? };
                r.finish()?;
                Message::Wide(m)
            }
            5 => {
                let mut r = Reader::new(typed::buffer_body(words, buf)?);
                let m = Named { id: r.u32()?, name: r.string()? };
                r.finish()?;
                Message::Named(m)
            }
            6 => {
                let mut r = Reader::new(typed::buffer_body(words, buf)?);
                let m = Blob { offset: r.u64()?, data: r.bytes()?, label: r.string()? };
                r.finish()?;
                Message::Blob(m)
            }
            7 => {
                let bytes = typed::inline_bytes(words, buf)?;
                let mut r = Reader::new(&bytes);
                let m = Grant { pages: r.u32()? };
                r.finish_padding()?;
                Message::Grant(m)
            }
            4294967295 => {
                let mut r = Reader::new(typed::buffer_body(words, buf)?);
                let m = Last { note: r.string()? };
                r.finish()?;
                Message::Last(m)
            }
            _ => return Err(Error::BadOpcode),
        };
        typed::check_handles(handles, message.handle_names().len())?;
        Ok(message)
    }

    /// Encodes the message: returns its words, and writes the fields into `buf` if it
    /// is a buffer message (the buffer's length is then in word 1).
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        match self {
            Message::Ping(_) => typed::encode_inline(1, |_| Ok(())),
            Message::Pong(m) => typed::encode_inline(2, |w| {
                w.u64(m.seq)?;
                w.u32(m.flags)
            }),
            Message::Small(m) => typed::encode_inline(3, |w| {
                w.u8(m.a)?;
                w.u16(m.b)
            }),
            Message::Wide(m) => typed::encode_buffer(4, buf, |w| {
                w.u64(m.a)?;
                w.u32(m.b)?;
                w.u8(m.c)
            }),
            Message::Named(m) => typed::encode_buffer(5, buf, |w| {
                w.u32(m.id)?;
                w.string(m.name)
            }),
            Message::Blob(m) => typed::encode_buffer(6, buf, |w| {
                w.u64(m.offset)?;
                w.bytes(m.data)?;
                w.string(m.label)
            }),
            Message::Grant(m) => typed::encode_inline(7, |w| w.u32(m.pages)),
            Message::Last(m) => typed::encode_buffer(4294967295, buf, |w| w.string(m.note)),
        }
    }

    /// Calls `f` with each field's name and value, in table order (handles excluded).
    pub fn fields(&self, f: &mut dyn FnMut(&'static str, Value<'_>)) {
        match self {
            Message::Ping(_) => {}
            Message::Pong(m) => {
                f("seq", Value::U64(m.seq));
                f("flags", Value::U32(m.flags));
            }
            Message::Small(m) => {
                f("a", Value::U8(m.a));
                f("b", Value::U16(m.b));
            }
            Message::Wide(m) => {
                f("a", Value::U64(m.a));
                f("b", Value::U32(m.b));
                f("c", Value::U8(m.c));
            }
            Message::Named(m) => {
                f("id", Value::U32(m.id));
                f("name", Value::Str(m.name));
            }
            Message::Blob(m) => {
                f("offset", Value::U64(m.offset));
                f("data", Value::Bytes(m.data));
                f("label", Value::Str(m.label));
            }
            Message::Grant(m) => {
                f("pages", Value::U32(m.pages));
            }
            Message::Last(m) => {
                f("note", Value::Str(m.note));
            }
        }
    }
}
