//! Generated typed-message codecs, one module per protocol table.
//!
//! Generated by `redoubt-wire-gen`. Do not edit: change the tables and run
//! `cargo run -p redoubt-wire-gen`.

pub mod example;
