// Generated by tools/gen-opcodes.escript from tools/genop.tab. Do not edit.

/// One row of the compiler's opcode table.
pub struct Op {
    pub name: &'static str,
    pub arity: u8,
    /// The pinned compiler never emits it; the loader refuses it.
    pub deprecated: bool,
}

/// Highest opcode number the pinned compiler knows.
pub const MAX_OPCODE: u8 = 184;

/// Indexed by opcode number. Index 0 is not an opcode.
pub static OPCODES: [Op; 185] = [
    Op {
        name: "",
        arity: 0,
        deprecated: true,
    },
    Op {
        name: "label",
        arity: 1,
        deprecated: false,
    }, // 1
    Op {
        name: "func_info",
        arity: 3,
        deprecated: false,
    }, // 2
    Op {
        name: "int_code_end",
        arity: 0,
        deprecated: false,
    }, // 3
    Op {
        name: "call",
        arity: 2,
        deprecated: false,
    }, // 4
    Op {
        name: "call_last",
        arity: 3,
        deprecated: false,
    }, // 5
    Op {
        name: "call_only",
        arity: 2,
        deprecated: false,
    }, // 6
    Op {
        name: "call_ext",
        arity: 2,
        deprecated: false,
    }, // 7
    Op {
        name: "call_ext_last",
        arity: 3,
        deprecated: false,
    }, // 8
    Op {
        name: "bif0",
        arity: 2,
        deprecated: false,
    }, // 9
    Op {
        name: "bif1",
        arity: 4,
        deprecated: false,
    }, // 10
    Op {
        name: "bif2",
        arity: 5,
        deprecated: false,
    }, // 11
    Op {
        name: "allocate",
        arity: 2,
        deprecated: false,
    }, // 12
    Op {
        name: "allocate_heap",
        arity: 3,
        deprecated: false,
    }, // 13
    Op {
        name: "allocate_zero",
        arity: 2,
        deprecated: true,
    }, // 14
    Op {
        name: "allocate_heap_zero",
        arity: 3,
        deprecated: true,
    }, // 15
    Op {
        name: "test_heap",
        arity: 2,
        deprecated: false,
    }, // 16
    Op {
        name: "init",
        arity: 1,
        deprecated: true,
    }, // 17
    Op {
        name: "deallocate",
        arity: 1,
        deprecated: false,
    }, // 18
    Op {
        name: "return",
        arity: 0,
        deprecated: false,
    }, // 19
    Op {
        name: "send",
        arity: 0,
        deprecated: false,
    }, // 20
    Op {
        name: "remove_message",
        arity: 0,
        deprecated: false,
    }, // 21
    Op {
        name: "timeout",
        arity: 0,
        deprecated: false,
    }, // 22
    Op {
        name: "loop_rec",
        arity: 2,
        deprecated: false,
    }, // 23
    Op {
        name: "loop_rec_end",
        arity: 1,
        deprecated: false,
    }, // 24
    Op {
        name: "wait",
        arity: 1,
        deprecated: false,
    }, // 25
    Op {
        name: "wait_timeout",
        arity: 2,
        deprecated: false,
    }, // 26
    Op {
        name: "m_plus",
        arity: 4,
        deprecated: true,
    }, // 27
    Op {
        name: "m_minus",
        arity: 4,
        deprecated: true,
    }, // 28
    Op {
        name: "m_times",
        arity: 4,
        deprecated: true,
    }, // 29
    Op {
        name: "m_div",
        arity: 4,
        deprecated: true,
    }, // 30
    Op {
        name: "int_div",
        arity: 4,
        deprecated: true,
    }, // 31
    Op {
        name: "int_rem",
        arity: 4,
        deprecated: true,
    }, // 32
    Op {
        name: "int_band",
        arity: 4,
        deprecated: true,
    }, // 33
    Op {
        name: "int_bor",
        arity: 4,
        deprecated: true,
    }, // 34
    Op {
        name: "int_bxor",
        arity: 4,
        deprecated: true,
    }, // 35
    Op {
        name: "int_bsl",
        arity: 4,
        deprecated: true,
    }, // 36
    Op {
        name: "int_bsr",
        arity: 4,
        deprecated: true,
    }, // 37
    Op {
        name: "int_bnot",
        arity: 3,
        deprecated: true,
    }, // 38
    Op {
        name: "is_lt",
        arity: 3,
        deprecated: false,
    }, // 39
    Op {
        name: "is_ge",
        arity: 3,
        deprecated: false,
    }, // 40
    Op {
        name: "is_eq",
        arity: 3,
        deprecated: false,
    }, // 41
    Op {
        name: "is_ne",
        arity: 3,
        deprecated: false,
    }, // 42
    Op {
        name: "is_eq_exact",
        arity: 3,
        deprecated: false,
    }, // 43
    Op {
        name: "is_ne_exact",
        arity: 3,
        deprecated: false,
    }, // 44
    Op {
        name: "is_integer",
        arity: 2,
        deprecated: false,
    }, // 45
    Op {
        name: "is_float",
        arity: 2,
        deprecated: false,
    }, // 46
    Op {
        name: "is_number",
        arity: 2,
        deprecated: false,
    }, // 47
    Op {
        name: "is_atom",
        arity: 2,
        deprecated: false,
    }, // 48
    Op {
        name: "is_pid",
        arity: 2,
        deprecated: false,
    }, // 49
    Op {
        name: "is_reference",
        arity: 2,
        deprecated: false,
    }, // 50
    Op {
        name: "is_port",
        arity: 2,
        deprecated: false,
    }, // 51
    Op {
        name: "is_nil",
        arity: 2,
        deprecated: false,
    }, // 52
    Op {
        name: "is_binary",
        arity: 2,
        deprecated: false,
    }, // 53
    Op {
        name: "is_constant",
        arity: 2,
        deprecated: true,
    }, // 54
    Op {
        name: "is_list",
        arity: 2,
        deprecated: false,
    }, // 55
    Op {
        name: "is_nonempty_list",
        arity: 2,
        deprecated: false,
    }, // 56
    Op {
        name: "is_tuple",
        arity: 2,
        deprecated: false,
    }, // 57
    Op {
        name: "test_arity",
        arity: 3,
        deprecated: false,
    }, // 58
    Op {
        name: "select_val",
        arity: 3,
        deprecated: false,
    }, // 59
    Op {
        name: "select_tuple_arity",
        arity: 3,
        deprecated: false,
    }, // 60
    Op {
        name: "jump",
        arity: 1,
        deprecated: false,
    }, // 61
    Op {
        name: "catch",
        arity: 2,
        deprecated: false,
    }, // 62
    Op {
        name: "catch_end",
        arity: 1,
        deprecated: false,
    }, // 63
    Op {
        name: "move",
        arity: 2,
        deprecated: false,
    }, // 64
    Op {
        name: "get_list",
        arity: 3,
        deprecated: false,
    }, // 65
    Op {
        name: "get_tuple_element",
        arity: 3,
        deprecated: false,
    }, // 66
    Op {
        name: "set_tuple_element",
        arity: 3,
        deprecated: false,
    }, // 67
    Op {
        name: "put_string",
        arity: 3,
        deprecated: true,
    }, // 68
    Op {
        name: "put_list",
        arity: 3,
        deprecated: false,
    }, // 69
    Op {
        name: "put_tuple",
        arity: 2,
        deprecated: true,
    }, // 70
    Op {
        name: "put",
        arity: 1,
        deprecated: true,
    }, // 71
    Op {
        name: "badmatch",
        arity: 1,
        deprecated: false,
    }, // 72
    Op {
        name: "if_end",
        arity: 0,
        deprecated: false,
    }, // 73
    Op {
        name: "case_end",
        arity: 1,
        deprecated: false,
    }, // 74
    Op {
        name: "call_fun",
        arity: 1,
        deprecated: false,
    }, // 75
    Op {
        name: "make_fun",
        arity: 3,
        deprecated: true,
    }, // 76
    Op {
        name: "is_function",
        arity: 2,
        deprecated: false,
    }, // 77
    Op {
        name: "call_ext_only",
        arity: 2,
        deprecated: false,
    }, // 78
    Op {
        name: "bs_start_match",
        arity: 2,
        deprecated: true,
    }, // 79
    Op {
        name: "bs_get_integer",
        arity: 5,
        deprecated: true,
    }, // 80
    Op {
        name: "bs_get_float",
        arity: 5,
        deprecated: true,
    }, // 81
    Op {
        name: "bs_get_binary",
        arity: 5,
        deprecated: true,
    }, // 82
    Op {
        name: "bs_skip_bits",
        arity: 4,
        deprecated: true,
    }, // 83
    Op {
        name: "bs_test_tail",
        arity: 2,
        deprecated: true,
    }, // 84
    Op {
        name: "bs_save",
        arity: 1,
        deprecated: true,
    }, // 85
    Op {
        name: "bs_restore",
        arity: 1,
        deprecated: true,
    }, // 86
    Op {
        name: "bs_init",
        arity: 2,
        deprecated: true,
    }, // 87
    Op {
        name: "bs_final",
        arity: 2,
        deprecated: true,
    }, // 88
    Op {
        name: "bs_put_integer",
        arity: 5,
        deprecated: true,
    }, // 89
    Op {
        name: "bs_put_binary",
        arity: 5,
        deprecated: true,
    }, // 90
    Op {
        name: "bs_put_float",
        arity: 5,
        deprecated: true,
    }, // 91
    Op {
        name: "bs_put_string",
        arity: 2,
        deprecated: true,
    }, // 92
    Op {
        name: "bs_need_buf",
        arity: 1,
        deprecated: true,
    }, // 93
    Op {
        name: "fclearerror",
        arity: 0,
        deprecated: true,
    }, // 94
    Op {
        name: "fcheckerror",
        arity: 1,
        deprecated: true,
    }, // 95
    Op {
        name: "fmove",
        arity: 2,
        deprecated: false,
    }, // 96
    Op {
        name: "fconv",
        arity: 2,
        deprecated: false,
    }, // 97
    Op {
        name: "fadd",
        arity: 4,
        deprecated: false,
    }, // 98
    Op {
        name: "fsub",
        arity: 4,
        deprecated: false,
    }, // 99
    Op {
        name: "fmul",
        arity: 4,
        deprecated: false,
    }, // 100
    Op {
        name: "fdiv",
        arity: 4,
        deprecated: false,
    }, // 101
    Op {
        name: "fnegate",
        arity: 3,
        deprecated: false,
    }, // 102
    Op {
        name: "make_fun2",
        arity: 1,
        deprecated: true,
    }, // 103
    Op {
        name: "try",
        arity: 2,
        deprecated: false,
    }, // 104
    Op {
        name: "try_end",
        arity: 1,
        deprecated: false,
    }, // 105
    Op {
        name: "try_case",
        arity: 1,
        deprecated: false,
    }, // 106
    Op {
        name: "try_case_end",
        arity: 1,
        deprecated: false,
    }, // 107
    Op {
        name: "raise",
        arity: 2,
        deprecated: false,
    }, // 108
    Op {
        name: "bs_init2",
        arity: 6,
        deprecated: true,
    }, // 109
    Op {
        name: "bs_bits_to_bytes",
        arity: 3,
        deprecated: true,
    }, // 110
    Op {
        name: "bs_add",
        arity: 5,
        deprecated: true,
    }, // 111
    Op {
        name: "apply",
        arity: 1,
        deprecated: false,
    }, // 112
    Op {
        name: "apply_last",
        arity: 2,
        deprecated: false,
    }, // 113
    Op {
        name: "is_boolean",
        arity: 2,
        deprecated: false,
    }, // 114
    Op {
        name: "is_function2",
        arity: 3,
        deprecated: false,
    }, // 115
    Op {
        name: "bs_start_match2",
        arity: 5,
        deprecated: true,
    }, // 116
    Op {
        name: "bs_get_integer2",
        arity: 7,
        deprecated: false,
    }, // 117
    Op {
        name: "bs_get_float2",
        arity: 7,
        deprecated: false,
    }, // 118
    Op {
        name: "bs_get_binary2",
        arity: 7,
        deprecated: false,
    }, // 119
    Op {
        name: "bs_skip_bits2",
        arity: 5,
        deprecated: false,
    }, // 120
    Op {
        name: "bs_test_tail2",
        arity: 3,
        deprecated: false,
    }, // 121
    Op {
        name: "bs_save2",
        arity: 2,
        deprecated: true,
    }, // 122
    Op {
        name: "bs_restore2",
        arity: 2,
        deprecated: true,
    }, // 123
    Op {
        name: "gc_bif1",
        arity: 5,
        deprecated: false,
    }, // 124
    Op {
        name: "gc_bif2",
        arity: 6,
        deprecated: false,
    }, // 125
    Op {
        name: "bs_final2",
        arity: 2,
        deprecated: true,
    }, // 126
    Op {
        name: "bs_bits_to_bytes2",
        arity: 2,
        deprecated: true,
    }, // 127
    Op {
        name: "put_literal",
        arity: 2,
        deprecated: true,
    }, // 128
    Op {
        name: "is_bitstr",
        arity: 2,
        deprecated: false,
    }, // 129
    Op {
        name: "bs_context_to_binary",
        arity: 1,
        deprecated: true,
    }, // 130
    Op {
        name: "bs_test_unit",
        arity: 3,
        deprecated: false,
    }, // 131
    Op {
        name: "bs_match_string",
        arity: 4,
        deprecated: false,
    }, // 132
    Op {
        name: "bs_init_writable",
        arity: 0,
        deprecated: false,
    }, // 133
    Op {
        name: "bs_append",
        arity: 8,
        deprecated: true,
    }, // 134
    Op {
        name: "bs_private_append",
        arity: 6,
        deprecated: true,
    }, // 135
    Op {
        name: "trim",
        arity: 2,
        deprecated: false,
    }, // 136
    Op {
        name: "bs_init_bits",
        arity: 6,
        deprecated: true,
    }, // 137
    Op {
        name: "bs_get_utf8",
        arity: 5,
        deprecated: false,
    }, // 138
    Op {
        name: "bs_skip_utf8",
        arity: 4,
        deprecated: false,
    }, // 139
    Op {
        name: "bs_get_utf16",
        arity: 5,
        deprecated: false,
    }, // 140
    Op {
        name: "bs_skip_utf16",
        arity: 4,
        deprecated: false,
    }, // 141
    Op {
        name: "bs_get_utf32",
        arity: 5,
        deprecated: false,
    }, // 142
    Op {
        name: "bs_skip_utf32",
        arity: 4,
        deprecated: false,
    }, // 143
    Op {
        name: "bs_utf8_size",
        arity: 3,
        deprecated: true,
    }, // 144
    Op {
        name: "bs_put_utf8",
        arity: 3,
        deprecated: true,
    }, // 145
    Op {
        name: "bs_utf16_size",
        arity: 3,
        deprecated: true,
    }, // 146
    Op {
        name: "bs_put_utf16",
        arity: 3,
        deprecated: true,
    }, // 147
    Op {
        name: "bs_put_utf32",
        arity: 3,
        deprecated: true,
    }, // 148
    Op {
        name: "on_load",
        arity: 0,
        deprecated: false,
    }, // 149
    Op {
        name: "recv_mark",
        arity: 1,
        deprecated: true,
    }, // 150
    Op {
        name: "recv_set",
        arity: 1,
        deprecated: true,
    }, // 151
    Op {
        name: "gc_bif3",
        arity: 7,
        deprecated: false,
    }, // 152
    Op {
        name: "line",
        arity: 1,
        deprecated: false,
    }, // 153
    Op {
        name: "put_map_assoc",
        arity: 5,
        deprecated: false,
    }, // 154
    Op {
        name: "put_map_exact",
        arity: 5,
        deprecated: false,
    }, // 155
    Op {
        name: "is_map",
        arity: 2,
        deprecated: false,
    }, // 156
    Op {
        name: "has_map_fields",
        arity: 3,
        deprecated: false,
    }, // 157
    Op {
        name: "get_map_elements",
        arity: 3,
        deprecated: false,
    }, // 158
    Op {
        name: "is_tagged_tuple",
        arity: 4,
        deprecated: false,
    }, // 159
    Op {
        name: "build_stacktrace",
        arity: 0,
        deprecated: false,
    }, // 160
    Op {
        name: "raw_raise",
        arity: 0,
        deprecated: false,
    }, // 161
    Op {
        name: "get_hd",
        arity: 2,
        deprecated: false,
    }, // 162
    Op {
        name: "get_tl",
        arity: 2,
        deprecated: false,
    }, // 163
    Op {
        name: "put_tuple2",
        arity: 2,
        deprecated: false,
    }, // 164
    Op {
        name: "bs_get_tail",
        arity: 3,
        deprecated: false,
    }, // 165
    Op {
        name: "bs_start_match3",
        arity: 4,
        deprecated: false,
    }, // 166
    Op {
        name: "bs_get_position",
        arity: 3,
        deprecated: false,
    }, // 167
    Op {
        name: "bs_set_position",
        arity: 2,
        deprecated: false,
    }, // 168
    Op {
        name: "swap",
        arity: 2,
        deprecated: false,
    }, // 169
    Op {
        name: "bs_start_match4",
        arity: 4,
        deprecated: false,
    }, // 170
    Op {
        name: "make_fun3",
        arity: 3,
        deprecated: false,
    }, // 171
    Op {
        name: "init_yregs",
        arity: 1,
        deprecated: false,
    }, // 172
    Op {
        name: "recv_marker_bind",
        arity: 2,
        deprecated: false,
    }, // 173
    Op {
        name: "recv_marker_clear",
        arity: 1,
        deprecated: false,
    }, // 174
    Op {
        name: "recv_marker_reserve",
        arity: 1,
        deprecated: false,
    }, // 175
    Op {
        name: "recv_marker_use",
        arity: 1,
        deprecated: false,
    }, // 176
    Op {
        name: "bs_create_bin",
        arity: 6,
        deprecated: false,
    }, // 177
    Op {
        name: "call_fun2",
        arity: 3,
        deprecated: false,
    }, // 178
    Op {
        name: "nif_start",
        arity: 0,
        deprecated: false,
    }, // 179
    Op {
        name: "badrecord",
        arity: 1,
        deprecated: false,
    }, // 180
    Op {
        name: "update_record",
        arity: 5,
        deprecated: false,
    }, // 181
    Op {
        name: "bs_match",
        arity: 3,
        deprecated: false,
    }, // 182
    Op {
        name: "executable_line",
        arity: 2,
        deprecated: false,
    }, // 183
    Op {
        name: "debug_line",
        arity: 4,
        deprecated: false,
    }, // 184
];

pub const LABEL: u8 = 1;
pub const FUNC_INFO: u8 = 2;
pub const INT_CODE_END: u8 = 3;
pub const CALL: u8 = 4;
pub const CALL_LAST: u8 = 5;
pub const CALL_ONLY: u8 = 6;
pub const CALL_EXT: u8 = 7;
pub const CALL_EXT_LAST: u8 = 8;
pub const BIF0: u8 = 9;
pub const BIF1: u8 = 10;
pub const BIF2: u8 = 11;
pub const ALLOCATE: u8 = 12;
pub const ALLOCATE_HEAP: u8 = 13;
pub const ALLOCATE_ZERO: u8 = 14;
pub const ALLOCATE_HEAP_ZERO: u8 = 15;
pub const TEST_HEAP: u8 = 16;
pub const INIT: u8 = 17;
pub const DEALLOCATE: u8 = 18;
pub const RETURN: u8 = 19;
pub const SEND: u8 = 20;
pub const REMOVE_MESSAGE: u8 = 21;
pub const TIMEOUT: u8 = 22;
pub const LOOP_REC: u8 = 23;
pub const LOOP_REC_END: u8 = 24;
pub const WAIT: u8 = 25;
pub const WAIT_TIMEOUT: u8 = 26;
pub const M_PLUS: u8 = 27;
pub const M_MINUS: u8 = 28;
pub const M_TIMES: u8 = 29;
pub const M_DIV: u8 = 30;
pub const INT_DIV: u8 = 31;
pub const INT_REM: u8 = 32;
pub const INT_BAND: u8 = 33;
pub const INT_BOR: u8 = 34;
pub const INT_BXOR: u8 = 35;
pub const INT_BSL: u8 = 36;
pub const INT_BSR: u8 = 37;
pub const INT_BNOT: u8 = 38;
pub const IS_LT: u8 = 39;
pub const IS_GE: u8 = 40;
pub const IS_EQ: u8 = 41;
pub const IS_NE: u8 = 42;
pub const IS_EQ_EXACT: u8 = 43;
pub const IS_NE_EXACT: u8 = 44;
pub const IS_INTEGER: u8 = 45;
pub const IS_FLOAT: u8 = 46;
pub const IS_NUMBER: u8 = 47;
pub const IS_ATOM: u8 = 48;
pub const IS_PID: u8 = 49;
pub const IS_REFERENCE: u8 = 50;
pub const IS_PORT: u8 = 51;
pub const IS_NIL: u8 = 52;
pub const IS_BINARY: u8 = 53;
pub const IS_CONSTANT: u8 = 54;
pub const IS_LIST: u8 = 55;
pub const IS_NONEMPTY_LIST: u8 = 56;
pub const IS_TUPLE: u8 = 57;
pub const TEST_ARITY: u8 = 58;
pub const SELECT_VAL: u8 = 59;
pub const SELECT_TUPLE_ARITY: u8 = 60;
pub const JUMP: u8 = 61;
pub const CATCH: u8 = 62;
pub const CATCH_END: u8 = 63;
pub const MOVE: u8 = 64;
pub const GET_LIST: u8 = 65;
pub const GET_TUPLE_ELEMENT: u8 = 66;
pub const SET_TUPLE_ELEMENT: u8 = 67;
pub const PUT_STRING: u8 = 68;
pub const PUT_LIST: u8 = 69;
pub const PUT_TUPLE: u8 = 70;
pub const PUT: u8 = 71;
pub const BADMATCH: u8 = 72;
pub const IF_END: u8 = 73;
pub const CASE_END: u8 = 74;
pub const CALL_FUN: u8 = 75;
pub const MAKE_FUN: u8 = 76;
pub const IS_FUNCTION: u8 = 77;
pub const CALL_EXT_ONLY: u8 = 78;
pub const BS_START_MATCH: u8 = 79;
pub const BS_GET_INTEGER: u8 = 80;
pub const BS_GET_FLOAT: u8 = 81;
pub const BS_GET_BINARY: u8 = 82;
pub const BS_SKIP_BITS: u8 = 83;
pub const BS_TEST_TAIL: u8 = 84;
pub const BS_SAVE: u8 = 85;
pub const BS_RESTORE: u8 = 86;
pub const BS_INIT: u8 = 87;
pub const BS_FINAL: u8 = 88;
pub const BS_PUT_INTEGER: u8 = 89;
pub const BS_PUT_BINARY: u8 = 90;
pub const BS_PUT_FLOAT: u8 = 91;
pub const BS_PUT_STRING: u8 = 92;
pub const BS_NEED_BUF: u8 = 93;
pub const FCLEARERROR: u8 = 94;
pub const FCHECKERROR: u8 = 95;
pub const FMOVE: u8 = 96;
pub const FCONV: u8 = 97;
pub const FADD: u8 = 98;
pub const FSUB: u8 = 99;
pub const FMUL: u8 = 100;
pub const FDIV: u8 = 101;
pub const FNEGATE: u8 = 102;
pub const MAKE_FUN2: u8 = 103;
pub const TRY: u8 = 104;
pub const TRY_END: u8 = 105;
pub const TRY_CASE: u8 = 106;
pub const TRY_CASE_END: u8 = 107;
pub const RAISE: u8 = 108;
pub const BS_INIT2: u8 = 109;
pub const BS_BITS_TO_BYTES: u8 = 110;
pub const BS_ADD: u8 = 111;
pub const APPLY: u8 = 112;
pub const APPLY_LAST: u8 = 113;
pub const IS_BOOLEAN: u8 = 114;
pub const IS_FUNCTION2: u8 = 115;
pub const BS_START_MATCH2: u8 = 116;
pub const BS_GET_INTEGER2: u8 = 117;
pub const BS_GET_FLOAT2: u8 = 118;
pub const BS_GET_BINARY2: u8 = 119;
pub const BS_SKIP_BITS2: u8 = 120;
pub const BS_TEST_TAIL2: u8 = 121;
pub const BS_SAVE2: u8 = 122;
pub const BS_RESTORE2: u8 = 123;
pub const GC_BIF1: u8 = 124;
pub const GC_BIF2: u8 = 125;
pub const BS_FINAL2: u8 = 126;
pub const BS_BITS_TO_BYTES2: u8 = 127;
pub const PUT_LITERAL: u8 = 128;
pub const IS_BITSTR: u8 = 129;
pub const BS_CONTEXT_TO_BINARY: u8 = 130;
pub const BS_TEST_UNIT: u8 = 131;
pub const BS_MATCH_STRING: u8 = 132;
pub const BS_INIT_WRITABLE: u8 = 133;
pub const BS_APPEND: u8 = 134;
pub const BS_PRIVATE_APPEND: u8 = 135;
pub const TRIM: u8 = 136;
pub const BS_INIT_BITS: u8 = 137;
pub const BS_GET_UTF8: u8 = 138;
pub const BS_SKIP_UTF8: u8 = 139;
pub const BS_GET_UTF16: u8 = 140;
pub const BS_SKIP_UTF16: u8 = 141;
pub const BS_GET_UTF32: u8 = 142;
pub const BS_SKIP_UTF32: u8 = 143;
pub const BS_UTF8_SIZE: u8 = 144;
pub const BS_PUT_UTF8: u8 = 145;
pub const BS_UTF16_SIZE: u8 = 146;
pub const BS_PUT_UTF16: u8 = 147;
pub const BS_PUT_UTF32: u8 = 148;
pub const ON_LOAD: u8 = 149;
pub const RECV_MARK: u8 = 150;
pub const RECV_SET: u8 = 151;
pub const GC_BIF3: u8 = 152;
pub const LINE: u8 = 153;
pub const PUT_MAP_ASSOC: u8 = 154;
pub const PUT_MAP_EXACT: u8 = 155;
pub const IS_MAP: u8 = 156;
pub const HAS_MAP_FIELDS: u8 = 157;
pub const GET_MAP_ELEMENTS: u8 = 158;
pub const IS_TAGGED_TUPLE: u8 = 159;
pub const BUILD_STACKTRACE: u8 = 160;
pub const RAW_RAISE: u8 = 161;
pub const GET_HD: u8 = 162;
pub const GET_TL: u8 = 163;
pub const PUT_TUPLE2: u8 = 164;
pub const BS_GET_TAIL: u8 = 165;
pub const BS_START_MATCH3: u8 = 166;
pub const BS_GET_POSITION: u8 = 167;
pub const BS_SET_POSITION: u8 = 168;
pub const SWAP: u8 = 169;
pub const BS_START_MATCH4: u8 = 170;
pub const MAKE_FUN3: u8 = 171;
pub const INIT_YREGS: u8 = 172;
pub const RECV_MARKER_BIND: u8 = 173;
pub const RECV_MARKER_CLEAR: u8 = 174;
pub const RECV_MARKER_RESERVE: u8 = 175;
pub const RECV_MARKER_USE: u8 = 176;
pub const BS_CREATE_BIN: u8 = 177;
pub const CALL_FUN2: u8 = 178;
pub const NIF_START: u8 = 179;
pub const BADRECORD: u8 = 180;
pub const UPDATE_RECORD: u8 = 181;
pub const BS_MATCH: u8 = 182;
pub const EXECUTABLE_LINE: u8 = 183;
pub const DEBUG_LINE: u8 = 184;
