[package]
name = "flatipc"
version = "0.1.0"
edition = "2021"
authors = ["Sean Cross <sean@xobs.io>"]
description = "Zerocopy IPC between Redoubt clients and servers"
license = "BSD-2-Clause OR Apache-2.0 OR MIT"

[dependencies]
flatipc-derive = { path = "../flatipc-derive" }
redoubt-abi = { path = "../abi", optional = true }

[features]
redoubt = ["dep:redoubt-abi", "flatipc-derive/redoubt"]
default = ["redoubt"]