# The client of the `blkd` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/blkd.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Client.Blkd do
  @moduledoc """
  One function per message of the `blkd` protocol, on a connection to its server.
  A call returns `{:ok, reply}`, the reply's fields and its handles by name, or
  `{:error, name}`: the protocol's error, or why the call was not made. An error keeps
  none of the handles its reply brought. A send returns `:ok` or `{:error, name}`.
  Codec: `Redoubt.Wire.Proto.Blkd`; calls: `Redoubt.Wire.Client`.
  """
  alias Redoubt.Wire.Client, as: C
  alias Redoubt.Wire.Proto.Blkd, as: P

  @doc "Calls `info`, waiting at most `timeout` ms."
  def info(conn, timeout \\ C.timeout()) do
    C.call(conn, P, {:info, %{}}, [], timeout)
  end

  @doc "Calls `read`, waiting at most `timeout` ms."
  def read(conn, v_sector, v_count, timeout \\ C.timeout()) do
    C.call(conn, P, {:read, %{sector: v_sector, count: v_count}}, [], timeout)
  end

  @doc "Calls `write`, waiting at most `timeout` ms."
  def write(conn, v_sector, v_data, timeout \\ C.timeout()) do
    C.call(conn, P, {:write, %{sector: v_sector, data: v_data}}, [], timeout)
  end

  @doc "Calls `flush`, waiting at most `timeout` ms."
  def flush(conn, timeout \\ C.timeout()) do
    C.call(conn, P, {:flush, %{}}, [], timeout)
  end
end
