# The client of the `bootfs` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/bootfs.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Client.Bootfs do
  @moduledoc """
  One function per message of the `bootfs` protocol, on a connection to its server.
  A call returns `{:ok, reply}`, the reply's fields and its handles by name, or
  `{:error, name}`: the protocol's error, or why the call was not made. An error keeps
  none of the handles its reply brought. A send returns `:ok` or `{:error, name}`.
  Codec: `Redoubt.Wire.Proto.Bootfs`; calls: `Redoubt.Wire.Client`.
  """
  alias Redoubt.Wire.Client, as: C
  alias Redoubt.Wire.Proto.Bootfs, as: P

  @doc "Calls `add`, waiting at most `timeout` ms."
  def add(conn, v_name, v_offset, v_data, timeout \\ C.timeout()) do
    C.call(conn, P, {:add, %{name: v_name, offset: v_offset, data: v_data}}, [], timeout)
  end

  @doc "Calls `seal`, waiting at most `timeout` ms."
  def seal(conn, timeout \\ C.timeout()) do
    C.call(conn, P, {:seal, %{}}, [], timeout)
  end
end
