# The client of the `consrelay` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/consrelay.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Client.Consrelay do
  @moduledoc """
  One function per message of the `consrelay` protocol, on a connection to its server.
  A call returns `{:ok, reply}`, the reply's fields and its handles by name, or
  `{:error, name}`: the protocol's error, or why the call was not made. An error keeps
  none of the handles its reply brought. A send returns `:ok` or `{:error, name}`.
  Codec: `Redoubt.Wire.Proto.Consrelay`; calls: `Redoubt.Wire.Client`.
  """
  alias Redoubt.Wire.Client, as: C
  alias Redoubt.Wire.Proto.Consrelay, as: P

  @doc "Calls `attach`, waiting at most `timeout` ms."
  def attach(conn, v_note, h_console, timeout \\ C.timeout()) do
    C.call(conn, P, {:attach, %{note: v_note}}, [h_console], timeout)
  end

  @doc "Calls `detach`, waiting at most `timeout` ms."
  def detach(conn, v_note, timeout \\ C.timeout()) do
    C.call(conn, P, {:detach, %{note: v_note}}, [], timeout)
  end

  @doc "Sends `hello`, one way."
  def hello(conn, h_vm, h_control) do
    C.send(conn, P, {:hello, %{}}, [h_vm, h_control])
  end
end
