# The client of the `consol` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/consol.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Client.Consol do
  @moduledoc """
  One function per message of the `consol` protocol, on a connection to its server.
  A call returns `{:ok, reply}`, the reply's fields and its handles by name, or
  `{:error, name}`: the protocol's error, or why the call was not made. An error keeps
  none of the handles its reply brought. A send returns `:ok` or `{:error, name}`.
  Codec: `Redoubt.Wire.Proto.Consol`; calls: `Redoubt.Wire.Client`.
  """
  alias Redoubt.Wire.Client, as: C
  alias Redoubt.Wire.Proto.Consol, as: P

  @doc "Calls `size`, waiting at most `timeout` ms."
  def size(conn, timeout \\ C.timeout()) do
    C.call(conn, P, {:size, %{}}, [], timeout)
  end

  @doc "Calls `resize`, waiting at most `timeout` ms."
  def resize(conn, timeout \\ C.timeout()) do
    C.call(conn, P, {:resize, %{}}, [], timeout)
  end

  @doc "Sends `ended`, one way."
  def ended(conn) do
    C.send(conn, P, {:ended, %{}}, [])
  end
end
