# The client of the `example` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/example.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Client.Example do
  @moduledoc """
  One function per message of the `example` protocol, on a connection to its server.
  A call returns `{:ok, reply}`, the reply's fields and its handles by name, or
  `{:error, name}`: the protocol's error, or why the call was not made. An error keeps
  none of the handles its reply brought. A send returns `:ok` or `{:error, name}`.
  Codec: `Redoubt.Wire.Proto.Example`; calls: `Redoubt.Wire.Client`.
  """
  alias Redoubt.Wire.Client, as: C
  alias Redoubt.Wire.Proto.Example, as: P

  @doc "Calls `ping`, waiting at most `timeout` ms."
  def ping(conn, timeout \\ C.timeout()) do
    C.call(conn, P, {:ping, %{}}, [], timeout)
  end

  @doc "Calls `pong`, waiting at most `timeout` ms."
  def pong(conn, v_seq, v_flags, timeout \\ C.timeout()) do
    C.call(conn, P, {:pong, %{seq: v_seq, flags: v_flags}}, [], timeout)
  end

  @doc "Calls `small`, waiting at most `timeout` ms."
  def small(conn, v_a, v_b, timeout \\ C.timeout()) do
    C.call(conn, P, {:small, %{a: v_a, b: v_b}}, [], timeout)
  end

  @doc "Calls `wide`, waiting at most `timeout` ms."
  def wide(conn, v_a, v_b, v_c, timeout \\ C.timeout()) do
    C.call(conn, P, {:wide, %{a: v_a, b: v_b, c: v_c}}, [], timeout)
  end

  @doc "Calls `named`, waiting at most `timeout` ms."
  def named(conn, v_id, v_name, timeout \\ C.timeout()) do
    C.call(conn, P, {:named, %{id: v_id, name: v_name}}, [], timeout)
  end

  @doc "Calls `blob`, waiting at most `timeout` ms."
  def blob(conn, v_offset, v_data, v_label, timeout \\ C.timeout()) do
    C.call(conn, P, {:blob, %{offset: v_offset, data: v_data, label: v_label}}, [], timeout)
  end

  @doc "Calls `grant`, waiting at most `timeout` ms."
  def grant(conn, v_pages, h_range, h_reply, timeout \\ C.timeout()) do
    C.call(conn, P, {:grant, %{pages: v_pages}}, [h_range, h_reply], timeout)
  end

  @doc "Calls `read`, waiting at most `timeout` ms."
  def read(conn, v_offset, v_count, timeout \\ C.timeout()) do
    C.call(conn, P, {:read, %{offset: v_offset, count: v_count}}, [], timeout)
  end

  @doc "Calls `last`, waiting at most `timeout` ms."
  def last(conn, v_note, h_key, timeout \\ C.timeout()) do
    C.call(conn, P, {:last, %{note: v_note}}, [h_key], timeout)
  end
end
