# The client of the `ipd` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/ipd.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Client.Ipd do
  @moduledoc """
  One function per message of the `ipd` protocol, on a connection to its server.
  A call returns `{:ok, reply}`, the reply's fields and its handles by name, or
  `{:error, name}`: the protocol's error, or why the call was not made. An error keeps
  none of the handles its reply brought. A send returns `:ok` or `{:error, name}`.
  Codec: `Redoubt.Wire.Proto.Ipd`; calls: `Redoubt.Wire.Client`.
  """
  alias Redoubt.Wire.Client, as: C
  alias Redoubt.Wire.Proto.Ipd, as: P

  @doc "Calls `grant`, waiting at most `timeout` ms."
  def grant(conn, v_scope, timeout \\ C.timeout()) do
    C.call(conn, P, {:grant, %{scope: v_scope}}, [], timeout)
  end

  @doc "Sends `frame`, one way."
  def frame(conn, v_frame) do
    C.send(conn, P, {:frame, %{frame: v_frame}}, [])
  end
end
