# The client of the `keyd` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/keyd.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Client.Keyd do
  @moduledoc """
  One function per message of the `keyd` protocol, on a connection to its server.
  A call returns `{:ok, reply}`, the reply's fields and its handles by name, or
  `{:error, name}`: the protocol's error, or why the call was not made. An error keeps
  none of the handles its reply brought. A send returns `:ok` or `{:error, name}`.
  Codec: `Redoubt.Wire.Proto.Keyd`; calls: `Redoubt.Wire.Client`.
  """
  alias Redoubt.Wire.Client, as: C
  alias Redoubt.Wire.Proto.Keyd, as: P

  @doc "Calls `sign_ssh_exchange`, waiting at most `timeout` ms."
  def sign_ssh_exchange(conn, v_v_c, v_v_s, v_i_c, v_i_s, v_q_c, v_q_s, v_k, timeout \\ C.timeout()) do
    C.call(conn, P, {:sign_ssh_exchange, %{v_c: v_v_c, v_s: v_v_s, i_c: v_i_c, i_s: v_i_s, q_c: v_q_c, q_s: v_q_s, k: v_k}}, [], timeout)
  end

  @doc "Calls `sign_record`, waiting at most `timeout` ms."
  def sign_record(conn, v_record, timeout \\ C.timeout()) do
    C.call(conn, P, {:sign_record, %{record: v_record}}, [], timeout)
  end

  @doc "Calls `public_key`, waiting at most `timeout` ms."
  def public_key(conn, timeout \\ C.timeout()) do
    C.call(conn, P, {:public_key, %{}}, [], timeout)
  end

  @doc "Calls `holds`, waiting at most `timeout` ms."
  def holds(conn, v_key, timeout \\ C.timeout()) do
    C.call(conn, P, {:holds, %{key: v_key}}, [], timeout)
  end

  @doc "Calls `grant`, waiting at most `timeout` ms."
  def grant(conn, timeout \\ C.timeout()) do
    C.call(conn, P, {:grant, %{}}, [], timeout)
  end

  @doc "Calls `release`, waiting at most `timeout` ms."
  def release(conn, v_id, timeout \\ C.timeout()) do
    C.call(conn, P, {:release, %{id: v_id}}, [], timeout)
  end
end
