# The client of the `littlefsd` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/littlefsd.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Client.Littlefsd do
  @moduledoc """
  One function per message of the `littlefsd` protocol, on a connection to its server.
  A call returns `{:ok, reply}`, the reply's fields and its handles by name, or
  `{:error, name}`: the protocol's error, or why the call was not made. An error keeps
  none of the handles its reply brought. A send returns `:ok` or `{:error, name}`.
  Codec: `Redoubt.Wire.Proto.Littlefsd`; calls: `Redoubt.Wire.Client`.
  """
  alias Redoubt.Wire.Client, as: C
  alias Redoubt.Wire.Proto.Littlefsd, as: P

  @doc "Calls `rename`, waiting at most `timeout` ms."
  def rename(conn, v_old_dir, v_old_name, v_new_dir, v_new_name, timeout \\ C.timeout()) do
    C.call(conn, P, {:rename, %{old_dir: v_old_dir, old_name: v_old_name, new_dir: v_new_dir, new_name: v_new_name}}, [], timeout)
  end

  @doc "Calls `copy_file`, waiting at most `timeout` ms."
  def copy_file(conn, v_src_fid, v_dst_dir, v_dst_name, timeout \\ C.timeout()) do
    C.call(conn, P, {:copy_file, %{src_fid: v_src_fid, dst_dir: v_dst_dir, dst_name: v_dst_name}}, [], timeout)
  end

  @doc "Calls `set_attr`, waiting at most `timeout` ms."
  def set_attr(conn, v_fid, v_attr, v_value, timeout \\ C.timeout()) do
    C.call(conn, P, {:set_attr, %{fid: v_fid, attr: v_attr, value: v_value}}, [], timeout)
  end

  @doc "Calls `get_attr`, waiting at most `timeout` ms."
  def get_attr(conn, v_fid, v_attr, timeout \\ C.timeout()) do
    C.call(conn, P, {:get_attr, %{fid: v_fid, attr: v_attr}}, [], timeout)
  end
end
