# The client of the `net_ctl` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/net_ctl.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Client.NetCtl do
  @moduledoc """
  One function per message of the `net_ctl` protocol, on a connection to its server.
  A call returns `{:ok, reply}`, the reply's fields and its handles by name, or
  `{:error, name}`: the protocol's error, or why the call was not made. An error keeps
  none of the handles its reply brought. A send returns `:ok` or `{:error, name}`.
  Codec: `Redoubt.Wire.Proto.NetCtl`; calls: `Redoubt.Wire.Client`.
  """
  alias Redoubt.Wire.Client, as: C
  alias Redoubt.Wire.Proto.NetCtl, as: P

  @doc "Calls `connect`, waiting at most `timeout` ms."
  def connect(conn, v_addr, v_port, timeout \\ C.timeout()) do
    C.call(conn, P, {:connect, %{addr: v_addr, port: v_port}}, [], timeout)
  end

  @doc "Calls `listen`, waiting at most `timeout` ms."
  def listen(conn, v_port, v_backlog, timeout \\ C.timeout()) do
    C.call(conn, P, {:listen, %{port: v_port, backlog: v_backlog}}, [], timeout)
  end

  @doc "Calls `close`, waiting at most `timeout` ms."
  def close(conn, timeout \\ C.timeout()) do
    C.call(conn, P, {:close, %{}}, [], timeout)
  end

  @doc "Calls `abort`, waiting at most `timeout` ms."
  def abort(conn, timeout \\ C.timeout()) do
    C.call(conn, P, {:abort, %{}}, [], timeout)
  end
end
