# The client of the `netif` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/netif.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Client.Netif do
  @moduledoc """
  One function per message of the `netif` protocol, on a connection to its server.
  A call returns `{:ok, reply}`, the reply's fields and its handles by name, or
  `{:error, name}`: the protocol's error, or why the call was not made. An error keeps
  none of the handles its reply brought. A send returns `:ok` or `{:error, name}`.
  Codec: `Redoubt.Wire.Proto.Netif`; calls: `Redoubt.Wire.Client`.
  """
  alias Redoubt.Wire.Client, as: C
  alias Redoubt.Wire.Proto.Netif, as: P

  @doc "Calls `info`, waiting at most `timeout` ms."
  def info(conn, timeout \\ C.timeout()) do
    C.call(conn, P, {:info, %{}}, [], timeout)
  end

  @doc "Calls `transmit`, waiting at most `timeout` ms."
  def transmit(conn, v_frame, timeout \\ C.timeout()) do
    C.call(conn, P, {:transmit, %{frame: v_frame}}, [], timeout)
  end
end
