# The client of the `ninep_common` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/ninep_common.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Client.NinepCommon do
  @moduledoc """
  One function per message of the `ninep_common` protocol, on a connection to its server.
  A call returns `{:ok, reply}`, the reply's fields and its handles by name, or
  `{:error, name}`: the protocol's error, or why the call was not made. An error keeps
  none of the handles its reply brought. A send returns `:ok` or `{:error, name}`.
  Codec: `Redoubt.Wire.Proto.NinepCommon`; calls: `Redoubt.Wire.Client`.
  """
  alias Redoubt.Wire.Client, as: C
  alias Redoubt.Wire.Proto.NinepCommon, as: P

  @doc "Calls `new_connection`, waiting at most `timeout` ms."
  def new_connection(conn, v_root, v_quota, timeout \\ C.timeout()) do
    C.call(conn, P, {:new_connection, %{root: v_root, quota: v_quota}}, [], timeout)
  end

  @doc "Calls `disconnect`, waiting at most `timeout` ms."
  def disconnect(conn, v_id, timeout \\ C.timeout()) do
    C.call(conn, P, {:disconnect, %{id: v_id}}, [], timeout)
  end
end
