# The client of the `startup` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/startup.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Client.Startup do
  @moduledoc """
  One function per message of the `startup` protocol, on a connection to its server.
  A call returns `{:ok, reply}`, the reply's fields and its handles by name, or
  `{:error, name}`: the protocol's error, or why the call was not made. An error keeps
  none of the handles its reply brought. A send returns `:ok` or `{:error, name}`.
  Codec: `Redoubt.Wire.Proto.Startup`; calls: `Redoubt.Wire.Client`.
  """
  alias Redoubt.Wire.Client, as: C
  alias Redoubt.Wire.Proto.Startup, as: P

  @doc "Calls `startup`, waiting at most `timeout` ms."
  def startup(conn, v_version, v_handle_count, v_namespace, v_handles, v_argv, v_image_addr, v_image_len, v_heap_pages, v_tag, timeout \\ C.timeout()) do
    C.call(conn, P, {:startup, %{version: v_version, handle_count: v_handle_count, namespace: v_namespace, handles: v_handles, argv: v_argv, image_addr: v_image_addr, image_len: v_image_len, heap_pages: v_heap_pages, tag: v_tag}}, [], timeout)
  end
end
