# The client of the `steward` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/steward.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Client.Steward do
  @moduledoc """
  One function per message of the `steward` protocol, on a connection to its server.
  A call returns `{:ok, reply}`, the reply's fields and its handles by name, or
  `{:error, name}`: the protocol's error, or why the call was not made. An error keeps
  none of the handles its reply brought. A send returns `:ok` or `{:error, name}`.
  Codec: `Redoubt.Wire.Proto.Steward`; calls: `Redoubt.Wire.Client`.
  """
  alias Redoubt.Wire.Client, as: C
  alias Redoubt.Wire.Proto.Steward, as: P

  @doc "Calls `login`, waiting at most `timeout` ms."
  def login(conn, v_principal, v_label, v_key, h_console, timeout \\ C.timeout()) do
    C.call(conn, P, {:login, %{principal: v_principal, label: v_label, key: v_key}}, [h_console], timeout)
  end

  @doc "Calls `channel_closed`, waiting at most `timeout` ms."
  def channel_closed(conn, v_session, timeout \\ C.timeout()) do
    C.call(conn, P, {:channel_closed, %{session: v_session}}, [], timeout)
  end

  @doc "Calls `approval_opened`, waiting at most `timeout` ms."
  def approval_opened(conn, v_principal, v_key, timeout \\ C.timeout()) do
    C.call(conn, P, {:approval_opened, %{principal: v_principal, key: v_key}}, [], timeout)
  end

  @doc "Calls `approval_closed`, waiting at most `timeout` ms."
  def approval_closed(conn, v_channel, timeout \\ C.timeout()) do
    C.call(conn, P, {:approval_closed, %{channel: v_channel}}, [], timeout)
  end

  @doc "Calls `pending`, waiting at most `timeout` ms."
  def pending(conn, v_channel, timeout \\ C.timeout()) do
    C.call(conn, P, {:pending, %{channel: v_channel}}, [], timeout)
  end

  @doc "Calls `approve`, waiting at most `timeout` ms."
  def approve(conn, v_channel, v_request, v_hash, timeout \\ C.timeout()) do
    C.call(conn, P, {:approve, %{channel: v_channel, request: v_request, hash: v_hash}}, [], timeout)
  end

  @doc "Calls `deny`, waiting at most `timeout` ms."
  def deny(conn, v_channel, v_request, timeout \\ C.timeout()) do
    C.call(conn, P, {:deny, %{channel: v_channel, request: v_request}}, [], timeout)
  end

  @doc "Calls `blame`, waiting at most `timeout` ms."
  def blame(conn, v_account, v_labels, v_server, timeout \\ C.timeout()) do
    C.call(conn, P, {:blame, %{account: v_account, labels: v_labels, server: v_server}}, [], timeout)
  end

  @doc "Calls `submit`, waiting at most `timeout` ms."
  def submit(conn, v_kind, v_labels, v_lease, v_item, v_source, v_what, v_reason, timeout \\ C.timeout()) do
    C.call(conn, P, {:submit, %{kind: v_kind, labels: v_labels, lease: v_lease, item: v_item, source: v_source, what: v_what, reason: v_reason}}, [], timeout)
  end

  @doc "Calls `start_agent`, waiting at most `timeout` ms."
  def start_agent(conn, v_lease, timeout \\ C.timeout()) do
    C.call(conn, P, {:start_agent, %{lease: v_lease}}, [], timeout)
  end

  @doc "Calls `end_lease`, waiting at most `timeout` ms."
  def end_lease(conn, v_lease, timeout \\ C.timeout()) do
    C.call(conn, P, {:end_lease, %{lease: v_lease}}, [], timeout)
  end

  @doc "Calls `end_session`, waiting at most `timeout` ms."
  def end_session(conn, timeout \\ C.timeout()) do
    C.call(conn, P, {:end_session, %{}}, [], timeout)
  end

  @doc "Calls `watch`, waiting at most `timeout` ms."
  def watch(conn, timeout \\ C.timeout()) do
    C.call(conn, P, {:watch, %{}}, [], timeout)
  end
end
