//! Typed messages of the `consrelay` protocol.
//!
//! Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/consrelay.md`.
//! Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.

use crate::codec::{Error, Reader, Writer};
use crate::typed::{self, Layout, Words};

/// `attach`: opcode 24, buffer; reply [`AttachReply`].
///
/// Handle slots: `console` (slot 0, endpoint).
/// Kinds are documentation, checked by use: a handle of the wrong kind gets `WrongObject`
/// on first use.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Attach<'a> {
    pub note: &'a str,
}

/// The reply to [`Attach`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AttachReply {}

/// `detach`: opcode 25, buffer; reply [`DetachReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Detach<'a> {
    pub note: &'a str,
}

/// The reply to [`Detach`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DetachReply {}

/// `hello`: opcode 26, inline, a `send`: its buffer is a transfer and there is no reply.
///
/// Handle slots: `vm` (slot 0, endpoint), `control` (slot 1, endpoint).
/// Kinds are documentation, checked by use: a handle of the wrong kind gets `WrongObject`
/// on first use.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Hello {}

/// The reply to [`Hello`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct HelloReply {}

/// Requests by opcode.
const REQUESTS: &[Layout] = &[
    Layout { opcode: 24, inline: false, handles: 1 },
    Layout { opcode: 25, inline: false, handles: 0 },
    Layout { opcode: 26, inline: true, handles: 2 },
];

/// Every request of the protocol.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Message<'a> {
    Attach(Attach<'a>),
    Detach(Detach<'a>),
    Hello(Hello),
}

impl<'a> Message<'a> {
    /// The handles it carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Message::Attach(_) => &["console"],
            Message::Detach(_) => &[],
            Message::Hello(_) => &["vm", "control"],
        }
    }

    /// The opcode in word 0.
    fn opcode(&self) -> u32 {
        match self {
            Message::Attach(_) => 24,
            Message::Detach(_) => 25,
            Message::Hello(_) => 26,
        }
    }

    fn write(&self, w: &mut Writer<'_>) -> Result<(), Error> {
        match self {
            Message::Attach(m) => w.string(m.note),
            Message::Detach(m) => w.string(m.note),
            Message::Hello(_) => Ok(()),
        }
    }

    fn read_inline(opcode: u32, _r: &mut Reader<'_>) -> Result<Self, Error> {
        Ok(match opcode {
            26 => Message::Hello(Hello {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    fn read_buffer(opcode: u32, r: &mut Reader<'a>) -> Result<Self, Error> {
        Ok(match opcode {
            24 => Message::Attach(Attach { note: r.string()? }),
            25 => Message::Detach(Detach { note: r.string()? }),
            26 => Message::Hello(Hello {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    /// Decodes a received request: its words, the buffer that came with it (empty if
    /// none), and how many handles it carried.
    pub fn decode(words: &Words, buf: &'a [u8], handles: usize) -> Result<Self, Error> {
        let layout = typed::layout(REQUESTS, typed::opcode(words)?)?;
        typed::decode(layout, words, buf, handles, Self::read_inline, Self::read_buffer)
    }

    /// Encodes the request: returns its words, and writes the fields into `buf` if it is
    /// a buffer message (the buffer's length is then in word 1).
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        let opcode = self.opcode();
        typed::encode(typed::layout(REQUESTS, opcode)?, opcode, buf, |w| self.write(w))
    }

    /// Decodes a request written into a 9P file: all of `bytes` is one operation.
    pub fn decode_file(bytes: &'a [u8]) -> Result<Self, Error> {
        typed::decode_file(REQUESTS, bytes, Self::read_buffer)
    }

    /// Writes the request in the file framing into the front of `out`; returns its length.
    pub fn encode_file(&self, out: &mut [u8]) -> Result<usize, Error> {
        typed::encode_file(typed::layout(REQUESTS, self.opcode())?, out, |w| self.write(w))
    }

    /// Whether this message is sent one-way (`send`, its buffer a transfer) rather than
    /// called: a receiver must not reply to it, and a sender must not wait for a reply.
    pub fn is_send(&self) -> bool {
        matches!(self, Message::Hello(_))
    }
}

/// Replies, by the opcode of their request.
const REPLIES: &[Layout] = &[
    Layout { opcode: 24, inline: false, handles: 0 },
    Layout { opcode: 25, inline: false, handles: 0 },
    Layout { opcode: 26, inline: true, handles: 0 },
];

/// Every successful reply of the protocol, named after its request.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reply {
    Attach(AttachReply),
    Detach(DetachReply),
    Hello(HelloReply),
}

impl<'a> Reply {
    /// The handles it carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Reply::Attach(_) => &[],
            Reply::Detach(_) => &[],
            Reply::Hello(_) => &[],
        }
    }

    /// The opcode of the request this replies to.
    fn opcode(&self) -> u32 {
        match self {
            Reply::Attach(_) => 24,
            Reply::Detach(_) => 25,
            Reply::Hello(_) => 26,
        }
    }

    fn write(&self, _w: &mut Writer<'_>) -> Result<(), Error> {
        match self {
            Reply::Attach(_) => Ok(()),
            Reply::Detach(_) => Ok(()),
            Reply::Hello(_) => Ok(()),
        }
    }

    fn read_inline(opcode: u32, _r: &mut Reader<'_>) -> Result<Self, Error> {
        Ok(match opcode {
            26 => Reply::Hello(HelloReply {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    fn read_buffer(opcode: u32, _r: &mut Reader<'a>) -> Result<Self, Error> {
        Ok(match opcode {
            24 => Reply::Attach(AttachReply {}),
            25 => Reply::Detach(DetachReply {}),
            26 => Reply::Hello(HelloReply {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    /// Decodes the reply to the request with `opcode` (the caller knows what it sent):
    /// `Ok(Ok(reply))`, `Ok(Err(code))`
    /// for an error reply, or `Err` if the reply is malformed.
    pub fn decode(opcode: u32, words: &Words, buf: &'a [u8], handles: usize) -> Result<Result<Self, ErrorCode>, Error> {
        let layout = typed::layout(REPLIES, opcode)?;
        if let Some(code) = typed::reply_status(words, handles)? {
            return ErrorCode::from_code(code).map(Err).ok_or(Error::BadStatus);
        }
        typed::decode(layout, words, buf, handles, Self::read_inline, Self::read_buffer).map(Ok)
    }

    /// Encodes the reply (status 0): returns its words, and writes the fields into `buf`
    /// (the caller's lend) if it is a buffer message.
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        typed::encode(typed::layout(REPLIES, self.opcode())?, 0, buf, |w| self.write(w))
    }
}

/// The protocol's error codes: word 0 of an error reply. Code 1, `Malformed`, is every
/// protocol's: a request that does not decode (servers/wire.md, "The message convention").
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ErrorCode {
    Malformed,
    Failed,
}

impl ErrorCode {
    pub fn code(self) -> u32 {
        match self {
            ErrorCode::Malformed => 1,
            ErrorCode::Failed => 2,
        }
    }

    pub fn from_code(code: u32) -> Option<Self> {
        match code {
            1 => Some(ErrorCode::Malformed),
            2 => Some(ErrorCode::Failed),
            _ => None,
        }
    }

    /// The words of the error reply (no buffer, no handles).
    pub fn encode(self) -> Words {
        typed::error_reply(self.code())
    }
}

typed::protocol!('a, Message<'a>, Reply);
