//! Typed messages of the `example` protocol.
//!
//! Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/example.md`.
//! Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.

use crate::codec::{Error, Reader, Writer};
use crate::typed::{self, Layout, Words};

/// `ping`: opcode 1, inline; reply [`PingReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Ping {}

/// The reply to [`Ping`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PingReply {}

/// `pong`: opcode 2, inline; reply [`PongReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Pong {
    pub seq: u64,
    pub flags: u32,
}

/// The reply to [`Pong`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PongReply {}

/// `small`: opcode 3, inline; reply [`SmallReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Small {
    pub a: u8,
    pub b: u16,
}

/// The reply to [`Small`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SmallReply {
    pub c: u32,
}

/// `wide`: opcode 4, buffer; reply [`WideReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Wide {
    pub a: u64,
    pub b: u32,
    pub c: u8,
}

/// The reply to [`Wide`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WideReply {}

/// `named`: opcode 5, buffer; reply [`NamedReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Named<'a> {
    pub id: u32,
    pub name: &'a str,
}

/// The reply to [`Named`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct NamedReply {
    pub id: u32,
}

/// `blob`: opcode 6, buffer; reply [`BlobReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Blob<'a> {
    pub offset: u64,
    pub data: &'a [u8],
    pub label: &'a str,
}

/// The reply to [`Blob`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BlobReply {}

/// `grant`: opcode 7, inline; reply [`GrantReply`].
///
/// Handle slots: `range` (slot 0, endpoint), `reply` (slot 1, endpoint).
/// Kinds are documentation, checked by use: a handle of the wrong kind gets `WrongObject`
/// on first use.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Grant {
    pub pages: u32,
}

/// The reply to [`Grant`].
///
/// Handle slots: `key` (slot 0, budget).
/// Kinds are documentation, checked by use: a handle of the wrong kind gets `WrongObject`
/// on first use.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GrantReply {}

/// `read`: opcode 8, buffer; reply [`ReadReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Read {
    pub offset: u64,
    pub count: u32,
}

/// The reply to [`Read`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReadReply<'a> {
    pub data: &'a [u8],
}

/// `last`: opcode 4294967295, buffer; reply [`LastReply`].
///
/// Handle slots: `key` (slot 0, process).
/// Kinds are documentation, checked by use: a handle of the wrong kind gets `WrongObject`
/// on first use.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Last<'a> {
    pub note: &'a str,
}

/// The reply to [`Last`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LastReply {
    pub n: u64,
    pub m: u32,
}

/// Requests by opcode.
const REQUESTS: &[Layout] = &[
    Layout { opcode: 1, inline: true, handles: 0 },
    Layout { opcode: 2, inline: true, handles: 0 },
    Layout { opcode: 3, inline: true, handles: 0 },
    Layout { opcode: 4, inline: false, handles: 0 },
    Layout { opcode: 5, inline: false, handles: 0 },
    Layout { opcode: 6, inline: false, handles: 0 },
    Layout { opcode: 7, inline: true, handles: 2 },
    Layout { opcode: 8, inline: false, handles: 0 },
    Layout { opcode: 4294967295, inline: false, handles: 1 },
];

/// Every request of the protocol.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Message<'a> {
    Ping(Ping),
    Pong(Pong),
    Small(Small),
    Wide(Wide),
    Named(Named<'a>),
    Blob(Blob<'a>),
    Grant(Grant),
    Read(Read),
    Last(Last<'a>),
}

impl<'a> Message<'a> {
    /// The handles it carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Message::Ping(_) => &[],
            Message::Pong(_) => &[],
            Message::Small(_) => &[],
            Message::Wide(_) => &[],
            Message::Named(_) => &[],
            Message::Blob(_) => &[],
            Message::Grant(_) => &["range", "reply"],
            Message::Read(_) => &[],
            Message::Last(_) => &["key"],
        }
    }

    /// The opcode in word 0.
    fn opcode(&self) -> u32 {
        match self {
            Message::Ping(_) => 1,
            Message::Pong(_) => 2,
            Message::Small(_) => 3,
            Message::Wide(_) => 4,
            Message::Named(_) => 5,
            Message::Blob(_) => 6,
            Message::Grant(_) => 7,
            Message::Read(_) => 8,
            Message::Last(_) => 4294967295,
        }
    }

    fn write(&self, w: &mut Writer<'_>) -> Result<(), Error> {
        match self {
            Message::Ping(_) => Ok(()),
            Message::Pong(m) => {
                w.u64(m.seq)?;
                w.u32(m.flags)
            }
            Message::Small(m) => {
                w.u8(m.a)?;
                w.u16(m.b)
            }
            Message::Wide(m) => {
                w.u64(m.a)?;
                w.u32(m.b)?;
                w.u8(m.c)
            }
            Message::Named(m) => {
                w.u32(m.id)?;
                w.string(m.name)
            }
            Message::Blob(m) => {
                w.u64(m.offset)?;
                w.bytes(m.data)?;
                w.string(m.label)
            }
            Message::Grant(m) => w.u32(m.pages),
            Message::Read(m) => {
                w.u64(m.offset)?;
                w.u32(m.count)
            }
            Message::Last(m) => w.string(m.note),
        }
    }

    fn read_inline(opcode: u32, r: &mut Reader<'_>) -> Result<Self, Error> {
        Ok(match opcode {
            1 => Message::Ping(Ping {}),
            2 => Message::Pong(Pong { seq: r.u64()?, flags: r.u32()? }),
            3 => Message::Small(Small { a: r.u8()?, b: r.u16()? }),
            7 => Message::Grant(Grant { pages: r.u32()? }),
            _ => return Err(Error::BadOpcode),
        })
    }

    fn read_buffer(opcode: u32, r: &mut Reader<'a>) -> Result<Self, Error> {
        Ok(match opcode {
            1 => Message::Ping(Ping {}),
            2 => Message::Pong(Pong { seq: r.u64()?, flags: r.u32()? }),
            3 => Message::Small(Small { a: r.u8()?, b: r.u16()? }),
            4 => Message::Wide(Wide { a: r.u64()?, b: r.u32()?, c: r.u8()? }),
            5 => Message::Named(Named { id: r.u32()?, name: r.string()? }),
            6 => Message::Blob(Blob { offset: r.u64()?, data: r.bytes()?, label: r.string()? }),
            7 => Message::Grant(Grant { pages: r.u32()? }),
            8 => Message::Read(Read { offset: r.u64()?, count: r.u32()? }),
            4294967295 => Message::Last(Last { note: r.string()? }),
            _ => return Err(Error::BadOpcode),
        })
    }

    /// Decodes a received request: its words, the buffer that came with it (empty if
    /// none), and how many handles it carried.
    pub fn decode(words: &Words, buf: &'a [u8], handles: usize) -> Result<Self, Error> {
        let layout = typed::layout(REQUESTS, typed::opcode(words)?)?;
        typed::decode(layout, words, buf, handles, Self::read_inline, Self::read_buffer)
    }

    /// Encodes the request: returns its words, and writes the fields into `buf` if it is
    /// a buffer message (the buffer's length is then in word 1).
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        let opcode = self.opcode();
        typed::encode(typed::layout(REQUESTS, opcode)?, opcode, buf, |w| self.write(w))
    }

    /// Decodes a request written into a 9P file: all of `bytes` is one operation.
    pub fn decode_file(bytes: &'a [u8]) -> Result<Self, Error> {
        typed::decode_file(REQUESTS, bytes, Self::read_buffer)
    }

    /// Writes the request in the file framing into the front of `out`; returns its length.
    pub fn encode_file(&self, out: &mut [u8]) -> Result<usize, Error> {
        typed::encode_file(typed::layout(REQUESTS, self.opcode())?, out, |w| self.write(w))
    }
}

/// Replies, by the opcode of their request.
const REPLIES: &[Layout] = &[
    Layout { opcode: 1, inline: true, handles: 0 },
    Layout { opcode: 2, inline: true, handles: 0 },
    Layout { opcode: 3, inline: true, handles: 0 },
    Layout { opcode: 4, inline: false, handles: 0 },
    Layout { opcode: 5, inline: false, handles: 0 },
    Layout { opcode: 6, inline: false, handles: 0 },
    Layout { opcode: 7, inline: true, handles: 1 },
    Layout { opcode: 8, inline: false, handles: 0 },
    Layout { opcode: 4294967295, inline: false, handles: 0 },
];

/// Every successful reply of the protocol, named after its request.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reply<'a> {
    Ping(PingReply),
    Pong(PongReply),
    Small(SmallReply),
    Wide(WideReply),
    Named(NamedReply),
    Blob(BlobReply),
    Grant(GrantReply),
    Read(ReadReply<'a>),
    Last(LastReply),
}

impl<'a> Reply<'a> {
    /// The handles it carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Reply::Ping(_) => &[],
            Reply::Pong(_) => &[],
            Reply::Small(_) => &[],
            Reply::Wide(_) => &[],
            Reply::Named(_) => &[],
            Reply::Blob(_) => &[],
            Reply::Grant(_) => &["key"],
            Reply::Read(_) => &[],
            Reply::Last(_) => &[],
        }
    }

    /// The opcode of the request this replies to.
    fn opcode(&self) -> u32 {
        match self {
            Reply::Ping(_) => 1,
            Reply::Pong(_) => 2,
            Reply::Small(_) => 3,
            Reply::Wide(_) => 4,
            Reply::Named(_) => 5,
            Reply::Blob(_) => 6,
            Reply::Grant(_) => 7,
            Reply::Read(_) => 8,
            Reply::Last(_) => 4294967295,
        }
    }

    fn write(&self, w: &mut Writer<'_>) -> Result<(), Error> {
        match self {
            Reply::Ping(_) => Ok(()),
            Reply::Pong(_) => Ok(()),
            Reply::Small(m) => w.u32(m.c),
            Reply::Wide(_) => Ok(()),
            Reply::Named(m) => w.u32(m.id),
            Reply::Blob(_) => Ok(()),
            Reply::Grant(_) => Ok(()),
            Reply::Read(m) => w.bytes(m.data),
            Reply::Last(m) => {
                w.u64(m.n)?;
                w.u32(m.m)
            }
        }
    }

    fn read_inline(opcode: u32, r: &mut Reader<'_>) -> Result<Self, Error> {
        Ok(match opcode {
            1 => Reply::Ping(PingReply {}),
            2 => Reply::Pong(PongReply {}),
            3 => Reply::Small(SmallReply { c: r.u32()? }),
            7 => Reply::Grant(GrantReply {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    fn read_buffer(opcode: u32, r: &mut Reader<'a>) -> Result<Self, Error> {
        Ok(match opcode {
            1 => Reply::Ping(PingReply {}),
            2 => Reply::Pong(PongReply {}),
            3 => Reply::Small(SmallReply { c: r.u32()? }),
            4 => Reply::Wide(WideReply {}),
            5 => Reply::Named(NamedReply { id: r.u32()? }),
            6 => Reply::Blob(BlobReply {}),
            7 => Reply::Grant(GrantReply {}),
            8 => Reply::Read(ReadReply { data: r.bytes()? }),
            4294967295 => Reply::Last(LastReply { n: r.u64()?, m: r.u32()? }),
            _ => return Err(Error::BadOpcode),
        })
    }

    /// Decodes the reply to the request with `opcode` (the caller knows what it sent):
    /// `Ok(Ok(reply))`, `Ok(Err(code))`
    /// for an error reply, or `Err` if the reply is malformed.
    pub fn decode(opcode: u32, words: &Words, buf: &'a [u8], handles: usize) -> Result<Result<Self, ErrorCode>, Error> {
        let layout = typed::layout(REPLIES, opcode)?;
        if let Some(code) = typed::reply_status(words, handles)? {
            return ErrorCode::from_code(code).map(Err).ok_or(Error::BadStatus);
        }
        typed::decode(layout, words, buf, handles, Self::read_inline, Self::read_buffer).map(Ok)
    }

    /// Encodes the reply (status 0): returns its words, and writes the fields into `buf`
    /// (the caller's lend) if it is a buffer message.
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        typed::encode(typed::layout(REPLIES, self.opcode())?, 0, buf, |w| self.write(w))
    }
}

/// The protocol's error codes: word 0 of an error reply. Code 1, `Malformed`, is every
/// protocol's: a request that does not decode (servers/wire.md, "The message convention").
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ErrorCode {
    Malformed,
    NotFound,
    Denied,
    LastError,
}

impl ErrorCode {
    pub fn code(self) -> u32 {
        match self {
            ErrorCode::Malformed => 1,
            ErrorCode::NotFound => 2,
            ErrorCode::Denied => 3,
            ErrorCode::LastError => 4294967295,
        }
    }

    pub fn from_code(code: u32) -> Option<Self> {
        match code {
            1 => Some(ErrorCode::Malformed),
            2 => Some(ErrorCode::NotFound),
            3 => Some(ErrorCode::Denied),
            4294967295 => Some(ErrorCode::LastError),
            _ => None,
        }
    }

    /// The words of the error reply (no buffer, no handles).
    pub fn encode(self) -> Words {
        typed::error_reply(self.code())
    }
}
