//! Typed messages of the `fsd` protocol.
//!
//! Generated by `redoubt-wire-gen` from the tables in `docs/NAMESPACES.md`.
//! Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.

use crate::codec::{Error, Reader, Writer};
use crate::typed::{self, Layout, Words};

/// `rename`: opcode 16, buffer; reply [`RenameReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Rename<'a> {
    pub old_dir: u32,
    pub old_name: &'a str,
    pub new_dir: u32,
    pub new_name: &'a str,
}

/// The reply to [`Rename`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RenameReply {}

/// `copy_file`: opcode 17, buffer; reply [`CopyFileReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CopyFile<'a> {
    pub src_fid: u32,
    pub dst_dir: u32,
    pub dst_name: &'a str,
}

/// The reply to [`CopyFile`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CopyFileReply {
    pub count: u64,
}

/// `set_attr`: opcode 18, buffer; reply [`SetAttrReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SetAttr<'a> {
    pub fid: u32,
    pub attr: u8,
    pub value: &'a [u8],
}

/// The reply to [`SetAttr`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SetAttrReply {}

/// `get_attr`: opcode 19, buffer; reply [`GetAttrReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GetAttr {
    pub fid: u32,
    pub attr: u8,
}

/// The reply to [`GetAttr`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GetAttrReply<'a> {
    pub value: &'a [u8],
}

/// Requests by opcode.
const REQUESTS: &[Layout] = &[
    Layout { opcode: 16, inline: false, handles: 0 },
    Layout { opcode: 17, inline: false, handles: 0 },
    Layout { opcode: 18, inline: false, handles: 0 },
    Layout { opcode: 19, inline: false, handles: 0 },
];

/// Every request of the protocol.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Message<'a> {
    Rename(Rename<'a>),
    CopyFile(CopyFile<'a>),
    SetAttr(SetAttr<'a>),
    GetAttr(GetAttr),
}

impl<'a> Message<'a> {
    /// The handles it carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Message::Rename(_) => &[],
            Message::CopyFile(_) => &[],
            Message::SetAttr(_) => &[],
            Message::GetAttr(_) => &[],
        }
    }

    /// The opcode in word 0.
    fn opcode(&self) -> u32 {
        match self {
            Message::Rename(_) => 16,
            Message::CopyFile(_) => 17,
            Message::SetAttr(_) => 18,
            Message::GetAttr(_) => 19,
        }
    }

    fn write(&self, w: &mut Writer<'_>) -> Result<(), Error> {
        match self {
            Message::Rename(m) => {
                w.u32(m.old_dir)?;
                w.string(m.old_name)?;
                w.u32(m.new_dir)?;
                w.string(m.new_name)
            }
            Message::CopyFile(m) => {
                w.u32(m.src_fid)?;
                w.u32(m.dst_dir)?;
                w.string(m.dst_name)
            }
            Message::SetAttr(m) => {
                w.u32(m.fid)?;
                w.u8(m.attr)?;
                w.bytes(m.value)
            }
            Message::GetAttr(m) => {
                w.u32(m.fid)?;
                w.u8(m.attr)
            }
        }
    }

    fn read_inline(_opcode: u32, _r: &mut Reader<'_>) -> Result<Self, Error> {
        Err(Error::BadOpcode)
    }

    fn read_buffer(opcode: u32, r: &mut Reader<'a>) -> Result<Self, Error> {
        Ok(match opcode {
            16 => Message::Rename(Rename { old_dir: r.u32()?, old_name: r.string()?, new_dir: r.u32()?, new_name: r.string()? }),
            17 => Message::CopyFile(CopyFile { src_fid: r.u32()?, dst_dir: r.u32()?, dst_name: r.string()? }),
            18 => Message::SetAttr(SetAttr { fid: r.u32()?, attr: r.u8()?, value: r.bytes()? }),
            19 => Message::GetAttr(GetAttr { fid: r.u32()?, attr: r.u8()? }),
            _ => return Err(Error::BadOpcode),
        })
    }

    /// Decodes a received request: its words, the buffer that came with it (empty if
    /// none), and how many handles it carried.
    pub fn decode(words: &Words, buf: &'a [u8], handles: usize) -> Result<Self, Error> {
        let layout = typed::layout(REQUESTS, typed::opcode(words)?)?;
        typed::decode(layout, words, buf, handles, Self::read_inline, Self::read_buffer)
    }

    /// Encodes the request: returns its words, and writes the fields into `buf` if it is
    /// a buffer message (the buffer's length is then in word 1).
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        let opcode = self.opcode();
        typed::encode(typed::layout(REQUESTS, opcode)?, opcode, buf, |w| self.write(w))
    }

    /// Decodes a request written into a 9P file: all of `bytes` is one operation.
    pub fn decode_file(bytes: &'a [u8]) -> Result<Self, Error> {
        typed::decode_file(REQUESTS, bytes, Self::read_buffer)
    }

    /// Writes the request in the file framing into the front of `out`; returns its length.
    pub fn encode_file(&self, out: &mut [u8]) -> Result<usize, Error> {
        typed::encode_file(typed::layout(REQUESTS, self.opcode())?, out, |w| self.write(w))
    }
}

/// Replies, by the opcode of their request.
const REPLIES: &[Layout] = &[
    Layout { opcode: 16, inline: false, handles: 0 },
    Layout { opcode: 17, inline: false, handles: 0 },
    Layout { opcode: 18, inline: false, handles: 0 },
    Layout { opcode: 19, inline: false, handles: 0 },
];

/// Every successful reply of the protocol, named after its request.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reply<'a> {
    Rename(RenameReply),
    CopyFile(CopyFileReply),
    SetAttr(SetAttrReply),
    GetAttr(GetAttrReply<'a>),
}

impl<'a> Reply<'a> {
    /// The handles it carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Reply::Rename(_) => &[],
            Reply::CopyFile(_) => &[],
            Reply::SetAttr(_) => &[],
            Reply::GetAttr(_) => &[],
        }
    }

    /// The opcode of the request this replies to.
    fn opcode(&self) -> u32 {
        match self {
            Reply::Rename(_) => 16,
            Reply::CopyFile(_) => 17,
            Reply::SetAttr(_) => 18,
            Reply::GetAttr(_) => 19,
        }
    }

    fn write(&self, w: &mut Writer<'_>) -> Result<(), Error> {
        match self {
            Reply::Rename(_) => Ok(()),
            Reply::CopyFile(m) => w.u64(m.count),
            Reply::SetAttr(_) => Ok(()),
            Reply::GetAttr(m) => w.bytes(m.value),
        }
    }

    fn read_inline(_opcode: u32, _r: &mut Reader<'_>) -> Result<Self, Error> {
        Err(Error::BadOpcode)
    }

    fn read_buffer(opcode: u32, r: &mut Reader<'a>) -> Result<Self, Error> {
        Ok(match opcode {
            16 => Reply::Rename(RenameReply {}),
            17 => Reply::CopyFile(CopyFileReply { count: r.u64()? }),
            18 => Reply::SetAttr(SetAttrReply {}),
            19 => Reply::GetAttr(GetAttrReply { value: r.bytes()? }),
            _ => return Err(Error::BadOpcode),
        })
    }

    /// Decodes the reply to the request with `opcode` (the caller knows what it sent):
    /// `Ok(Ok(reply))`, `Ok(Err(code))`
    /// for an error reply, or `Err` if the reply is malformed.
    pub fn decode(opcode: u32, words: &Words, buf: &'a [u8], handles: usize) -> Result<Result<Self, ErrorCode>, Error> {
        let layout = typed::layout(REPLIES, opcode)?;
        if let Some(code) = typed::reply_status(words, handles)? {
            return ErrorCode::from_code(code).map(Err).ok_or(Error::BadStatus);
        }
        typed::decode(layout, words, buf, handles, Self::read_inline, Self::read_buffer).map(Ok)
    }

    /// Encodes the reply (status 0): returns its words, and writes the fields into `buf`
    /// (the caller's lend) if it is a buffer message.
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        typed::encode(typed::layout(REPLIES, self.opcode())?, 0, buf, |w| self.write(w))
    }
}

/// The protocol's error codes: word 0 of an error reply. Code 1, `Malformed`, is every
/// protocol's: a request that does not decode (WIRE.md, Errors).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ErrorCode {
    Malformed,
    NotFound,
    Refused,
    Exists,
    NotDir,
}

impl ErrorCode {
    pub fn code(self) -> u32 {
        match self {
            ErrorCode::Malformed => 1,
            ErrorCode::NotFound => 2,
            ErrorCode::Refused => 3,
            ErrorCode::Exists => 4,
            ErrorCode::NotDir => 5,
        }
    }

    pub fn from_code(code: u32) -> Option<Self> {
        match code {
            1 => Some(ErrorCode::Malformed),
            2 => Some(ErrorCode::NotFound),
            3 => Some(ErrorCode::Refused),
            4 => Some(ErrorCode::Exists),
            5 => Some(ErrorCode::NotDir),
            _ => None,
        }
    }

    /// The words of the error reply (no buffer, no handles).
    pub fn encode(self) -> Words {
        typed::error_reply(self.code())
    }
}
