//! Typed messages of the `ipd` protocol.
//!
//! Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/ipd.md`.
//! Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.

use crate::codec::{Error, Reader, Writer};
use crate::typed::{self, Layout, Words};

/// `grant`: opcode 16, buffer; reply [`GrantReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Grant<'a> {
    pub scope: &'a [u8],
}

/// The reply to [`Grant`].
///
/// Handle slots: `conn` (slot 0, endpoint).
/// Kinds are documentation, checked by use: a handle of the wrong kind gets `WrongObject`
/// on first use.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GrantReply {
    pub id: u64,
}

/// `frame`: opcode 17, buffer, a `send`: its buffer is a transfer and there is no reply.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Frame<'a> {
    pub frame: &'a [u8],
}

/// The reply to [`Frame`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FrameReply {}

/// Requests by opcode.
const REQUESTS: &[Layout] = &[
    Layout { opcode: 16, inline: false, handles: 0 },
    Layout { opcode: 17, inline: false, handles: 0 },
];

/// Every request of the protocol.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Message<'a> {
    Grant(Grant<'a>),
    Frame(Frame<'a>),
}

impl<'a> Message<'a> {
    /// The handles it carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Message::Grant(_) => &[],
            Message::Frame(_) => &[],
        }
    }

    /// The opcode in word 0.
    fn opcode(&self) -> u32 {
        match self {
            Message::Grant(_) => 16,
            Message::Frame(_) => 17,
        }
    }

    fn write(&self, w: &mut Writer<'_>) -> Result<(), Error> {
        match self {
            Message::Grant(m) => w.bytes(m.scope),
            Message::Frame(m) => w.bytes(m.frame),
        }
    }

    fn read_inline(_opcode: u32, _r: &mut Reader<'_>) -> Result<Self, Error> {
        Err(Error::BadOpcode)
    }

    fn read_buffer(opcode: u32, r: &mut Reader<'a>) -> Result<Self, Error> {
        Ok(match opcode {
            16 => Message::Grant(Grant { scope: r.bytes()? }),
            17 => Message::Frame(Frame { frame: r.bytes()? }),
            _ => return Err(Error::BadOpcode),
        })
    }

    /// Decodes a received request: its words, the buffer that came with it (empty if
    /// none), and how many handles it carried.
    pub fn decode(words: &Words, buf: &'a [u8], handles: usize) -> Result<Self, Error> {
        let layout = typed::layout(REQUESTS, typed::opcode(words)?)?;
        typed::decode(layout, words, buf, handles, Self::read_inline, Self::read_buffer)
    }

    /// Encodes the request: returns its words, and writes the fields into `buf` if it is
    /// a buffer message (the buffer's length is then in word 1).
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        let opcode = self.opcode();
        typed::encode(typed::layout(REQUESTS, opcode)?, opcode, buf, |w| self.write(w))
    }

    /// Decodes a request written into a 9P file: all of `bytes` is one operation.
    pub fn decode_file(bytes: &'a [u8]) -> Result<Self, Error> {
        typed::decode_file(REQUESTS, bytes, Self::read_buffer)
    }

    /// Writes the request in the file framing into the front of `out`; returns its length.
    pub fn encode_file(&self, out: &mut [u8]) -> Result<usize, Error> {
        typed::encode_file(typed::layout(REQUESTS, self.opcode())?, out, |w| self.write(w))
    }

    /// Whether this message is sent one-way (`send`, its buffer a transfer) rather than
    /// called: a receiver must not reply to it, and a sender must not wait for a reply.
    pub fn is_send(&self) -> bool {
        matches!(self, Message::Frame(_))
    }
}

/// Replies, by the opcode of their request.
const REPLIES: &[Layout] = &[
    Layout { opcode: 16, inline: false, handles: 1 },
    Layout { opcode: 17, inline: false, handles: 0 },
];

/// Every successful reply of the protocol, named after its request.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reply {
    Grant(GrantReply),
    Frame(FrameReply),
}

impl<'a> Reply {
    /// The handles it carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Reply::Grant(_) => &["conn"],
            Reply::Frame(_) => &[],
        }
    }

    /// The opcode of the request this replies to.
    fn opcode(&self) -> u32 {
        match self {
            Reply::Grant(_) => 16,
            Reply::Frame(_) => 17,
        }
    }

    fn write(&self, w: &mut Writer<'_>) -> Result<(), Error> {
        match self {
            Reply::Grant(m) => w.u64(m.id),
            Reply::Frame(_) => Ok(()),
        }
    }

    fn read_inline(_opcode: u32, _r: &mut Reader<'_>) -> Result<Self, Error> {
        Err(Error::BadOpcode)
    }

    fn read_buffer(opcode: u32, r: &mut Reader<'a>) -> Result<Self, Error> {
        Ok(match opcode {
            16 => Reply::Grant(GrantReply { id: r.u64()? }),
            17 => Reply::Frame(FrameReply {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    /// Decodes the reply to the request with `opcode` (the caller knows what it sent):
    /// `Ok(Ok(reply))`, `Ok(Err(code))`
    /// for an error reply, or `Err` if the reply is malformed.
    pub fn decode(opcode: u32, words: &Words, buf: &'a [u8], handles: usize) -> Result<Result<Self, ErrorCode>, Error> {
        let layout = typed::layout(REPLIES, opcode)?;
        if let Some(code) = typed::reply_status(words, handles)? {
            return ErrorCode::from_code(code).map(Err).ok_or(Error::BadStatus);
        }
        typed::decode(layout, words, buf, handles, Self::read_inline, Self::read_buffer).map(Ok)
    }

    /// Encodes the reply (status 0): returns its words, and writes the fields into `buf`
    /// (the caller's lend) if it is a buffer message.
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        typed::encode(typed::layout(REPLIES, self.opcode())?, 0, buf, |w| self.write(w))
    }
}

/// The protocol's error codes: word 0 of an error reply. Code 1, `Malformed`, is every
/// protocol's: a request that does not decode (servers/wire.md, "The message convention").
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ErrorCode {
    Malformed,
    NotPermitted,
    TooMany,
}

impl ErrorCode {
    pub fn code(self) -> u32 {
        match self {
            ErrorCode::Malformed => 1,
            ErrorCode::NotPermitted => 2,
            ErrorCode::TooMany => 3,
        }
    }

    pub fn from_code(code: u32) -> Option<Self> {
        match code {
            1 => Some(ErrorCode::Malformed),
            2 => Some(ErrorCode::NotPermitted),
            3 => Some(ErrorCode::TooMany),
            _ => None,
        }
    }

    /// The words of the error reply (no buffer, no handles).
    pub fn encode(self) -> Words {
        typed::error_reply(self.code())
    }
}
