//! Typed messages of the `keyd` protocol.
//!
//! Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/keyd.md`.
//! Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.

use crate::codec::{Error, Reader, Writer};
use crate::typed::{self, Layout, Words};

/// `sign_ssh_exchange`: opcode 1, buffer; reply [`SignSshExchangeReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SignSshExchange<'a> {
    pub v_c: &'a [u8],
    pub v_s: &'a [u8],
    pub i_c: &'a [u8],
    pub i_s: &'a [u8],
    pub q_c: &'a [u8],
    pub q_s: &'a [u8],
    pub k: &'a [u8],
}

/// The reply to [`SignSshExchange`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SignSshExchangeReply<'a> {
    pub signature: &'a [u8],
}

/// `sign_record`: opcode 2, buffer; reply [`SignRecordReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SignRecord<'a> {
    pub record: &'a [u8],
}

/// The reply to [`SignRecord`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SignRecordReply<'a> {
    pub signature: &'a [u8],
}

/// `public_key`: opcode 3, buffer; reply [`PublicKeyReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PublicKey {}

/// The reply to [`PublicKey`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PublicKeyReply<'a> {
    pub key: &'a [u8],
}

/// `holds`: opcode 4, buffer; reply [`HoldsReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Holds<'a> {
    pub key: &'a [u8],
}

/// The reply to [`Holds`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct HoldsReply {
    pub held: u32,
}

/// `grant`: opcode 5, inline; reply [`GrantReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Grant {}

/// The reply to [`Grant`].
///
/// Handle slots: `capability` (slot 0, endpoint).
/// Kinds are documentation, checked by use: a handle of the wrong kind gets `WrongObject`
/// on first use.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GrantReply {
    pub id: u64,
}

/// `release`: opcode 6, inline; reply [`ReleaseReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Release {
    pub id: u64,
}

/// The reply to [`Release`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReleaseReply {}

/// Requests by opcode.
const REQUESTS: &[Layout] = &[
    Layout { opcode: 1, inline: false, handles: 0 },
    Layout { opcode: 2, inline: false, handles: 0 },
    Layout { opcode: 3, inline: false, handles: 0 },
    Layout { opcode: 4, inline: false, handles: 0 },
    Layout { opcode: 5, inline: true, handles: 0 },
    Layout { opcode: 6, inline: true, handles: 0 },
];

/// Every request of the protocol.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Message<'a> {
    SignSshExchange(SignSshExchange<'a>),
    SignRecord(SignRecord<'a>),
    PublicKey(PublicKey),
    Holds(Holds<'a>),
    Grant(Grant),
    Release(Release),
}

impl<'a> Message<'a> {
    /// The handles it carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Message::SignSshExchange(_) => &[],
            Message::SignRecord(_) => &[],
            Message::PublicKey(_) => &[],
            Message::Holds(_) => &[],
            Message::Grant(_) => &[],
            Message::Release(_) => &[],
        }
    }

    /// The opcode in word 0.
    fn opcode(&self) -> u32 {
        match self {
            Message::SignSshExchange(_) => 1,
            Message::SignRecord(_) => 2,
            Message::PublicKey(_) => 3,
            Message::Holds(_) => 4,
            Message::Grant(_) => 5,
            Message::Release(_) => 6,
        }
    }

    fn write(&self, w: &mut Writer<'_>) -> Result<(), Error> {
        match self {
            Message::SignSshExchange(m) => {
                w.bytes(m.v_c)?;
                w.bytes(m.v_s)?;
                w.bytes(m.i_c)?;
                w.bytes(m.i_s)?;
                w.bytes(m.q_c)?;
                w.bytes(m.q_s)?;
                w.bytes(m.k)
            }
            Message::SignRecord(m) => w.bytes(m.record),
            Message::PublicKey(_) => Ok(()),
            Message::Holds(m) => w.bytes(m.key),
            Message::Grant(_) => Ok(()),
            Message::Release(m) => w.u64(m.id),
        }
    }

    fn read_inline(opcode: u32, r: &mut Reader<'_>) -> Result<Self, Error> {
        Ok(match opcode {
            5 => Message::Grant(Grant {}),
            6 => Message::Release(Release { id: r.u64()? }),
            _ => return Err(Error::BadOpcode),
        })
    }

    fn read_buffer(opcode: u32, r: &mut Reader<'a>) -> Result<Self, Error> {
        Ok(match opcode {
            1 => Message::SignSshExchange(SignSshExchange { v_c: r.bytes()?, v_s: r.bytes()?, i_c: r.bytes()?, i_s: r.bytes()?, q_c: r.bytes()?, q_s: r.bytes()?, k: r.bytes()? }),
            2 => Message::SignRecord(SignRecord { record: r.bytes()? }),
            3 => Message::PublicKey(PublicKey {}),
            4 => Message::Holds(Holds { key: r.bytes()? }),
            5 => Message::Grant(Grant {}),
            6 => Message::Release(Release { id: r.u64()? }),
            _ => return Err(Error::BadOpcode),
        })
    }

    /// Decodes a received request: its words, the buffer that came with it (empty if
    /// none), and how many handles it carried.
    pub fn decode(words: &Words, buf: &'a [u8], handles: usize) -> Result<Self, Error> {
        let layout = typed::layout(REQUESTS, typed::opcode(words)?)?;
        typed::decode(layout, words, buf, handles, Self::read_inline, Self::read_buffer)
    }

    /// Encodes the request: returns its words, and writes the fields into `buf` if it is
    /// a buffer message (the buffer's length is then in word 1).
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        let opcode = self.opcode();
        typed::encode(typed::layout(REQUESTS, opcode)?, opcode, buf, |w| self.write(w))
    }

    /// Decodes a request written into a 9P file: all of `bytes` is one operation.
    pub fn decode_file(bytes: &'a [u8]) -> Result<Self, Error> {
        typed::decode_file(REQUESTS, bytes, Self::read_buffer)
    }

    /// Writes the request in the file framing into the front of `out`; returns its length.
    pub fn encode_file(&self, out: &mut [u8]) -> Result<usize, Error> {
        typed::encode_file(typed::layout(REQUESTS, self.opcode())?, out, |w| self.write(w))
    }
}

/// Replies, by the opcode of their request.
const REPLIES: &[Layout] = &[
    Layout { opcode: 1, inline: false, handles: 0 },
    Layout { opcode: 2, inline: false, handles: 0 },
    Layout { opcode: 3, inline: false, handles: 0 },
    Layout { opcode: 4, inline: false, handles: 0 },
    Layout { opcode: 5, inline: true, handles: 1 },
    Layout { opcode: 6, inline: true, handles: 0 },
];

/// Every successful reply of the protocol, named after its request.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reply<'a> {
    SignSshExchange(SignSshExchangeReply<'a>),
    SignRecord(SignRecordReply<'a>),
    PublicKey(PublicKeyReply<'a>),
    Holds(HoldsReply),
    Grant(GrantReply),
    Release(ReleaseReply),
}

impl<'a> Reply<'a> {
    /// The handles it carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Reply::SignSshExchange(_) => &[],
            Reply::SignRecord(_) => &[],
            Reply::PublicKey(_) => &[],
            Reply::Holds(_) => &[],
            Reply::Grant(_) => &["capability"],
            Reply::Release(_) => &[],
        }
    }

    /// The opcode of the request this replies to.
    fn opcode(&self) -> u32 {
        match self {
            Reply::SignSshExchange(_) => 1,
            Reply::SignRecord(_) => 2,
            Reply::PublicKey(_) => 3,
            Reply::Holds(_) => 4,
            Reply::Grant(_) => 5,
            Reply::Release(_) => 6,
        }
    }

    fn write(&self, w: &mut Writer<'_>) -> Result<(), Error> {
        match self {
            Reply::SignSshExchange(m) => w.bytes(m.signature),
            Reply::SignRecord(m) => w.bytes(m.signature),
            Reply::PublicKey(m) => w.bytes(m.key),
            Reply::Holds(m) => w.u32(m.held),
            Reply::Grant(m) => w.u64(m.id),
            Reply::Release(_) => Ok(()),
        }
    }

    fn read_inline(opcode: u32, r: &mut Reader<'_>) -> Result<Self, Error> {
        Ok(match opcode {
            5 => Reply::Grant(GrantReply { id: r.u64()? }),
            6 => Reply::Release(ReleaseReply {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    fn read_buffer(opcode: u32, r: &mut Reader<'a>) -> Result<Self, Error> {
        Ok(match opcode {
            1 => Reply::SignSshExchange(SignSshExchangeReply { signature: r.bytes()? }),
            2 => Reply::SignRecord(SignRecordReply { signature: r.bytes()? }),
            3 => Reply::PublicKey(PublicKeyReply { key: r.bytes()? }),
            4 => Reply::Holds(HoldsReply { held: r.u32()? }),
            5 => Reply::Grant(GrantReply { id: r.u64()? }),
            6 => Reply::Release(ReleaseReply {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    /// Decodes the reply to the request with `opcode` (the caller knows what it sent):
    /// `Ok(Ok(reply))`, `Ok(Err(code))`
    /// for an error reply, or `Err` if the reply is malformed.
    pub fn decode(opcode: u32, words: &Words, buf: &'a [u8], handles: usize) -> Result<Result<Self, ErrorCode>, Error> {
        let layout = typed::layout(REPLIES, opcode)?;
        if let Some(code) = typed::reply_status(words, handles)? {
            return ErrorCode::from_code(code).map(Err).ok_or(Error::BadStatus);
        }
        typed::decode(layout, words, buf, handles, Self::read_inline, Self::read_buffer).map(Ok)
    }

    /// Encodes the reply (status 0): returns its words, and writes the fields into `buf`
    /// (the caller's lend) if it is a buffer message.
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        typed::encode(typed::layout(REPLIES, self.opcode())?, 0, buf, |w| self.write(w))
    }
}

/// The protocol's error codes: word 0 of an error reply. Code 1, `Malformed`, is every
/// protocol's: a request that does not decode (WIRE.md, Errors).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ErrorCode {
    Malformed,
    NotPermitted,
    TooMany,
    Failed,
}

impl ErrorCode {
    pub fn code(self) -> u32 {
        match self {
            ErrorCode::Malformed => 1,
            ErrorCode::NotPermitted => 2,
            ErrorCode::TooMany => 3,
            ErrorCode::Failed => 4,
        }
    }

    pub fn from_code(code: u32) -> Option<Self> {
        match code {
            1 => Some(ErrorCode::Malformed),
            2 => Some(ErrorCode::NotPermitted),
            3 => Some(ErrorCode::TooMany),
            4 => Some(ErrorCode::Failed),
            _ => None,
        }
    }

    /// The words of the error reply (no buffer, no handles).
    pub fn encode(self) -> Words {
        typed::error_reply(self.code())
    }
}
