//! Typed messages of the `net_ctl` protocol.
//!
//! Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/net_ctl.md`.
//! Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.

use crate::codec::{Error, Reader, Writer};
use crate::typed::{self, Layout, Words};

/// `connect`: opcode 1, buffer; reply [`ConnectReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Connect<'a> {
    pub addr: &'a [u8],
    pub port: u16,
}

/// The reply to [`Connect`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ConnectReply {}

/// `listen`: opcode 2, inline; reply [`ListenReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Listen {
    pub port: u16,
    pub backlog: u8,
}

/// The reply to [`Listen`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ListenReply {}

/// `close`: opcode 3, inline; reply [`CloseReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Close {}

/// The reply to [`Close`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CloseReply {}

/// `abort`: opcode 4, inline; reply [`AbortReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Abort {}

/// The reply to [`Abort`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AbortReply {}

/// Requests by opcode.
const REQUESTS: &[Layout] = &[
    Layout { opcode: 1, inline: false, handles: 0 },
    Layout { opcode: 2, inline: true, handles: 0 },
    Layout { opcode: 3, inline: true, handles: 0 },
    Layout { opcode: 4, inline: true, handles: 0 },
];

/// Every request of the protocol.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Message<'a> {
    Connect(Connect<'a>),
    Listen(Listen),
    Close(Close),
    Abort(Abort),
}

impl<'a> Message<'a> {
    /// The handles it carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Message::Connect(_) => &[],
            Message::Listen(_) => &[],
            Message::Close(_) => &[],
            Message::Abort(_) => &[],
        }
    }

    /// The opcode in word 0.
    fn opcode(&self) -> u32 {
        match self {
            Message::Connect(_) => 1,
            Message::Listen(_) => 2,
            Message::Close(_) => 3,
            Message::Abort(_) => 4,
        }
    }

    fn write(&self, w: &mut Writer<'_>) -> Result<(), Error> {
        match self {
            Message::Connect(m) => {
                w.bytes(m.addr)?;
                w.u16(m.port)
            }
            Message::Listen(m) => {
                w.u16(m.port)?;
                w.u8(m.backlog)
            }
            Message::Close(_) => Ok(()),
            Message::Abort(_) => Ok(()),
        }
    }

    fn read_inline(opcode: u32, r: &mut Reader<'_>) -> Result<Self, Error> {
        Ok(match opcode {
            2 => Message::Listen(Listen { port: r.u16()?, backlog: r.u8()? }),
            3 => Message::Close(Close {}),
            4 => Message::Abort(Abort {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    fn read_buffer(opcode: u32, r: &mut Reader<'a>) -> Result<Self, Error> {
        Ok(match opcode {
            1 => Message::Connect(Connect { addr: r.bytes()?, port: r.u16()? }),
            2 => Message::Listen(Listen { port: r.u16()?, backlog: r.u8()? }),
            3 => Message::Close(Close {}),
            4 => Message::Abort(Abort {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    /// Decodes a received request: its words, the buffer that came with it (empty if
    /// none), and how many handles it carried.
    pub fn decode(words: &Words, buf: &'a [u8], handles: usize) -> Result<Self, Error> {
        let layout = typed::layout(REQUESTS, typed::opcode(words)?)?;
        typed::decode(layout, words, buf, handles, Self::read_inline, Self::read_buffer)
    }

    /// Encodes the request: returns its words, and writes the fields into `buf` if it is
    /// a buffer message (the buffer's length is then in word 1).
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        let opcode = self.opcode();
        typed::encode(typed::layout(REQUESTS, opcode)?, opcode, buf, |w| self.write(w))
    }

    /// Decodes a request written into a 9P file: all of `bytes` is one operation.
    pub fn decode_file(bytes: &'a [u8]) -> Result<Self, Error> {
        typed::decode_file(REQUESTS, bytes, Self::read_buffer)
    }

    /// Writes the request in the file framing into the front of `out`; returns its length.
    pub fn encode_file(&self, out: &mut [u8]) -> Result<usize, Error> {
        typed::encode_file(typed::layout(REQUESTS, self.opcode())?, out, |w| self.write(w))
    }
}

/// Replies, by the opcode of their request.
const REPLIES: &[Layout] = &[
    Layout { opcode: 1, inline: false, handles: 0 },
    Layout { opcode: 2, inline: true, handles: 0 },
    Layout { opcode: 3, inline: true, handles: 0 },
    Layout { opcode: 4, inline: true, handles: 0 },
];

/// Every successful reply of the protocol, named after its request.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reply {
    Connect(ConnectReply),
    Listen(ListenReply),
    Close(CloseReply),
    Abort(AbortReply),
}

impl<'a> Reply {
    /// The handles it carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Reply::Connect(_) => &[],
            Reply::Listen(_) => &[],
            Reply::Close(_) => &[],
            Reply::Abort(_) => &[],
        }
    }

    /// The opcode of the request this replies to.
    fn opcode(&self) -> u32 {
        match self {
            Reply::Connect(_) => 1,
            Reply::Listen(_) => 2,
            Reply::Close(_) => 3,
            Reply::Abort(_) => 4,
        }
    }

    fn write(&self, _w: &mut Writer<'_>) -> Result<(), Error> {
        match self {
            Reply::Connect(_) => Ok(()),
            Reply::Listen(_) => Ok(()),
            Reply::Close(_) => Ok(()),
            Reply::Abort(_) => Ok(()),
        }
    }

    fn read_inline(opcode: u32, _r: &mut Reader<'_>) -> Result<Self, Error> {
        Ok(match opcode {
            2 => Reply::Listen(ListenReply {}),
            3 => Reply::Close(CloseReply {}),
            4 => Reply::Abort(AbortReply {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    fn read_buffer(opcode: u32, _r: &mut Reader<'a>) -> Result<Self, Error> {
        Ok(match opcode {
            1 => Reply::Connect(ConnectReply {}),
            2 => Reply::Listen(ListenReply {}),
            3 => Reply::Close(CloseReply {}),
            4 => Reply::Abort(AbortReply {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    /// Decodes the reply to the request with `opcode` (the caller knows what it sent):
    /// `Ok(Ok(reply))`, `Ok(Err(code))`
    /// for an error reply, or `Err` if the reply is malformed.
    pub fn decode(opcode: u32, words: &Words, buf: &'a [u8], handles: usize) -> Result<Result<Self, ErrorCode>, Error> {
        let layout = typed::layout(REPLIES, opcode)?;
        if let Some(code) = typed::reply_status(words, handles)? {
            return ErrorCode::from_code(code).map(Err).ok_or(Error::BadStatus);
        }
        typed::decode(layout, words, buf, handles, Self::read_inline, Self::read_buffer).map(Ok)
    }

    /// Encodes the reply (status 0): returns its words, and writes the fields into `buf`
    /// (the caller's lend) if it is a buffer message.
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        typed::encode(typed::layout(REPLIES, self.opcode())?, 0, buf, |w| self.write(w))
    }
}

/// The protocol's error codes: word 0 of an error reply. Code 1, `Malformed`, is every
/// protocol's: a request that does not decode (servers/wire.md, "The message convention").
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ErrorCode {
    Malformed,
    NotPermitted,
    InUse,
    TooMany,
    State,
    Unreachable,
    Refused,
    Timeout,
}

impl ErrorCode {
    pub fn code(self) -> u32 {
        match self {
            ErrorCode::Malformed => 1,
            ErrorCode::NotPermitted => 2,
            ErrorCode::InUse => 3,
            ErrorCode::TooMany => 4,
            ErrorCode::State => 5,
            ErrorCode::Unreachable => 6,
            ErrorCode::Refused => 7,
            ErrorCode::Timeout => 8,
        }
    }

    pub fn from_code(code: u32) -> Option<Self> {
        match code {
            1 => Some(ErrorCode::Malformed),
            2 => Some(ErrorCode::NotPermitted),
            3 => Some(ErrorCode::InUse),
            4 => Some(ErrorCode::TooMany),
            5 => Some(ErrorCode::State),
            6 => Some(ErrorCode::Unreachable),
            7 => Some(ErrorCode::Refused),
            8 => Some(ErrorCode::Timeout),
            _ => None,
        }
    }

    /// The words of the error reply (no buffer, no handles).
    pub fn encode(self) -> Words {
        typed::error_reply(self.code())
    }
}
