//! Typed messages of the `startup` protocol.
//!
//! Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/startup.md`.
//! Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.

use crate::codec::{Error, Reader, Writer};
use crate::typed::{self, Layout, Words};

/// `startup`: opcode 1, buffer; reply [`StartupReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Startup<'a> {
    pub version: u32,
    pub handle_count: u32,
    pub namespace: &'a [u8],
    pub handles: &'a [u8],
    pub argv: &'a [u8],
    pub image_addr: u64,
    pub image_len: u64,
}

/// The reply to [`Startup`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StartupReply {}

/// Requests by opcode.
const REQUESTS: &[Layout] = &[
    Layout { opcode: 1, inline: false, handles: 0 },
];

/// Every request of the protocol.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Message<'a> {
    Startup(Startup<'a>),
}

impl<'a> Message<'a> {
    /// The handles it carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Message::Startup(_) => &[],
        }
    }

    /// The opcode in word 0.
    fn opcode(&self) -> u32 {
        match self {
            Message::Startup(_) => 1,
        }
    }

    fn write(&self, w: &mut Writer<'_>) -> Result<(), Error> {
        match self {
            Message::Startup(m) => {
                w.u32(m.version)?;
                w.u32(m.handle_count)?;
                w.bytes(m.namespace)?;
                w.bytes(m.handles)?;
                w.bytes(m.argv)?;
                w.u64(m.image_addr)?;
                w.u64(m.image_len)
            }
        }
    }

    fn read_inline(_opcode: u32, _r: &mut Reader<'_>) -> Result<Self, Error> {
        Err(Error::BadOpcode)
    }

    fn read_buffer(opcode: u32, r: &mut Reader<'a>) -> Result<Self, Error> {
        Ok(match opcode {
            1 => Message::Startup(Startup { version: r.u32()?, handle_count: r.u32()?, namespace: r.bytes()?, handles: r.bytes()?, argv: r.bytes()?, image_addr: r.u64()?, image_len: r.u64()? }),
            _ => return Err(Error::BadOpcode),
        })
    }

    /// Decodes a received request: its words, the buffer that came with it (empty if
    /// none), and how many handles it carried.
    pub fn decode(words: &Words, buf: &'a [u8], handles: usize) -> Result<Self, Error> {
        let layout = typed::layout(REQUESTS, typed::opcode(words)?)?;
        typed::decode(layout, words, buf, handles, Self::read_inline, Self::read_buffer)
    }

    /// Encodes the request: returns its words, and writes the fields into `buf` if it is
    /// a buffer message (the buffer's length is then in word 1).
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        let opcode = self.opcode();
        typed::encode(typed::layout(REQUESTS, opcode)?, opcode, buf, |w| self.write(w))
    }

    /// Decodes a request written into a 9P file: all of `bytes` is one operation.
    pub fn decode_file(bytes: &'a [u8]) -> Result<Self, Error> {
        typed::decode_file(REQUESTS, bytes, Self::read_buffer)
    }

    /// Writes the request in the file framing into the front of `out`; returns its length.
    pub fn encode_file(&self, out: &mut [u8]) -> Result<usize, Error> {
        typed::encode_file(typed::layout(REQUESTS, self.opcode())?, out, |w| self.write(w))
    }
}

/// Replies, by the opcode of their request.
const REPLIES: &[Layout] = &[
    Layout { opcode: 1, inline: false, handles: 0 },
];

/// Every successful reply of the protocol, named after its request.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reply {
    Startup(StartupReply),
}

impl<'a> Reply {
    /// The handles it carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Reply::Startup(_) => &[],
        }
    }

    /// The opcode of the request this replies to.
    fn opcode(&self) -> u32 {
        match self {
            Reply::Startup(_) => 1,
        }
    }

    fn write(&self, _w: &mut Writer<'_>) -> Result<(), Error> {
        match self {
            Reply::Startup(_) => Ok(()),
        }
    }

    fn read_inline(_opcode: u32, _r: &mut Reader<'_>) -> Result<Self, Error> {
        Err(Error::BadOpcode)
    }

    fn read_buffer(opcode: u32, _r: &mut Reader<'a>) -> Result<Self, Error> {
        Ok(match opcode {
            1 => Reply::Startup(StartupReply {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    /// Decodes the reply to the request with `opcode` (the caller knows what it sent):
    /// `Ok(Ok(reply))`, `Ok(Err(code))`
    /// for an error reply, or `Err` if the reply is malformed.
    pub fn decode(opcode: u32, words: &Words, buf: &'a [u8], handles: usize) -> Result<Result<Self, ErrorCode>, Error> {
        let layout = typed::layout(REPLIES, opcode)?;
        if let Some(code) = typed::reply_status(words, handles)? {
            return ErrorCode::from_code(code).map(Err).ok_or(Error::BadStatus);
        }
        typed::decode(layout, words, buf, handles, Self::read_inline, Self::read_buffer).map(Ok)
    }

    /// Encodes the reply (status 0): returns its words, and writes the fields into `buf`
    /// (the caller's lend) if it is a buffer message.
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        typed::encode(typed::layout(REPLIES, self.opcode())?, 0, buf, |w| self.write(w))
    }
}

/// The protocol's error codes: word 0 of an error reply. Code 1, `Malformed`, is every
/// protocol's: a request that does not decode (servers/wire.md, "The message convention").
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ErrorCode {
    Malformed,
}

impl ErrorCode {
    pub fn code(self) -> u32 {
        match self {
            ErrorCode::Malformed => 1,
        }
    }

    pub fn from_code(code: u32) -> Option<Self> {
        match code {
            1 => Some(ErrorCode::Malformed),
            _ => None,
        }
    }

    /// The words of the error reply (no buffer, no handles).
    pub fn encode(self) -> Words {
        typed::error_reply(self.code())
    }
}
