//! Typed messages of the `steward` protocol.
//!
//! Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/steward.md`.
//! Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.

use crate::codec::{Error, Reader, Writer};
use crate::typed::{self, Layout, Words};

/// `login`: opcode 1, buffer; reply [`LoginReply`].
///
/// Handle slots: `console` (slot 0, endpoint), `relay` (slot 1, endpoint).
/// Kinds are documentation, checked by use: a handle of the wrong kind gets `WrongObject`
/// on first use.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Login<'a> {
    pub principal: &'a str,
    pub label: &'a str,
    pub context: &'a str,
    pub from: &'a str,
    pub key: &'a [u8],
}

/// The reply to [`Login`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LoginReply<'a> {
    pub session: u64,
    pub name: &'a str,
    pub labels: &'a [u8],
}

/// `channel_closed`: opcode 2, inline; reply [`ChannelClosedReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ChannelClosed {
    pub session: u64,
}

/// The reply to [`ChannelClosed`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ChannelClosedReply {}

/// `approval_opened`: opcode 3, buffer; reply [`ApprovalOpenedReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ApprovalOpened<'a> {
    pub principal: &'a str,
    pub key: &'a [u8],
}

/// The reply to [`ApprovalOpened`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ApprovalOpenedReply {
    pub channel: u64,
}

/// `approval_closed`: opcode 4, inline; reply [`ApprovalClosedReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ApprovalClosed {
    pub channel: u64,
}

/// The reply to [`ApprovalClosed`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ApprovalClosedReply {}

/// `pending`: opcode 5, buffer; reply [`PendingReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Pending {
    pub channel: u64,
}

/// The reply to [`Pending`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PendingReply<'a> {
    pub request: u64,
    pub hash: &'a [u8],
    pub labels: &'a [u8],
    pub text: &'a str,
}

/// `approve`: opcode 6, buffer; reply [`ApproveReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Approve<'a> {
    pub channel: u64,
    pub request: u64,
    pub hash: &'a [u8],
}

/// The reply to [`Approve`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ApproveReply {}

/// `deny`: opcode 7, buffer; reply [`DenyReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Deny {
    pub channel: u64,
    pub request: u64,
}

/// The reply to [`Deny`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DenyReply {}

/// `blame`: opcode 8, buffer; reply [`BlameReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Blame<'a> {
    pub account: u64,
    pub labels: &'a [u8],
    pub server: &'a str,
}

/// The reply to [`Blame`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BlameReply {}

/// `submit`: opcode 9, buffer; reply [`SubmitReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Submit<'a> {
    pub kind: u32,
    pub labels: &'a [u8],
    pub lease: u64,
    pub item: u64,
    pub source: u64,
    pub what: &'a str,
    pub reason: &'a str,
}

/// The reply to [`Submit`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SubmitReply {
    pub request: u64,
}

/// `start_agent`: opcode 10, buffer; reply [`StartAgentReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StartAgent {
    pub lease: u64,
}

/// The reply to [`StartAgent`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StartAgentReply<'a> {
    pub lease: u64,
    pub name: &'a str,
}

/// `end_lease`: opcode 11, inline; reply [`EndLeaseReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EndLease {
    pub lease: u64,
}

/// The reply to [`EndLease`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EndLeaseReply {}

/// `end_session`: opcode 12, inline; reply [`EndSessionReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EndSession {}

/// The reply to [`EndSession`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EndSessionReply {}

/// `watch`: opcode 13, inline; reply [`WatchReply`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Watch {}

/// The reply to [`Watch`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WatchReply {}

/// Requests by opcode.
const REQUESTS: &[Layout] = &[
    Layout { opcode: 1, inline: false, handles: 2 },
    Layout { opcode: 2, inline: true, handles: 0 },
    Layout { opcode: 3, inline: false, handles: 0 },
    Layout { opcode: 4, inline: true, handles: 0 },
    Layout { opcode: 5, inline: false, handles: 0 },
    Layout { opcode: 6, inline: false, handles: 0 },
    Layout { opcode: 7, inline: false, handles: 0 },
    Layout { opcode: 8, inline: false, handles: 0 },
    Layout { opcode: 9, inline: false, handles: 0 },
    Layout { opcode: 10, inline: false, handles: 0 },
    Layout { opcode: 11, inline: true, handles: 0 },
    Layout { opcode: 12, inline: true, handles: 0 },
    Layout { opcode: 13, inline: true, handles: 0 },
];

/// Every request of the protocol.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Message<'a> {
    Login(Login<'a>),
    ChannelClosed(ChannelClosed),
    ApprovalOpened(ApprovalOpened<'a>),
    ApprovalClosed(ApprovalClosed),
    Pending(Pending),
    Approve(Approve<'a>),
    Deny(Deny),
    Blame(Blame<'a>),
    Submit(Submit<'a>),
    StartAgent(StartAgent),
    EndLease(EndLease),
    EndSession(EndSession),
    Watch(Watch),
}

impl<'a> Message<'a> {
    /// The handles it carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Message::Login(_) => &["console", "relay"],
            Message::ChannelClosed(_) => &[],
            Message::ApprovalOpened(_) => &[],
            Message::ApprovalClosed(_) => &[],
            Message::Pending(_) => &[],
            Message::Approve(_) => &[],
            Message::Deny(_) => &[],
            Message::Blame(_) => &[],
            Message::Submit(_) => &[],
            Message::StartAgent(_) => &[],
            Message::EndLease(_) => &[],
            Message::EndSession(_) => &[],
            Message::Watch(_) => &[],
        }
    }

    /// The opcode in word 0.
    fn opcode(&self) -> u32 {
        match self {
            Message::Login(_) => 1,
            Message::ChannelClosed(_) => 2,
            Message::ApprovalOpened(_) => 3,
            Message::ApprovalClosed(_) => 4,
            Message::Pending(_) => 5,
            Message::Approve(_) => 6,
            Message::Deny(_) => 7,
            Message::Blame(_) => 8,
            Message::Submit(_) => 9,
            Message::StartAgent(_) => 10,
            Message::EndLease(_) => 11,
            Message::EndSession(_) => 12,
            Message::Watch(_) => 13,
        }
    }

    fn write(&self, w: &mut Writer<'_>) -> Result<(), Error> {
        match self {
            Message::Login(m) => {
                w.string(m.principal)?;
                w.string(m.label)?;
                w.string(m.context)?;
                w.string(m.from)?;
                w.bytes(m.key)
            }
            Message::ChannelClosed(m) => w.u64(m.session),
            Message::ApprovalOpened(m) => {
                w.string(m.principal)?;
                w.bytes(m.key)
            }
            Message::ApprovalClosed(m) => w.u64(m.channel),
            Message::Pending(m) => w.u64(m.channel),
            Message::Approve(m) => {
                w.u64(m.channel)?;
                w.u64(m.request)?;
                w.bytes(m.hash)
            }
            Message::Deny(m) => {
                w.u64(m.channel)?;
                w.u64(m.request)
            }
            Message::Blame(m) => {
                w.u64(m.account)?;
                w.bytes(m.labels)?;
                w.string(m.server)
            }
            Message::Submit(m) => {
                w.u32(m.kind)?;
                w.bytes(m.labels)?;
                w.u64(m.lease)?;
                w.u64(m.item)?;
                w.u64(m.source)?;
                w.string(m.what)?;
                w.string(m.reason)
            }
            Message::StartAgent(m) => w.u64(m.lease),
            Message::EndLease(m) => w.u64(m.lease),
            Message::EndSession(_) => Ok(()),
            Message::Watch(_) => Ok(()),
        }
    }

    fn read_inline(opcode: u32, r: &mut Reader<'_>) -> Result<Self, Error> {
        Ok(match opcode {
            2 => Message::ChannelClosed(ChannelClosed { session: r.u64()? }),
            4 => Message::ApprovalClosed(ApprovalClosed { channel: r.u64()? }),
            11 => Message::EndLease(EndLease { lease: r.u64()? }),
            12 => Message::EndSession(EndSession {}),
            13 => Message::Watch(Watch {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    fn read_buffer(opcode: u32, r: &mut Reader<'a>) -> Result<Self, Error> {
        Ok(match opcode {
            1 => Message::Login(Login { principal: r.string()?, label: r.string()?, context: r.string()?, from: r.string()?, key: r.bytes()? }),
            2 => Message::ChannelClosed(ChannelClosed { session: r.u64()? }),
            3 => Message::ApprovalOpened(ApprovalOpened { principal: r.string()?, key: r.bytes()? }),
            4 => Message::ApprovalClosed(ApprovalClosed { channel: r.u64()? }),
            5 => Message::Pending(Pending { channel: r.u64()? }),
            6 => Message::Approve(Approve { channel: r.u64()?, request: r.u64()?, hash: r.bytes()? }),
            7 => Message::Deny(Deny { channel: r.u64()?, request: r.u64()? }),
            8 => Message::Blame(Blame { account: r.u64()?, labels: r.bytes()?, server: r.string()? }),
            9 => Message::Submit(Submit { kind: r.u32()?, labels: r.bytes()?, lease: r.u64()?, item: r.u64()?, source: r.u64()?, what: r.string()?, reason: r.string()? }),
            10 => Message::StartAgent(StartAgent { lease: r.u64()? }),
            11 => Message::EndLease(EndLease { lease: r.u64()? }),
            12 => Message::EndSession(EndSession {}),
            13 => Message::Watch(Watch {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    /// Decodes a received request: its words, the buffer that came with it (empty if
    /// none), and how many handles it carried.
    pub fn decode(words: &Words, buf: &'a [u8], handles: usize) -> Result<Self, Error> {
        let layout = typed::layout(REQUESTS, typed::opcode(words)?)?;
        typed::decode(layout, words, buf, handles, Self::read_inline, Self::read_buffer)
    }

    /// Encodes the request: returns its words, and writes the fields into `buf` if it is
    /// a buffer message (the buffer's length is then in word 1).
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        let opcode = self.opcode();
        typed::encode(typed::layout(REQUESTS, opcode)?, opcode, buf, |w| self.write(w))
    }

    /// Decodes a request written into a 9P file: all of `bytes` is one operation.
    pub fn decode_file(bytes: &'a [u8]) -> Result<Self, Error> {
        typed::decode_file(REQUESTS, bytes, Self::read_buffer)
    }

    /// Writes the request in the file framing into the front of `out`; returns its length.
    pub fn encode_file(&self, out: &mut [u8]) -> Result<usize, Error> {
        typed::encode_file(typed::layout(REQUESTS, self.opcode())?, out, |w| self.write(w))
    }
}

/// Replies, by the opcode of their request.
const REPLIES: &[Layout] = &[
    Layout { opcode: 1, inline: false, handles: 0 },
    Layout { opcode: 2, inline: true, handles: 0 },
    Layout { opcode: 3, inline: false, handles: 0 },
    Layout { opcode: 4, inline: true, handles: 0 },
    Layout { opcode: 5, inline: false, handles: 0 },
    Layout { opcode: 6, inline: false, handles: 0 },
    Layout { opcode: 7, inline: false, handles: 0 },
    Layout { opcode: 8, inline: false, handles: 0 },
    Layout { opcode: 9, inline: false, handles: 0 },
    Layout { opcode: 10, inline: false, handles: 0 },
    Layout { opcode: 11, inline: true, handles: 0 },
    Layout { opcode: 12, inline: true, handles: 0 },
    Layout { opcode: 13, inline: true, handles: 0 },
];

/// Every successful reply of the protocol, named after its request.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reply<'a> {
    Login(LoginReply<'a>),
    ChannelClosed(ChannelClosedReply),
    ApprovalOpened(ApprovalOpenedReply),
    ApprovalClosed(ApprovalClosedReply),
    Pending(PendingReply<'a>),
    Approve(ApproveReply),
    Deny(DenyReply),
    Blame(BlameReply),
    Submit(SubmitReply),
    StartAgent(StartAgentReply<'a>),
    EndLease(EndLeaseReply),
    EndSession(EndSessionReply),
    Watch(WatchReply),
}

impl<'a> Reply<'a> {
    /// The handles it carries, by slot.
    pub fn handle_names(&self) -> &'static [&'static str] {
        match self {
            Reply::Login(_) => &[],
            Reply::ChannelClosed(_) => &[],
            Reply::ApprovalOpened(_) => &[],
            Reply::ApprovalClosed(_) => &[],
            Reply::Pending(_) => &[],
            Reply::Approve(_) => &[],
            Reply::Deny(_) => &[],
            Reply::Blame(_) => &[],
            Reply::Submit(_) => &[],
            Reply::StartAgent(_) => &[],
            Reply::EndLease(_) => &[],
            Reply::EndSession(_) => &[],
            Reply::Watch(_) => &[],
        }
    }

    /// The opcode of the request this replies to.
    fn opcode(&self) -> u32 {
        match self {
            Reply::Login(_) => 1,
            Reply::ChannelClosed(_) => 2,
            Reply::ApprovalOpened(_) => 3,
            Reply::ApprovalClosed(_) => 4,
            Reply::Pending(_) => 5,
            Reply::Approve(_) => 6,
            Reply::Deny(_) => 7,
            Reply::Blame(_) => 8,
            Reply::Submit(_) => 9,
            Reply::StartAgent(_) => 10,
            Reply::EndLease(_) => 11,
            Reply::EndSession(_) => 12,
            Reply::Watch(_) => 13,
        }
    }

    fn write(&self, w: &mut Writer<'_>) -> Result<(), Error> {
        match self {
            Reply::Login(m) => {
                w.u64(m.session)?;
                w.string(m.name)?;
                w.bytes(m.labels)
            }
            Reply::ChannelClosed(_) => Ok(()),
            Reply::ApprovalOpened(m) => w.u64(m.channel),
            Reply::ApprovalClosed(_) => Ok(()),
            Reply::Pending(m) => {
                w.u64(m.request)?;
                w.bytes(m.hash)?;
                w.bytes(m.labels)?;
                w.string(m.text)
            }
            Reply::Approve(_) => Ok(()),
            Reply::Deny(_) => Ok(()),
            Reply::Blame(_) => Ok(()),
            Reply::Submit(m) => w.u64(m.request),
            Reply::StartAgent(m) => {
                w.u64(m.lease)?;
                w.string(m.name)
            }
            Reply::EndLease(_) => Ok(()),
            Reply::EndSession(_) => Ok(()),
            Reply::Watch(_) => Ok(()),
        }
    }

    fn read_inline(opcode: u32, _r: &mut Reader<'_>) -> Result<Self, Error> {
        Ok(match opcode {
            2 => Reply::ChannelClosed(ChannelClosedReply {}),
            4 => Reply::ApprovalClosed(ApprovalClosedReply {}),
            11 => Reply::EndLease(EndLeaseReply {}),
            12 => Reply::EndSession(EndSessionReply {}),
            13 => Reply::Watch(WatchReply {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    fn read_buffer(opcode: u32, r: &mut Reader<'a>) -> Result<Self, Error> {
        Ok(match opcode {
            1 => Reply::Login(LoginReply { session: r.u64()?, name: r.string()?, labels: r.bytes()? }),
            2 => Reply::ChannelClosed(ChannelClosedReply {}),
            3 => Reply::ApprovalOpened(ApprovalOpenedReply { channel: r.u64()? }),
            4 => Reply::ApprovalClosed(ApprovalClosedReply {}),
            5 => Reply::Pending(PendingReply { request: r.u64()?, hash: r.bytes()?, labels: r.bytes()?, text: r.string()? }),
            6 => Reply::Approve(ApproveReply {}),
            7 => Reply::Deny(DenyReply {}),
            8 => Reply::Blame(BlameReply {}),
            9 => Reply::Submit(SubmitReply { request: r.u64()? }),
            10 => Reply::StartAgent(StartAgentReply { lease: r.u64()?, name: r.string()? }),
            11 => Reply::EndLease(EndLeaseReply {}),
            12 => Reply::EndSession(EndSessionReply {}),
            13 => Reply::Watch(WatchReply {}),
            _ => return Err(Error::BadOpcode),
        })
    }

    /// Decodes the reply to the request with `opcode` (the caller knows what it sent):
    /// `Ok(Ok(reply))`, `Ok(Err(code))`
    /// for an error reply, or `Err` if the reply is malformed.
    pub fn decode(opcode: u32, words: &Words, buf: &'a [u8], handles: usize) -> Result<Result<Self, ErrorCode>, Error> {
        let layout = typed::layout(REPLIES, opcode)?;
        if let Some(code) = typed::reply_status(words, handles)? {
            return ErrorCode::from_code(code).map(Err).ok_or(Error::BadStatus);
        }
        typed::decode(layout, words, buf, handles, Self::read_inline, Self::read_buffer).map(Ok)
    }

    /// Encodes the reply (status 0): returns its words, and writes the fields into `buf`
    /// (the caller's lend) if it is a buffer message.
    pub fn encode(&self, buf: &mut [u8]) -> Result<Words, Error> {
        typed::encode(typed::layout(REPLIES, self.opcode())?, 0, buf, |w| self.write(w))
    }
}

/// The protocol's error codes: word 0 of an error reply. Code 1, `Malformed`, is every
/// protocol's: a request that does not decode (servers/wire.md, "The message convention").
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ErrorCode {
    Malformed,
    Unknown,
    BadKey,
    NotOwner,
    Labelled,
    Cap,
    TooBig,
    NotPrintable,
    NotRendered,
    HashMismatch,
    BadLease,
    LockedOut,
    NotSponsor,
    Failed,
    InUse,
}

impl ErrorCode {
    pub fn code(self) -> u32 {
        match self {
            ErrorCode::Malformed => 1,
            ErrorCode::Unknown => 2,
            ErrorCode::BadKey => 3,
            ErrorCode::NotOwner => 4,
            ErrorCode::Labelled => 5,
            ErrorCode::Cap => 6,
            ErrorCode::TooBig => 7,
            ErrorCode::NotPrintable => 8,
            ErrorCode::NotRendered => 9,
            ErrorCode::HashMismatch => 10,
            ErrorCode::BadLease => 11,
            ErrorCode::LockedOut => 12,
            ErrorCode::NotSponsor => 13,
            ErrorCode::Failed => 14,
            ErrorCode::InUse => 15,
        }
    }

    pub fn from_code(code: u32) -> Option<Self> {
        match code {
            1 => Some(ErrorCode::Malformed),
            2 => Some(ErrorCode::Unknown),
            3 => Some(ErrorCode::BadKey),
            4 => Some(ErrorCode::NotOwner),
            5 => Some(ErrorCode::Labelled),
            6 => Some(ErrorCode::Cap),
            7 => Some(ErrorCode::TooBig),
            8 => Some(ErrorCode::NotPrintable),
            9 => Some(ErrorCode::NotRendered),
            10 => Some(ErrorCode::HashMismatch),
            11 => Some(ErrorCode::BadLease),
            12 => Some(ErrorCode::LockedOut),
            13 => Some(ErrorCode::NotSponsor),
            14 => Some(ErrorCode::Failed),
            15 => Some(ErrorCode::InUse),
            _ => None,
        }
    }

    /// The words of the error reply (no buffer, no handles).
    pub fn encode(self) -> Words {
        typed::error_reply(self.code())
    }
}

typed::protocol!('a, Message<'a>, Reply<'a>);
