[package]
name = "beamlet"
description = "Run BEAM modules on beamlet using the POSIX platform"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
beamlet-vm = { path = "../vm" }
beamlet-crypto = { path = "../crypto" }
beamlet-re = { path = "../re" }
cap-std = "3"
fs-set-times = "0.20"
