# Typed messages of the `bootfs` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/bootfs.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Proto.Bootfs do
  @moduledoc """
  Codec for the `bootfs` protocol. A request or reply is `{name, fields}`, with `fields` a
  map holding exactly the table's non-handle fields; an error reply decodes to
  `{:failed, error}`; `:malformed` (code 1) is every protocol's error for a request that
  does not decode. Framing and errors: `Redoubt.Wire`.
  """
  alias Redoubt.Wire, as: W

  # opcode => {name, shape, handles}; replies are keyed by their request's opcode.
  @requests %{
    16 => {:add, :buffer, 0},
    17 => {:seal, :inline, 0}
  }
  @replies %{
    16 => {:add, :buffer, 0},
    17 => {:seal, :inline, 0}
  }
  @errors %{
    1 => :malformed,
    2 => :refused
  }

  @doc """
  A message's layout: `{opcode, shape, fields, handles, reply}`, where `fields` lists
  `{name, type}` in order, `handles` lists the handles' names by slot, and `reply` is
  `{fields, handles}`.
  """
  def layout(:add), do: {16, :buffer, [{:name, :string}, {:offset, :u64}, {:data, :bytes}], [], {[], []}}
  def layout(:seal), do: {17, :inline, [], [], {[], []}}
  def layout(_), do: nil

  @doc "Encodes a request: `{:ok, words, buffer}` or `{:error, reason}`."
  def encode(message), do: W.encode(message, @requests, &enc(:request, &1, &2))

  @doc "Encodes a successful reply (status 0): `{:ok, words, buffer}` or `{:error, reason}`."
  def encode_reply(reply), do: W.encode_reply(reply, @replies, &enc(:reply, &1, &2))

  @doc "The words of an error reply: `{:ok, words, <<>>}` or `{:error, :bad_message}`."
  def encode_error(error), do: W.encode_error(error, @errors)

  @doc "Encodes a request for writing into a 9P file: `{:ok, bytes}` or `{:error, reason}`."
  def encode_file(message), do: W.encode_file(message, @requests, &enc(:request, &1, &2))

  @doc "Decodes a request from its four words, its buffer and its handle count."
  def decode(words, buffer, handles), do: W.decode(words, buffer, handles, @requests, &read(:request, &1, &2))

  @doc "Decodes the reply to the request with `opcode`: `{:ok, reply}`, `{:failed, error}` or `{:error, reason}`."
  def decode_reply(opcode, words, buffer, handles),
    do: W.decode_reply(opcode, words, buffer, handles, @replies, @errors, &read(:reply, &1, &2))

  @doc "Decodes a request written into a 9P file."
  def decode_file(bytes), do: W.decode_file(bytes, @requests, &read(:request, &1, &2))

  defp enc(:request, :add, %{name: v_name, offset: v_offset, data: v_data} = f) when map_size(f) == 3, do: {16, [W.str(v_name), W.u(v_offset, 64), W.bytes(v_data)]}
  defp enc(:reply, :add, %{} = f) when map_size(f) == 0, do: {16, []}
  defp enc(:request, :seal, %{} = f) when map_size(f) == 0, do: {17, []}
  defp enc(:reply, :seal, %{} = f) when map_size(f) == 0, do: {17, []}
  defp enc(_, _, _), do: throw({:wire, :bad_message})

  defp read(:request, 16, <<n_name::little-16, v_name::binary-size(n_name), v_offset::little-64, n_data::little-32, v_data::binary-size(n_data), rest::binary>>), do: W.utf8([v_name], {:ok, :add, %{name: v_name, offset: v_offset, data: v_data}, rest})
  defp read(:reply, 16, <<rest::binary>>), do: {:ok, :add, %{}, rest}
  defp read(:request, 17, <<rest::binary>>), do: {:ok, :seal, %{}, rest}
  defp read(:reply, 17, <<rest::binary>>), do: {:ok, :seal, %{}, rest}
  defp read(_, _, _), do: {:error, :short_fields}
end
