# Typed messages of the `consrelay` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/consrelay.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Proto.Consrelay do
  @moduledoc """
  Codec for the `consrelay` protocol. A request or reply is `{name, fields}`, with `fields` a
  map holding exactly the table's non-handle fields; an error reply decodes to
  `{:failed, error}`; `:malformed` (code 1) is every protocol's error for a request that
  does not decode. Framing and errors: `Redoubt.Wire`.
  """
  alias Redoubt.Wire, as: W

  # opcode => {name, shape, handles}; replies are keyed by their request's opcode.
  @requests %{
    24 => {:attach, :buffer, 1},
    25 => {:detach, :buffer, 0},
    26 => {:hello, :inline, 2}
  }
  @replies %{
    24 => {:attach, :buffer, 0},
    25 => {:detach, :buffer, 0},
    26 => {:hello, :inline, 0}
  }
  @errors %{
    1 => :malformed,
    2 => :failed
  }

  @doc """
  A message's layout: `{opcode, shape, fields, handles, reply}`, where `fields` lists
  `{name, type}` in order, `handles` lists the handles' names by slot, and `reply` is
  `{fields, handles}`.

  Handle kinds, from the table: documentation, checked by use (a handle of the wrong kind
  gets `WrongObject` on first use).

  - `attach`: `console` (slot 0, endpoint)
  - `hello`: `vm` (slot 0, endpoint), `control` (slot 1, endpoint)
  """
  def layout(:attach), do: {24, :buffer, [{:note, :string}], [:console], {[], []}}
  def layout(:detach), do: {25, :buffer, [{:note, :string}], [], {[], []}}
  def layout(:hello), do: {26, :inline, [], [:vm, :control], {[], []}}
  def layout(_), do: nil

  @doc "Encodes a request: `{:ok, words, buffer}` or `{:error, reason}`."
  def encode(message), do: W.encode(message, @requests, &enc(:request, &1, &2))

  @doc "Encodes a successful reply (status 0): `{:ok, words, buffer}` or `{:error, reason}`."
  def encode_reply(reply), do: W.encode_reply(reply, @replies, &enc(:reply, &1, &2))

  @doc "The words of an error reply: `{:ok, words, <<>>}` or `{:error, :bad_message}`."
  def encode_error(error), do: W.encode_error(error, @errors)

  @doc "Encodes a request for writing into a 9P file: `{:ok, bytes}` or `{:error, reason}`."
  def encode_file(message), do: W.encode_file(message, @requests, &enc(:request, &1, &2))

  @doc "Decodes a request from its four words, its buffer and its handle count."
  def decode(words, buffer, handles), do: W.decode(words, buffer, handles, @requests, &read(:request, &1, &2))

  @doc "Decodes the reply to the request with `opcode`: `{:ok, reply}`, `{:failed, error}` or `{:error, reason}`."
  def decode_reply(opcode, words, buffer, handles),
    do: W.decode_reply(opcode, words, buffer, handles, @replies, @errors, &read(:reply, &1, &2))

  @doc "Decodes a request written into a 9P file."
  def decode_file(bytes), do: W.decode_file(bytes, @requests, &read(:request, &1, &2))

  defp enc(:request, :attach, %{note: v_note} = f) when map_size(f) == 1, do: {24, [W.str(v_note)]}
  defp enc(:reply, :attach, %{} = f) when map_size(f) == 0, do: {24, []}
  defp enc(:request, :detach, %{note: v_note} = f) when map_size(f) == 1, do: {25, [W.str(v_note)]}
  defp enc(:reply, :detach, %{} = f) when map_size(f) == 0, do: {25, []}
  defp enc(:request, :hello, %{} = f) when map_size(f) == 0, do: {26, []}
  defp enc(:reply, :hello, %{} = f) when map_size(f) == 0, do: {26, []}
  defp enc(_, _, _), do: throw({:wire, :bad_message})

  defp read(:request, 24, <<n_note::little-16, v_note::binary-size(n_note), rest::binary>>), do: W.utf8([v_note], {:ok, :attach, %{note: v_note}, rest})
  defp read(:reply, 24, <<rest::binary>>), do: {:ok, :attach, %{}, rest}
  defp read(:request, 25, <<n_note::little-16, v_note::binary-size(n_note), rest::binary>>), do: W.utf8([v_note], {:ok, :detach, %{note: v_note}, rest})
  defp read(:reply, 25, <<rest::binary>>), do: {:ok, :detach, %{}, rest}
  defp read(:request, 26, <<rest::binary>>), do: {:ok, :hello, %{}, rest}
  defp read(:reply, 26, <<rest::binary>>), do: {:ok, :hello, %{}, rest}
  defp read(_, _, _), do: {:error, :short_fields}
end
