# Typed messages of the `consol` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/consol.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Proto.Consol do
  @moduledoc """
  Codec for the `consol` protocol. A request or reply is `{name, fields}`, with `fields` a
  map holding exactly the table's non-handle fields; an error reply decodes to
  `{:failed, error}`; `:malformed` (code 1) is every protocol's error for a request that
  does not decode. Framing and errors: `Redoubt.Wire`.
  """
  alias Redoubt.Wire, as: W

  # opcode => {name, shape, handles}; replies are keyed by their request's opcode.
  @requests %{
    16 => {:size, :inline, 0},
    17 => {:resize, :inline, 0}
  }
  @replies %{
    16 => {:size, :inline, 0},
    17 => {:resize, :inline, 0}
  }
  @errors %{
    1 => :malformed
  }

  @doc """
  A message's layout: `{opcode, shape, fields, handles, reply}`, where `fields` lists
  `{name, type}` in order, `handles` lists the handles' names by slot, and `reply` is
  `{fields, handles}`.
  """
  def layout(:size), do: {16, :inline, [], [], {[{:cols, :u16}, {:rows, :u16}], []}}
  def layout(:resize), do: {17, :inline, [], [], {[{:cols, :u16}, {:rows, :u16}], []}}
  def layout(_), do: nil

  @doc "Encodes a request: `{:ok, words, buffer}` or `{:error, reason}`."
  def encode(message), do: W.encode(message, @requests, &enc(:request, &1, &2))

  @doc "Encodes a successful reply (status 0): `{:ok, words, buffer}` or `{:error, reason}`."
  def encode_reply(reply), do: W.encode_reply(reply, @replies, &enc(:reply, &1, &2))

  @doc "The words of an error reply: `{:ok, words, <<>>}` or `{:error, :bad_message}`."
  def encode_error(error), do: W.encode_error(error, @errors)

  @doc "Encodes a request for writing into a 9P file: `{:ok, bytes}` or `{:error, reason}`."
  def encode_file(message), do: W.encode_file(message, @requests, &enc(:request, &1, &2))

  @doc "Decodes a request from its four words, its buffer and its handle count."
  def decode(words, buffer, handles), do: W.decode(words, buffer, handles, @requests, &read(:request, &1, &2))

  @doc "Decodes the reply to the request with `opcode`: `{:ok, reply}`, `{:failed, error}` or `{:error, reason}`."
  def decode_reply(opcode, words, buffer, handles),
    do: W.decode_reply(opcode, words, buffer, handles, @replies, @errors, &read(:reply, &1, &2))

  @doc "Decodes a request written into a 9P file."
  def decode_file(bytes), do: W.decode_file(bytes, @requests, &read(:request, &1, &2))

  defp enc(:request, :size, %{} = f) when map_size(f) == 0, do: {16, []}
  defp enc(:reply, :size, %{cols: v_cols, rows: v_rows} = f) when map_size(f) == 2, do: {16, [W.u(v_cols, 16), W.u(v_rows, 16)]}
  defp enc(:request, :resize, %{} = f) when map_size(f) == 0, do: {17, []}
  defp enc(:reply, :resize, %{cols: v_cols, rows: v_rows} = f) when map_size(f) == 2, do: {17, [W.u(v_cols, 16), W.u(v_rows, 16)]}
  defp enc(_, _, _), do: throw({:wire, :bad_message})

  defp read(:request, 16, <<rest::binary>>), do: {:ok, :size, %{}, rest}
  defp read(:reply, 16, <<v_cols::little-16, v_rows::little-16, rest::binary>>), do: {:ok, :size, %{cols: v_cols, rows: v_rows}, rest}
  defp read(:request, 17, <<rest::binary>>), do: {:ok, :resize, %{}, rest}
  defp read(:reply, 17, <<v_cols::little-16, v_rows::little-16, rest::binary>>), do: {:ok, :resize, %{cols: v_cols, rows: v_rows}, rest}
  defp read(_, _, _), do: {:error, :short_fields}
end
