# Typed messages of the `fsd` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/fsd.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Proto.Fsd do
  @moduledoc """
  Codec for the `fsd` protocol. A request or reply is `{name, fields}`, with `fields` a
  map holding exactly the table's non-handle fields; an error reply decodes to
  `{:failed, error}`; `:malformed` (code 1) is every protocol's error for a request that
  does not decode. Framing and errors: `Redoubt.Wire`.
  """
  alias Redoubt.Wire, as: W

  # opcode => {name, shape, handles}; replies are keyed by their request's opcode.
  @requests %{
    16 => {:rename, :buffer, 0},
    17 => {:copy_file, :buffer, 0},
    18 => {:set_attr, :buffer, 0},
    19 => {:get_attr, :buffer, 0}
  }
  @replies %{
    16 => {:rename, :buffer, 0},
    17 => {:copy_file, :buffer, 0},
    18 => {:set_attr, :buffer, 0},
    19 => {:get_attr, :buffer, 0}
  }
  @errors %{
    1 => :malformed,
    2 => :not_found,
    3 => :refused,
    4 => :exists,
    5 => :not_dir
  }

  @doc """
  A message's layout: `{opcode, shape, fields, handles, reply}`, where `fields` lists
  `{name, type}` in order, `handles` lists the handles' names by slot, and `reply` is
  `{fields, handles}`.
  """
  def layout(:rename), do: {16, :buffer, [{:old_dir, :u32}, {:old_name, :string}, {:new_dir, :u32}, {:new_name, :string}], [], {[], []}}
  def layout(:copy_file), do: {17, :buffer, [{:src_fid, :u32}, {:dst_dir, :u32}, {:dst_name, :string}], [], {[{:count, :u64}], []}}
  def layout(:set_attr), do: {18, :buffer, [{:fid, :u32}, {:attr, :u8}, {:value, :bytes}], [], {[], []}}
  def layout(:get_attr), do: {19, :buffer, [{:fid, :u32}, {:attr, :u8}], [], {[{:value, :bytes}], []}}
  def layout(_), do: nil

  @doc "Encodes a request: `{:ok, words, buffer}` or `{:error, reason}`."
  def encode(message), do: W.encode(message, @requests, &enc(:request, &1, &2))

  @doc "Encodes a successful reply (status 0): `{:ok, words, buffer}` or `{:error, reason}`."
  def encode_reply(reply), do: W.encode_reply(reply, @replies, &enc(:reply, &1, &2))

  @doc "The words of an error reply: `{:ok, words, <<>>}` or `{:error, :bad_message}`."
  def encode_error(error), do: W.encode_error(error, @errors)

  @doc "Encodes a request for writing into a 9P file: `{:ok, bytes}` or `{:error, reason}`."
  def encode_file(message), do: W.encode_file(message, @requests, &enc(:request, &1, &2))

  @doc "Decodes a request from its four words, its buffer and its handle count."
  def decode(words, buffer, handles), do: W.decode(words, buffer, handles, @requests, &read(:request, &1, &2))

  @doc "Decodes the reply to the request with `opcode`: `{:ok, reply}`, `{:failed, error}` or `{:error, reason}`."
  def decode_reply(opcode, words, buffer, handles),
    do: W.decode_reply(opcode, words, buffer, handles, @replies, @errors, &read(:reply, &1, &2))

  @doc "Decodes a request written into a 9P file."
  def decode_file(bytes), do: W.decode_file(bytes, @requests, &read(:request, &1, &2))

  defp enc(:request, :rename, %{old_dir: v_old_dir, old_name: v_old_name, new_dir: v_new_dir, new_name: v_new_name} = f) when map_size(f) == 4, do: {16, [W.u(v_old_dir, 32), W.str(v_old_name), W.u(v_new_dir, 32), W.str(v_new_name)]}
  defp enc(:reply, :rename, %{} = f) when map_size(f) == 0, do: {16, []}
  defp enc(:request, :copy_file, %{src_fid: v_src_fid, dst_dir: v_dst_dir, dst_name: v_dst_name} = f) when map_size(f) == 3, do: {17, [W.u(v_src_fid, 32), W.u(v_dst_dir, 32), W.str(v_dst_name)]}
  defp enc(:reply, :copy_file, %{count: v_count} = f) when map_size(f) == 1, do: {17, [W.u(v_count, 64)]}
  defp enc(:request, :set_attr, %{fid: v_fid, attr: v_attr, value: v_value} = f) when map_size(f) == 3, do: {18, [W.u(v_fid, 32), W.u(v_attr, 8), W.bytes(v_value)]}
  defp enc(:reply, :set_attr, %{} = f) when map_size(f) == 0, do: {18, []}
  defp enc(:request, :get_attr, %{fid: v_fid, attr: v_attr} = f) when map_size(f) == 2, do: {19, [W.u(v_fid, 32), W.u(v_attr, 8)]}
  defp enc(:reply, :get_attr, %{value: v_value} = f) when map_size(f) == 1, do: {19, [W.bytes(v_value)]}
  defp enc(_, _, _), do: throw({:wire, :bad_message})

  defp read(:request, 16, <<v_old_dir::little-32, n_old_name::little-16, v_old_name::binary-size(n_old_name), v_new_dir::little-32, n_new_name::little-16, v_new_name::binary-size(n_new_name), rest::binary>>), do: W.utf8([v_old_name, v_new_name], {:ok, :rename, %{old_dir: v_old_dir, old_name: v_old_name, new_dir: v_new_dir, new_name: v_new_name}, rest})
  defp read(:reply, 16, <<rest::binary>>), do: {:ok, :rename, %{}, rest}
  defp read(:request, 17, <<v_src_fid::little-32, v_dst_dir::little-32, n_dst_name::little-16, v_dst_name::binary-size(n_dst_name), rest::binary>>), do: W.utf8([v_dst_name], {:ok, :copy_file, %{src_fid: v_src_fid, dst_dir: v_dst_dir, dst_name: v_dst_name}, rest})
  defp read(:reply, 17, <<v_count::little-64, rest::binary>>), do: {:ok, :copy_file, %{count: v_count}, rest}
  defp read(:request, 18, <<v_fid::little-32, v_attr::little-8, n_value::little-32, v_value::binary-size(n_value), rest::binary>>), do: {:ok, :set_attr, %{fid: v_fid, attr: v_attr, value: v_value}, rest}
  defp read(:reply, 18, <<rest::binary>>), do: {:ok, :set_attr, %{}, rest}
  defp read(:request, 19, <<v_fid::little-32, v_attr::little-8, rest::binary>>), do: {:ok, :get_attr, %{fid: v_fid, attr: v_attr}, rest}
  defp read(:reply, 19, <<n_value::little-32, v_value::binary-size(n_value), rest::binary>>), do: {:ok, :get_attr, %{value: v_value}, rest}
  defp read(_, _, _), do: {:error, :short_fields}
end
