# Typed messages of the `ipd` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/ipd.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Proto.Ipd do
  @moduledoc """
  Codec for the `ipd` protocol. A request or reply is `{name, fields}`, with `fields` a
  map holding exactly the table's non-handle fields; an error reply decodes to
  `{:failed, error}`; `:malformed` (code 1) is every protocol's error for a request that
  does not decode. Framing and errors: `Redoubt.Wire`.
  """
  alias Redoubt.Wire, as: W

  # opcode => {name, shape, handles}; replies are keyed by their request's opcode.
  @requests %{
    16 => {:grant, :buffer, 0},
    17 => {:frame, :buffer, 0}
  }
  @replies %{
    16 => {:grant, :buffer, 1},
    17 => {:frame, :buffer, 0}
  }
  @errors %{
    1 => :malformed,
    2 => :not_permitted,
    3 => :too_many
  }

  @doc """
  A message's layout: `{opcode, shape, fields, handles, reply}`, where `fields` lists
  `{name, type}` in order, `handles` lists the handles' names by slot, and `reply` is
  `{fields, handles}`.

  Handle kinds, from the table: documentation, checked by use (a handle of the wrong kind
  gets `WrongObject` on first use).

  - `grant` reply: `conn` (slot 0, endpoint)
  """
  def layout(:grant), do: {16, :buffer, [{:scope, :bytes}], [], {[{:id, :u64}], [:conn]}}
  def layout(:frame), do: {17, :buffer, [{:frame, :bytes}], [], {[], []}}
  def layout(_), do: nil

  @doc "Encodes a request: `{:ok, words, buffer}` or `{:error, reason}`."
  def encode(message), do: W.encode(message, @requests, &enc(:request, &1, &2))

  @doc "Encodes a successful reply (status 0): `{:ok, words, buffer}` or `{:error, reason}`."
  def encode_reply(reply), do: W.encode_reply(reply, @replies, &enc(:reply, &1, &2))

  @doc "The words of an error reply: `{:ok, words, <<>>}` or `{:error, :bad_message}`."
  def encode_error(error), do: W.encode_error(error, @errors)

  @doc "Encodes a request for writing into a 9P file: `{:ok, bytes}` or `{:error, reason}`."
  def encode_file(message), do: W.encode_file(message, @requests, &enc(:request, &1, &2))

  @doc "Decodes a request from its four words, its buffer and its handle count."
  def decode(words, buffer, handles), do: W.decode(words, buffer, handles, @requests, &read(:request, &1, &2))

  @doc "Decodes the reply to the request with `opcode`: `{:ok, reply}`, `{:failed, error}` or `{:error, reason}`."
  def decode_reply(opcode, words, buffer, handles),
    do: W.decode_reply(opcode, words, buffer, handles, @replies, @errors, &read(:reply, &1, &2))

  @doc "Decodes a request written into a 9P file."
  def decode_file(bytes), do: W.decode_file(bytes, @requests, &read(:request, &1, &2))

  defp enc(:request, :grant, %{scope: v_scope} = f) when map_size(f) == 1, do: {16, [W.bytes(v_scope)]}
  defp enc(:reply, :grant, %{id: v_id} = f) when map_size(f) == 1, do: {16, [W.u(v_id, 64)]}
  defp enc(:request, :frame, %{frame: v_frame} = f) when map_size(f) == 1, do: {17, [W.bytes(v_frame)]}
  defp enc(:reply, :frame, %{} = f) when map_size(f) == 0, do: {17, []}
  defp enc(_, _, _), do: throw({:wire, :bad_message})

  defp read(:request, 16, <<n_scope::little-32, v_scope::binary-size(n_scope), rest::binary>>), do: {:ok, :grant, %{scope: v_scope}, rest}
  defp read(:reply, 16, <<v_id::little-64, rest::binary>>), do: {:ok, :grant, %{id: v_id}, rest}
  defp read(:request, 17, <<n_frame::little-32, v_frame::binary-size(n_frame), rest::binary>>), do: {:ok, :frame, %{frame: v_frame}, rest}
  defp read(:reply, 17, <<rest::binary>>), do: {:ok, :frame, %{}, rest}
  defp read(_, _, _), do: {:error, :short_fields}
end
