# Typed messages of the `keyd` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `docs/INIT.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Proto.Keyd do
  @moduledoc """
  Codec for the `keyd` protocol. A request or reply is `{name, fields}`, with `fields` a
  map holding exactly the table's non-handle fields; an error reply decodes to
  `{:failed, error}`; `:malformed` (code 1) is every protocol's error for a request that
  does not decode. Framing and errors: `Redoubt.Wire`.
  """
  alias Redoubt.Wire, as: W

  # opcode => {name, shape, handles}; replies are keyed by their request's opcode.
  @requests %{
    1 => {:sign_ssh_exchange, :buffer, 0},
    2 => {:sign_record, :buffer, 0},
    3 => {:public_key, :buffer, 0},
    4 => {:holds, :buffer, 0},
    5 => {:grant, :inline, 0},
    6 => {:release, :inline, 0}
  }
  @replies %{
    1 => {:sign_ssh_exchange, :buffer, 0},
    2 => {:sign_record, :buffer, 0},
    3 => {:public_key, :buffer, 0},
    4 => {:holds, :buffer, 0},
    5 => {:grant, :inline, 1},
    6 => {:release, :inline, 0}
  }
  @errors %{
    1 => :malformed,
    2 => :not_permitted,
    3 => :too_many,
    4 => :failed
  }

  @doc """
  A message's layout: `{opcode, shape, fields, handles, reply}`, where `fields` lists
  `{name, type}` in order, `handles` lists the handles' names by slot, and `reply` is
  `{fields, handles}`.

  Handle kinds, from the table: documentation, checked by use (a handle of the wrong kind
  gets `WrongObject` on first use).

  - `grant` reply: `capability` (slot 0, endpoint)
  """
  def layout(:sign_ssh_exchange), do: {1, :buffer, [{:v_c, :bytes}, {:v_s, :bytes}, {:i_c, :bytes}, {:i_s, :bytes}, {:q_c, :bytes}, {:q_s, :bytes}, {:k, :bytes}], [], {[{:signature, :bytes}], []}}
  def layout(:sign_record), do: {2, :buffer, [{:record, :bytes}], [], {[{:signature, :bytes}], []}}
  def layout(:public_key), do: {3, :buffer, [], [], {[{:key, :bytes}], []}}
  def layout(:holds), do: {4, :buffer, [{:key, :bytes}], [], {[{:held, :u32}], []}}
  def layout(:grant), do: {5, :inline, [], [], {[{:id, :u64}], [:capability]}}
  def layout(:release), do: {6, :inline, [{:id, :u64}], [], {[], []}}
  def layout(_), do: nil

  @doc "Encodes a request: `{:ok, words, buffer}` or `{:error, reason}`."
  def encode(message), do: W.encode(message, @requests, &enc(:request, &1, &2))

  @doc "Encodes a successful reply (status 0): `{:ok, words, buffer}` or `{:error, reason}`."
  def encode_reply(reply), do: W.encode_reply(reply, @replies, &enc(:reply, &1, &2))

  @doc "The words of an error reply: `{:ok, words, <<>>}` or `{:error, :bad_message}`."
  def encode_error(error), do: W.encode_error(error, @errors)

  @doc "Encodes a request for writing into a 9P file: `{:ok, bytes}` or `{:error, reason}`."
  def encode_file(message), do: W.encode_file(message, @requests, &enc(:request, &1, &2))

  @doc "Decodes a request from its four words, its buffer and its handle count."
  def decode(words, buffer, handles), do: W.decode(words, buffer, handles, @requests, &read(:request, &1, &2))

  @doc "Decodes the reply to the request with `opcode`: `{:ok, reply}`, `{:failed, error}` or `{:error, reason}`."
  def decode_reply(opcode, words, buffer, handles),
    do: W.decode_reply(opcode, words, buffer, handles, @replies, @errors, &read(:reply, &1, &2))

  @doc "Decodes a request written into a 9P file."
  def decode_file(bytes), do: W.decode_file(bytes, @requests, &read(:request, &1, &2))

  defp enc(:request, :sign_ssh_exchange, %{v_c: v_v_c, v_s: v_v_s, i_c: v_i_c, i_s: v_i_s, q_c: v_q_c, q_s: v_q_s, k: v_k} = f) when map_size(f) == 7, do: {1, [W.bytes(v_v_c), W.bytes(v_v_s), W.bytes(v_i_c), W.bytes(v_i_s), W.bytes(v_q_c), W.bytes(v_q_s), W.bytes(v_k)]}
  defp enc(:reply, :sign_ssh_exchange, %{signature: v_signature} = f) when map_size(f) == 1, do: {1, [W.bytes(v_signature)]}
  defp enc(:request, :sign_record, %{record: v_record} = f) when map_size(f) == 1, do: {2, [W.bytes(v_record)]}
  defp enc(:reply, :sign_record, %{signature: v_signature} = f) when map_size(f) == 1, do: {2, [W.bytes(v_signature)]}
  defp enc(:request, :public_key, %{} = f) when map_size(f) == 0, do: {3, []}
  defp enc(:reply, :public_key, %{key: v_key} = f) when map_size(f) == 1, do: {3, [W.bytes(v_key)]}
  defp enc(:request, :holds, %{key: v_key} = f) when map_size(f) == 1, do: {4, [W.bytes(v_key)]}
  defp enc(:reply, :holds, %{held: v_held} = f) when map_size(f) == 1, do: {4, [W.u(v_held, 32)]}
  defp enc(:request, :grant, %{} = f) when map_size(f) == 0, do: {5, []}
  defp enc(:reply, :grant, %{id: v_id} = f) when map_size(f) == 1, do: {5, [W.u(v_id, 64)]}
  defp enc(:request, :release, %{id: v_id} = f) when map_size(f) == 1, do: {6, [W.u(v_id, 64)]}
  defp enc(:reply, :release, %{} = f) when map_size(f) == 0, do: {6, []}
  defp enc(_, _, _), do: throw({:wire, :bad_message})

  defp read(:request, 1, <<n_v_c::little-32, v_v_c::binary-size(n_v_c), n_v_s::little-32, v_v_s::binary-size(n_v_s), n_i_c::little-32, v_i_c::binary-size(n_i_c), n_i_s::little-32, v_i_s::binary-size(n_i_s), n_q_c::little-32, v_q_c::binary-size(n_q_c), n_q_s::little-32, v_q_s::binary-size(n_q_s), n_k::little-32, v_k::binary-size(n_k), rest::binary>>), do: {:ok, :sign_ssh_exchange, %{v_c: v_v_c, v_s: v_v_s, i_c: v_i_c, i_s: v_i_s, q_c: v_q_c, q_s: v_q_s, k: v_k}, rest}
  defp read(:reply, 1, <<n_signature::little-32, v_signature::binary-size(n_signature), rest::binary>>), do: {:ok, :sign_ssh_exchange, %{signature: v_signature}, rest}
  defp read(:request, 2, <<n_record::little-32, v_record::binary-size(n_record), rest::binary>>), do: {:ok, :sign_record, %{record: v_record}, rest}
  defp read(:reply, 2, <<n_signature::little-32, v_signature::binary-size(n_signature), rest::binary>>), do: {:ok, :sign_record, %{signature: v_signature}, rest}
  defp read(:request, 3, <<rest::binary>>), do: {:ok, :public_key, %{}, rest}
  defp read(:reply, 3, <<n_key::little-32, v_key::binary-size(n_key), rest::binary>>), do: {:ok, :public_key, %{key: v_key}, rest}
  defp read(:request, 4, <<n_key::little-32, v_key::binary-size(n_key), rest::binary>>), do: {:ok, :holds, %{key: v_key}, rest}
  defp read(:reply, 4, <<v_held::little-32, rest::binary>>), do: {:ok, :holds, %{held: v_held}, rest}
  defp read(:request, 5, <<rest::binary>>), do: {:ok, :grant, %{}, rest}
  defp read(:reply, 5, <<v_id::little-64, rest::binary>>), do: {:ok, :grant, %{id: v_id}, rest}
  defp read(:request, 6, <<v_id::little-64, rest::binary>>), do: {:ok, :release, %{id: v_id}, rest}
  defp read(:reply, 6, <<rest::binary>>), do: {:ok, :release, %{}, rest}
  defp read(_, _, _), do: {:error, :short_fields}
end
