# Typed messages of the `net_ctl` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `docs/NAMESPACES.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Proto.NetCtl do
  @moduledoc """
  Codec for the `net_ctl` protocol. A request or reply is `{name, fields}`, with `fields` a
  map holding exactly the table's non-handle fields; an error reply decodes to
  `{:failed, error}`; `:malformed` (code 1) is every protocol's error for a request that
  does not decode. Framing and errors: `Redoubt.Wire`.
  """
  alias Redoubt.Wire, as: W

  # opcode => {name, shape, handles}; replies are keyed by their request's opcode.
  @requests %{
    1 => {:connect, :buffer, 0},
    2 => {:listen, :inline, 0},
    3 => {:close, :inline, 0},
    4 => {:abort, :inline, 0}
  }
  @replies %{
    1 => {:connect, :buffer, 0},
    2 => {:listen, :inline, 0},
    3 => {:close, :inline, 0},
    4 => {:abort, :inline, 0}
  }
  @errors %{
    1 => :malformed,
    2 => :not_permitted,
    3 => :in_use,
    4 => :too_many,
    5 => :state,
    6 => :unreachable,
    7 => :refused,
    8 => :timeout
  }

  @doc """
  A message's layout: `{opcode, shape, fields, handles, reply}`, where `fields` lists
  `{name, type}` in order, `handles` lists the handles' names by slot, and `reply` is
  `{fields, handles}`.
  """
  def layout(:connect), do: {1, :buffer, [{:addr, :bytes}, {:port, :u16}], [], {[], []}}
  def layout(:listen), do: {2, :inline, [{:port, :u16}, {:backlog, :u8}], [], {[], []}}
  def layout(:close), do: {3, :inline, [], [], {[], []}}
  def layout(:abort), do: {4, :inline, [], [], {[], []}}
  def layout(_), do: nil

  @doc "Encodes a request: `{:ok, words, buffer}` or `{:error, reason}`."
  def encode(message), do: W.encode(message, @requests, &enc(:request, &1, &2))

  @doc "Encodes a successful reply (status 0): `{:ok, words, buffer}` or `{:error, reason}`."
  def encode_reply(reply), do: W.encode_reply(reply, @replies, &enc(:reply, &1, &2))

  @doc "The words of an error reply: `{:ok, words, <<>>}` or `{:error, :bad_message}`."
  def encode_error(error), do: W.encode_error(error, @errors)

  @doc "Encodes a request for writing into a 9P file: `{:ok, bytes}` or `{:error, reason}`."
  def encode_file(message), do: W.encode_file(message, @requests, &enc(:request, &1, &2))

  @doc "Decodes a request from its four words, its buffer and its handle count."
  def decode(words, buffer, handles), do: W.decode(words, buffer, handles, @requests, &read(:request, &1, &2))

  @doc "Decodes the reply to the request with `opcode`: `{:ok, reply}`, `{:failed, error}` or `{:error, reason}`."
  def decode_reply(opcode, words, buffer, handles),
    do: W.decode_reply(opcode, words, buffer, handles, @replies, @errors, &read(:reply, &1, &2))

  @doc "Decodes a request written into a 9P file."
  def decode_file(bytes), do: W.decode_file(bytes, @requests, &read(:request, &1, &2))

  defp enc(:request, :connect, %{addr: v_addr, port: v_port} = f) when map_size(f) == 2, do: {1, [W.bytes(v_addr), W.u(v_port, 16)]}
  defp enc(:reply, :connect, %{} = f) when map_size(f) == 0, do: {1, []}
  defp enc(:request, :listen, %{port: v_port, backlog: v_backlog} = f) when map_size(f) == 2, do: {2, [W.u(v_port, 16), W.u(v_backlog, 8)]}
  defp enc(:reply, :listen, %{} = f) when map_size(f) == 0, do: {2, []}
  defp enc(:request, :close, %{} = f) when map_size(f) == 0, do: {3, []}
  defp enc(:reply, :close, %{} = f) when map_size(f) == 0, do: {3, []}
  defp enc(:request, :abort, %{} = f) when map_size(f) == 0, do: {4, []}
  defp enc(:reply, :abort, %{} = f) when map_size(f) == 0, do: {4, []}
  defp enc(_, _, _), do: throw({:wire, :bad_message})

  defp read(:request, 1, <<n_addr::little-32, v_addr::binary-size(n_addr), v_port::little-16, rest::binary>>), do: {:ok, :connect, %{addr: v_addr, port: v_port}, rest}
  defp read(:reply, 1, <<rest::binary>>), do: {:ok, :connect, %{}, rest}
  defp read(:request, 2, <<v_port::little-16, v_backlog::little-8, rest::binary>>), do: {:ok, :listen, %{port: v_port, backlog: v_backlog}, rest}
  defp read(:reply, 2, <<rest::binary>>), do: {:ok, :listen, %{}, rest}
  defp read(:request, 3, <<rest::binary>>), do: {:ok, :close, %{}, rest}
  defp read(:reply, 3, <<rest::binary>>), do: {:ok, :close, %{}, rest}
  defp read(:request, 4, <<rest::binary>>), do: {:ok, :abort, %{}, rest}
  defp read(:reply, 4, <<rest::binary>>), do: {:ok, :abort, %{}, rest}
  defp read(_, _, _), do: {:error, :short_fields}
end
