# Typed messages of the `netif` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `docs/IO-ARCHITECTURE.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Proto.Netif do
  @moduledoc """
  Codec for the `netif` protocol. A request or reply is `{name, fields}`, with `fields` a
  map holding exactly the table's non-handle fields; an error reply decodes to
  `{:failed, error}`; `:malformed` (code 1) is every protocol's error for a request that
  does not decode. Framing and errors: `Redoubt.Wire`.
  """
  alias Redoubt.Wire, as: W

  # opcode => {name, shape, handles}; replies are keyed by their request's opcode.
  @requests %{
    1 => {:info, :inline, 0},
    2 => {:transmit, :buffer, 0}
  }
  @replies %{
    1 => {:info, :inline, 0},
    2 => {:transmit, :buffer, 0}
  }
  @errors %{
    1 => :malformed,
    2 => :not_permitted,
    3 => :too_many,
    4 => :busy,
    5 => :failed
  }

  @doc """
  A message's layout: `{opcode, shape, fields, handles, reply}`, where `fields` lists
  `{name, type}` in order, `handles` lists the handles' names by slot, and `reply` is
  `{fields, handles}`.
  """
  def layout(:info), do: {1, :inline, [], [], {[{:mac, :u64}, {:mtu, :u32}], []}}
  def layout(:transmit), do: {2, :buffer, [{:frame, :bytes}], [], {[], []}}
  def layout(_), do: nil

  @doc "Encodes a request: `{:ok, words, buffer}` or `{:error, reason}`."
  def encode(message), do: W.encode(message, @requests, &enc(:request, &1, &2))

  @doc "Encodes a successful reply (status 0): `{:ok, words, buffer}` or `{:error, reason}`."
  def encode_reply(reply), do: W.encode_reply(reply, @replies, &enc(:reply, &1, &2))

  @doc "The words of an error reply: `{:ok, words, <<>>}` or `{:error, :bad_message}`."
  def encode_error(error), do: W.encode_error(error, @errors)

  @doc "Encodes a request for writing into a 9P file: `{:ok, bytes}` or `{:error, reason}`."
  def encode_file(message), do: W.encode_file(message, @requests, &enc(:request, &1, &2))

  @doc "Decodes a request from its four words, its buffer and its handle count."
  def decode(words, buffer, handles), do: W.decode(words, buffer, handles, @requests, &read(:request, &1, &2))

  @doc "Decodes the reply to the request with `opcode`: `{:ok, reply}`, `{:failed, error}` or `{:error, reason}`."
  def decode_reply(opcode, words, buffer, handles),
    do: W.decode_reply(opcode, words, buffer, handles, @replies, @errors, &read(:reply, &1, &2))

  @doc "Decodes a request written into a 9P file."
  def decode_file(bytes), do: W.decode_file(bytes, @requests, &read(:request, &1, &2))

  defp enc(:request, :info, %{} = f) when map_size(f) == 0, do: {1, []}
  defp enc(:reply, :info, %{mac: v_mac, mtu: v_mtu} = f) when map_size(f) == 2, do: {1, [W.u(v_mac, 64), W.u(v_mtu, 32)]}
  defp enc(:request, :transmit, %{frame: v_frame} = f) when map_size(f) == 1, do: {2, [W.bytes(v_frame)]}
  defp enc(:reply, :transmit, %{} = f) when map_size(f) == 0, do: {2, []}
  defp enc(_, _, _), do: throw({:wire, :bad_message})

  defp read(:request, 1, <<rest::binary>>), do: {:ok, :info, %{}, rest}
  defp read(:reply, 1, <<v_mac::little-64, v_mtu::little-32, rest::binary>>), do: {:ok, :info, %{mac: v_mac, mtu: v_mtu}, rest}
  defp read(:request, 2, <<n_frame::little-32, v_frame::binary-size(n_frame), rest::binary>>), do: {:ok, :transmit, %{frame: v_frame}, rest}
  defp read(:reply, 2, <<rest::binary>>), do: {:ok, :transmit, %{}, rest}
  defp read(_, _, _), do: {:error, :short_fields}
end
