# Typed messages of the `ninep_common` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `docs/NAMESPACES.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Proto.NinepCommon do
  @moduledoc """
  Codec for the `ninep_common` protocol. A request or reply is `{name, fields}`, with `fields` a
  map holding exactly the table's non-handle fields; an error reply decodes to
  `{:failed, error}`; `:malformed` (code 1) is every protocol's error for a request that
  does not decode. Framing and errors: `Redoubt.Wire`.
  """
  alias Redoubt.Wire, as: W

  # opcode => {name, shape, handles}; replies are keyed by their request's opcode.
  @requests %{
    2 => {:new_connection, :buffer, 0},
    3 => {:disconnect, :inline, 0}
  }
  @replies %{
    2 => {:new_connection, :buffer, 1},
    3 => {:disconnect, :inline, 0}
  }
  @errors %{
    1 => :malformed,
    3 => :refused
  }

  @doc """
  A message's layout: `{opcode, shape, fields, handles, reply}`, where `fields` lists
  `{name, type}` in order, `handles` lists the handles' names by slot, and `reply` is
  `{fields, handles}`.

  Handle kinds, from the table: documentation, checked by use (a handle of the wrong kind
  gets `WrongObject` on first use).

  - `new_connection` reply: `conn` (slot 0, endpoint)
  """
  def layout(:new_connection), do: {2, :buffer, [{:root, :string}, {:quota, :u64}], [], {[{:id, :u64}], [:conn]}}
  def layout(:disconnect), do: {3, :inline, [{:id, :u64}], [], {[], []}}
  def layout(_), do: nil

  @doc "Encodes a request: `{:ok, words, buffer}` or `{:error, reason}`."
  def encode(message), do: W.encode(message, @requests, &enc(:request, &1, &2))

  @doc "Encodes a successful reply (status 0): `{:ok, words, buffer}` or `{:error, reason}`."
  def encode_reply(reply), do: W.encode_reply(reply, @replies, &enc(:reply, &1, &2))

  @doc "The words of an error reply: `{:ok, words, <<>>}` or `{:error, :bad_message}`."
  def encode_error(error), do: W.encode_error(error, @errors)

  @doc "Encodes a request for writing into a 9P file: `{:ok, bytes}` or `{:error, reason}`."
  def encode_file(message), do: W.encode_file(message, @requests, &enc(:request, &1, &2))

  @doc "Decodes a request from its four words, its buffer and its handle count."
  def decode(words, buffer, handles), do: W.decode(words, buffer, handles, @requests, &read(:request, &1, &2))

  @doc "Decodes the reply to the request with `opcode`: `{:ok, reply}`, `{:failed, error}` or `{:error, reason}`."
  def decode_reply(opcode, words, buffer, handles),
    do: W.decode_reply(opcode, words, buffer, handles, @replies, @errors, &read(:reply, &1, &2))

  @doc "Decodes a request written into a 9P file."
  def decode_file(bytes), do: W.decode_file(bytes, @requests, &read(:request, &1, &2))

  defp enc(:request, :new_connection, %{root: v_root, quota: v_quota} = f) when map_size(f) == 2, do: {2, [W.str(v_root), W.u(v_quota, 64)]}
  defp enc(:reply, :new_connection, %{id: v_id} = f) when map_size(f) == 1, do: {2, [W.u(v_id, 64)]}
  defp enc(:request, :disconnect, %{id: v_id} = f) when map_size(f) == 1, do: {3, [W.u(v_id, 64)]}
  defp enc(:reply, :disconnect, %{} = f) when map_size(f) == 0, do: {3, []}
  defp enc(_, _, _), do: throw({:wire, :bad_message})

  defp read(:request, 2, <<n_root::little-16, v_root::binary-size(n_root), v_quota::little-64, rest::binary>>), do: W.utf8([v_root], {:ok, :new_connection, %{root: v_root, quota: v_quota}, rest})
  defp read(:reply, 2, <<v_id::little-64, rest::binary>>), do: {:ok, :new_connection, %{id: v_id}, rest}
  defp read(:request, 3, <<v_id::little-64, rest::binary>>), do: {:ok, :disconnect, %{id: v_id}, rest}
  defp read(:reply, 3, <<rest::binary>>), do: {:ok, :disconnect, %{}, rest}
  defp read(_, _, _), do: {:error, :short_fields}
end
