# Typed messages of the `startup` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/startup.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Proto.Startup do
  @moduledoc """
  Codec for the `startup` protocol. A request or reply is `{name, fields}`, with `fields` a
  map holding exactly the table's non-handle fields; an error reply decodes to
  `{:failed, error}`; `:malformed` (code 1) is every protocol's error for a request that
  does not decode. Framing and errors: `Redoubt.Wire`.
  """
  alias Redoubt.Wire, as: W

  # opcode => {name, shape, handles}; replies are keyed by their request's opcode.
  @requests %{
    1 => {:startup, :buffer, 0}
  }
  @replies %{
    1 => {:startup, :buffer, 0}
  }
  @errors %{
    1 => :malformed
  }

  @doc """
  A message's layout: `{opcode, shape, fields, handles, reply}`, where `fields` lists
  `{name, type}` in order, `handles` lists the handles' names by slot, and `reply` is
  `{fields, handles}`.
  """
  def layout(:startup), do: {1, :buffer, [{:version, :u32}, {:handle_count, :u32}, {:namespace, :bytes}, {:handles, :bytes}, {:argv, :bytes}, {:image_addr, :u64}, {:image_len, :u64}], [], {[], []}}
  def layout(_), do: nil

  @doc "Encodes a request: `{:ok, words, buffer}` or `{:error, reason}`."
  def encode(message), do: W.encode(message, @requests, &enc(:request, &1, &2))

  @doc "Encodes a successful reply (status 0): `{:ok, words, buffer}` or `{:error, reason}`."
  def encode_reply(reply), do: W.encode_reply(reply, @replies, &enc(:reply, &1, &2))

  @doc "The words of an error reply: `{:ok, words, <<>>}` or `{:error, :bad_message}`."
  def encode_error(error), do: W.encode_error(error, @errors)

  @doc "Encodes a request for writing into a 9P file: `{:ok, bytes}` or `{:error, reason}`."
  def encode_file(message), do: W.encode_file(message, @requests, &enc(:request, &1, &2))

  @doc "Decodes a request from its four words, its buffer and its handle count."
  def decode(words, buffer, handles), do: W.decode(words, buffer, handles, @requests, &read(:request, &1, &2))

  @doc "Decodes the reply to the request with `opcode`: `{:ok, reply}`, `{:failed, error}` or `{:error, reason}`."
  def decode_reply(opcode, words, buffer, handles),
    do: W.decode_reply(opcode, words, buffer, handles, @replies, @errors, &read(:reply, &1, &2))

  @doc "Decodes a request written into a 9P file."
  def decode_file(bytes), do: W.decode_file(bytes, @requests, &read(:request, &1, &2))

  defp enc(:request, :startup, %{version: v_version, handle_count: v_handle_count, namespace: v_namespace, handles: v_handles, argv: v_argv, image_addr: v_image_addr, image_len: v_image_len} = f) when map_size(f) == 7, do: {1, [W.u(v_version, 32), W.u(v_handle_count, 32), W.bytes(v_namespace), W.bytes(v_handles), W.bytes(v_argv), W.u(v_image_addr, 64), W.u(v_image_len, 64)]}
  defp enc(:reply, :startup, %{} = f) when map_size(f) == 0, do: {1, []}
  defp enc(_, _, _), do: throw({:wire, :bad_message})

  defp read(:request, 1, <<v_version::little-32, v_handle_count::little-32, n_namespace::little-32, v_namespace::binary-size(n_namespace), n_handles::little-32, v_handles::binary-size(n_handles), n_argv::little-32, v_argv::binary-size(n_argv), v_image_addr::little-64, v_image_len::little-64, rest::binary>>), do: {:ok, :startup, %{version: v_version, handle_count: v_handle_count, namespace: v_namespace, handles: v_handles, argv: v_argv, image_addr: v_image_addr, image_len: v_image_len}, rest}
  defp read(:reply, 1, <<rest::binary>>), do: {:ok, :startup, %{}, rest}
  defp read(_, _, _), do: {:error, :short_fields}
end
