# Typed messages of the `steward` protocol.
#
# Generated by `redoubt-wire-gen` from the tables in `libs/wire/tables/steward.md`.
# Do not edit: change the tables and run `cargo run -p redoubt-wire-gen`.
defmodule Redoubt.Wire.Proto.Steward do
  @moduledoc """
  Codec for the `steward` protocol. A request or reply is `{name, fields}`, with `fields` a
  map holding exactly the table's non-handle fields; an error reply decodes to
  `{:failed, error}`; `:malformed` (code 1) is every protocol's error for a request that
  does not decode. Framing and errors: `Redoubt.Wire`.
  """
  alias Redoubt.Wire, as: W

  # opcode => {name, shape, handles}; replies are keyed by their request's opcode.
  @requests %{
    1 => {:login, :buffer, 2},
    2 => {:channel_closed, :inline, 0},
    3 => {:approval_opened, :buffer, 0},
    4 => {:approval_closed, :inline, 0},
    5 => {:pending, :buffer, 0},
    6 => {:approve, :buffer, 0},
    7 => {:deny, :buffer, 0},
    8 => {:blame, :buffer, 0},
    9 => {:submit, :buffer, 0},
    10 => {:start_agent, :buffer, 0},
    11 => {:end_lease, :inline, 0},
    12 => {:end_session, :inline, 0},
    13 => {:watch, :inline, 0},
    14 => {:contexts, :buffer, 0},
    15 => {:detach, :inline, 0},
    16 => {:end_context, :buffer, 0}
  }
  @replies %{
    1 => {:login, :buffer, 0},
    2 => {:channel_closed, :inline, 0},
    3 => {:approval_opened, :buffer, 0},
    4 => {:approval_closed, :inline, 0},
    5 => {:pending, :buffer, 0},
    6 => {:approve, :buffer, 0},
    7 => {:deny, :buffer, 0},
    8 => {:blame, :buffer, 0},
    9 => {:submit, :buffer, 0},
    10 => {:start_agent, :buffer, 0},
    11 => {:end_lease, :inline, 0},
    12 => {:end_session, :inline, 0},
    13 => {:watch, :inline, 0},
    14 => {:contexts, :buffer, 0},
    15 => {:detach, :inline, 0},
    16 => {:end_context, :buffer, 0}
  }
  @errors %{
    1 => :malformed,
    2 => :unknown,
    3 => :bad_key,
    4 => :not_owner,
    5 => :labelled,
    6 => :cap,
    7 => :too_big,
    8 => :not_printable,
    9 => :not_rendered,
    10 => :hash_mismatch,
    11 => :bad_lease,
    12 => :locked_out,
    13 => :not_sponsor,
    14 => :failed,
    15 => :in_use
  }

  @doc """
  A message's layout: `{opcode, shape, fields, handles, reply}`, where `fields` lists
  `{name, type}` in order, `handles` lists the handles' names by slot, and `reply` is
  `{fields, handles}`.

  Handle kinds, from the table: documentation, checked by use (a handle of the wrong kind
  gets `WrongObject` on first use).

  - `login`: `console` (slot 0, endpoint), `relay` (slot 1, endpoint)
  """
  def layout(:login), do: {1, :buffer, [{:principal, :string}, {:label, :string}, {:context, :string}, {:from, :string}, {:key, :bytes}], [:console, :relay], {[{:session, :u64}, {:name, :string}, {:labels, :bytes}], []}}
  def layout(:channel_closed), do: {2, :inline, [{:session, :u64}], [], {[], []}}
  def layout(:approval_opened), do: {3, :buffer, [{:principal, :string}, {:key, :bytes}], [], {[{:channel, :u64}], []}}
  def layout(:approval_closed), do: {4, :inline, [{:channel, :u64}], [], {[], []}}
  def layout(:pending), do: {5, :buffer, [{:channel, :u64}], [], {[{:request, :u64}, {:hash, :bytes}, {:labels, :bytes}, {:text, :string}], []}}
  def layout(:approve), do: {6, :buffer, [{:channel, :u64}, {:request, :u64}, {:hash, :bytes}], [], {[], []}}
  def layout(:deny), do: {7, :buffer, [{:channel, :u64}, {:request, :u64}], [], {[], []}}
  def layout(:blame), do: {8, :buffer, [{:account, :u64}, {:labels, :bytes}, {:server, :string}], [], {[], []}}
  def layout(:submit), do: {9, :buffer, [{:kind, :u32}, {:labels, :bytes}, {:lease, :u64}, {:item, :u64}, {:source, :u64}, {:what, :string}, {:reason, :string}], [], {[{:request, :u64}], []}}
  def layout(:start_agent), do: {10, :buffer, [{:lease, :u64}], [], {[{:lease, :u64}, {:name, :string}], []}}
  def layout(:end_lease), do: {11, :inline, [{:lease, :u64}], [], {[], []}}
  def layout(:end_session), do: {12, :inline, [], [], {[], []}}
  def layout(:watch), do: {13, :inline, [], [], {[], []}}
  def layout(:contexts), do: {14, :buffer, [], [], {[{:list, :string}], []}}
  def layout(:detach), do: {15, :inline, [], [], {[], []}}
  def layout(:end_context), do: {16, :buffer, [{:name, :string}], [], {[], []}}
  def layout(_), do: nil

  @doc "Encodes a request: `{:ok, words, buffer}` or `{:error, reason}`."
  def encode(message), do: W.encode(message, @requests, &enc(:request, &1, &2))

  @doc "Encodes a successful reply (status 0): `{:ok, words, buffer}` or `{:error, reason}`."
  def encode_reply(reply), do: W.encode_reply(reply, @replies, &enc(:reply, &1, &2))

  @doc "The words of an error reply: `{:ok, words, <<>>}` or `{:error, :bad_message}`."
  def encode_error(error), do: W.encode_error(error, @errors)

  @doc "Encodes a request for writing into a 9P file: `{:ok, bytes}` or `{:error, reason}`."
  def encode_file(message), do: W.encode_file(message, @requests, &enc(:request, &1, &2))

  @doc "Decodes a request from its four words, its buffer and its handle count."
  def decode(words, buffer, handles), do: W.decode(words, buffer, handles, @requests, &read(:request, &1, &2))

  @doc "Decodes the reply to the request with `opcode`: `{:ok, reply}`, `{:failed, error}` or `{:error, reason}`."
  def decode_reply(opcode, words, buffer, handles),
    do: W.decode_reply(opcode, words, buffer, handles, @replies, @errors, &read(:reply, &1, &2))

  @doc "Decodes a request written into a 9P file."
  def decode_file(bytes), do: W.decode_file(bytes, @requests, &read(:request, &1, &2))

  defp enc(:request, :login, %{principal: v_principal, label: v_label, context: v_context, from: v_from, key: v_key} = f) when map_size(f) == 5, do: {1, [W.str(v_principal), W.str(v_label), W.str(v_context), W.str(v_from), W.bytes(v_key)]}
  defp enc(:reply, :login, %{session: v_session, name: v_name, labels: v_labels} = f) when map_size(f) == 3, do: {1, [W.u(v_session, 64), W.str(v_name), W.bytes(v_labels)]}
  defp enc(:request, :channel_closed, %{session: v_session} = f) when map_size(f) == 1, do: {2, [W.u(v_session, 64)]}
  defp enc(:reply, :channel_closed, %{} = f) when map_size(f) == 0, do: {2, []}
  defp enc(:request, :approval_opened, %{principal: v_principal, key: v_key} = f) when map_size(f) == 2, do: {3, [W.str(v_principal), W.bytes(v_key)]}
  defp enc(:reply, :approval_opened, %{channel: v_channel} = f) when map_size(f) == 1, do: {3, [W.u(v_channel, 64)]}
  defp enc(:request, :approval_closed, %{channel: v_channel} = f) when map_size(f) == 1, do: {4, [W.u(v_channel, 64)]}
  defp enc(:reply, :approval_closed, %{} = f) when map_size(f) == 0, do: {4, []}
  defp enc(:request, :pending, %{channel: v_channel} = f) when map_size(f) == 1, do: {5, [W.u(v_channel, 64)]}
  defp enc(:reply, :pending, %{request: v_request, hash: v_hash, labels: v_labels, text: v_text} = f) when map_size(f) == 4, do: {5, [W.u(v_request, 64), W.bytes(v_hash), W.bytes(v_labels), W.str(v_text)]}
  defp enc(:request, :approve, %{channel: v_channel, request: v_request, hash: v_hash} = f) when map_size(f) == 3, do: {6, [W.u(v_channel, 64), W.u(v_request, 64), W.bytes(v_hash)]}
  defp enc(:reply, :approve, %{} = f) when map_size(f) == 0, do: {6, []}
  defp enc(:request, :deny, %{channel: v_channel, request: v_request} = f) when map_size(f) == 2, do: {7, [W.u(v_channel, 64), W.u(v_request, 64)]}
  defp enc(:reply, :deny, %{} = f) when map_size(f) == 0, do: {7, []}
  defp enc(:request, :blame, %{account: v_account, labels: v_labels, server: v_server} = f) when map_size(f) == 3, do: {8, [W.u(v_account, 64), W.bytes(v_labels), W.str(v_server)]}
  defp enc(:reply, :blame, %{} = f) when map_size(f) == 0, do: {8, []}
  defp enc(:request, :submit, %{kind: v_kind, labels: v_labels, lease: v_lease, item: v_item, source: v_source, what: v_what, reason: v_reason} = f) when map_size(f) == 7, do: {9, [W.u(v_kind, 32), W.bytes(v_labels), W.u(v_lease, 64), W.u(v_item, 64), W.u(v_source, 64), W.str(v_what), W.str(v_reason)]}
  defp enc(:reply, :submit, %{request: v_request} = f) when map_size(f) == 1, do: {9, [W.u(v_request, 64)]}
  defp enc(:request, :start_agent, %{lease: v_lease} = f) when map_size(f) == 1, do: {10, [W.u(v_lease, 64)]}
  defp enc(:reply, :start_agent, %{lease: v_lease, name: v_name} = f) when map_size(f) == 2, do: {10, [W.u(v_lease, 64), W.str(v_name)]}
  defp enc(:request, :end_lease, %{lease: v_lease} = f) when map_size(f) == 1, do: {11, [W.u(v_lease, 64)]}
  defp enc(:reply, :end_lease, %{} = f) when map_size(f) == 0, do: {11, []}
  defp enc(:request, :end_session, %{} = f) when map_size(f) == 0, do: {12, []}
  defp enc(:reply, :end_session, %{} = f) when map_size(f) == 0, do: {12, []}
  defp enc(:request, :watch, %{} = f) when map_size(f) == 0, do: {13, []}
  defp enc(:reply, :watch, %{} = f) when map_size(f) == 0, do: {13, []}
  defp enc(:request, :contexts, %{} = f) when map_size(f) == 0, do: {14, []}
  defp enc(:reply, :contexts, %{list: v_list} = f) when map_size(f) == 1, do: {14, [W.str(v_list)]}
  defp enc(:request, :detach, %{} = f) when map_size(f) == 0, do: {15, []}
  defp enc(:reply, :detach, %{} = f) when map_size(f) == 0, do: {15, []}
  defp enc(:request, :end_context, %{name: v_name} = f) when map_size(f) == 1, do: {16, [W.str(v_name)]}
  defp enc(:reply, :end_context, %{} = f) when map_size(f) == 0, do: {16, []}
  defp enc(_, _, _), do: throw({:wire, :bad_message})

  defp read(:request, 1, <<n_principal::little-16, v_principal::binary-size(n_principal), n_label::little-16, v_label::binary-size(n_label), n_context::little-16, v_context::binary-size(n_context), n_from::little-16, v_from::binary-size(n_from), n_key::little-32, v_key::binary-size(n_key), rest::binary>>), do: W.utf8([v_principal, v_label, v_context, v_from], {:ok, :login, %{principal: v_principal, label: v_label, context: v_context, from: v_from, key: v_key}, rest})
  defp read(:reply, 1, <<v_session::little-64, n_name::little-16, v_name::binary-size(n_name), n_labels::little-32, v_labels::binary-size(n_labels), rest::binary>>), do: W.utf8([v_name], {:ok, :login, %{session: v_session, name: v_name, labels: v_labels}, rest})
  defp read(:request, 2, <<v_session::little-64, rest::binary>>), do: {:ok, :channel_closed, %{session: v_session}, rest}
  defp read(:reply, 2, <<rest::binary>>), do: {:ok, :channel_closed, %{}, rest}
  defp read(:request, 3, <<n_principal::little-16, v_principal::binary-size(n_principal), n_key::little-32, v_key::binary-size(n_key), rest::binary>>), do: W.utf8([v_principal], {:ok, :approval_opened, %{principal: v_principal, key: v_key}, rest})
  defp read(:reply, 3, <<v_channel::little-64, rest::binary>>), do: {:ok, :approval_opened, %{channel: v_channel}, rest}
  defp read(:request, 4, <<v_channel::little-64, rest::binary>>), do: {:ok, :approval_closed, %{channel: v_channel}, rest}
  defp read(:reply, 4, <<rest::binary>>), do: {:ok, :approval_closed, %{}, rest}
  defp read(:request, 5, <<v_channel::little-64, rest::binary>>), do: {:ok, :pending, %{channel: v_channel}, rest}
  defp read(:reply, 5, <<v_request::little-64, n_hash::little-32, v_hash::binary-size(n_hash), n_labels::little-32, v_labels::binary-size(n_labels), n_text::little-16, v_text::binary-size(n_text), rest::binary>>), do: W.utf8([v_text], {:ok, :pending, %{request: v_request, hash: v_hash, labels: v_labels, text: v_text}, rest})
  defp read(:request, 6, <<v_channel::little-64, v_request::little-64, n_hash::little-32, v_hash::binary-size(n_hash), rest::binary>>), do: {:ok, :approve, %{channel: v_channel, request: v_request, hash: v_hash}, rest}
  defp read(:reply, 6, <<rest::binary>>), do: {:ok, :approve, %{}, rest}
  defp read(:request, 7, <<v_channel::little-64, v_request::little-64, rest::binary>>), do: {:ok, :deny, %{channel: v_channel, request: v_request}, rest}
  defp read(:reply, 7, <<rest::binary>>), do: {:ok, :deny, %{}, rest}
  defp read(:request, 8, <<v_account::little-64, n_labels::little-32, v_labels::binary-size(n_labels), n_server::little-16, v_server::binary-size(n_server), rest::binary>>), do: W.utf8([v_server], {:ok, :blame, %{account: v_account, labels: v_labels, server: v_server}, rest})
  defp read(:reply, 8, <<rest::binary>>), do: {:ok, :blame, %{}, rest}
  defp read(:request, 9, <<v_kind::little-32, n_labels::little-32, v_labels::binary-size(n_labels), v_lease::little-64, v_item::little-64, v_source::little-64, n_what::little-16, v_what::binary-size(n_what), n_reason::little-16, v_reason::binary-size(n_reason), rest::binary>>), do: W.utf8([v_what, v_reason], {:ok, :submit, %{kind: v_kind, labels: v_labels, lease: v_lease, item: v_item, source: v_source, what: v_what, reason: v_reason}, rest})
  defp read(:reply, 9, <<v_request::little-64, rest::binary>>), do: {:ok, :submit, %{request: v_request}, rest}
  defp read(:request, 10, <<v_lease::little-64, rest::binary>>), do: {:ok, :start_agent, %{lease: v_lease}, rest}
  defp read(:reply, 10, <<v_lease::little-64, n_name::little-16, v_name::binary-size(n_name), rest::binary>>), do: W.utf8([v_name], {:ok, :start_agent, %{lease: v_lease, name: v_name}, rest})
  defp read(:request, 11, <<v_lease::little-64, rest::binary>>), do: {:ok, :end_lease, %{lease: v_lease}, rest}
  defp read(:reply, 11, <<rest::binary>>), do: {:ok, :end_lease, %{}, rest}
  defp read(:request, 12, <<rest::binary>>), do: {:ok, :end_session, %{}, rest}
  defp read(:reply, 12, <<rest::binary>>), do: {:ok, :end_session, %{}, rest}
  defp read(:request, 13, <<rest::binary>>), do: {:ok, :watch, %{}, rest}
  defp read(:reply, 13, <<rest::binary>>), do: {:ok, :watch, %{}, rest}
  defp read(:request, 14, <<rest::binary>>), do: {:ok, :contexts, %{}, rest}
  defp read(:reply, 14, <<n_list::little-16, v_list::binary-size(n_list), rest::binary>>), do: W.utf8([v_list], {:ok, :contexts, %{list: v_list}, rest})
  defp read(:request, 15, <<rest::binary>>), do: {:ok, :detach, %{}, rest}
  defp read(:reply, 15, <<rest::binary>>), do: {:ok, :detach, %{}, rest}
  defp read(:request, 16, <<n_name::little-16, v_name::binary-size(n_name), rest::binary>>), do: W.utf8([v_name], {:ok, :end_context, %{name: v_name}, rest})
  defp read(:reply, 16, <<rest::binary>>), do: {:ok, :end_context, %{}, rest}
  defp read(_, _, _), do: {:error, :short_fields}
end
