#!/usr/bin/env escript
%% Generates vm/src/opcodes.rs from tools/genop.tab, the compiler's opcode table taken
%% verbatim from the pinned OTP tag (see README.md). Usage:
%%   escript tools/gen-opcodes.escript tools/genop.tab vm/src/opcodes.rs
main([Tab, Out]) ->
    {ok, Bin} = file:read_file(Tab),
    Rows = [parse(L) || L <- binary:split(Bin, <<"\n">>, [global]), is_op(L)],
    Max = lists:max([Op || {Op, _, _, _} <- Rows]),
    Seq = lists:seq(1, Max),
    [] = Seq -- [Op || {Op, _, _, _} <- Rows],   % no gaps
    Entry = fun({Op, N, A, Dep}) ->
                io_lib:format("    Op { name: \"~s\", arity: ~p, deprecated: ~p }, // ~p~n", [N, A, Dep, Op])
            end,
    Const = fun({Op, N, _, _}) ->
                io_lib:format("pub const ~s: u8 = ~p;~n", [string:uppercase(N), Op])
            end,
    ok = file:write_file(Out, [
        "// Generated by tools/gen-opcodes.escript from tools/genop.tab. Do not edit.\n\n",
        "/// One row of the compiler's opcode table.\n",
        "pub struct Op {\n    pub name: &'static str,\n    pub arity: u8,\n",
        "    /// The pinned compiler never emits it; the loader refuses it.\n",
        "    pub deprecated: bool,\n}\n\n",
        "/// Highest opcode number the pinned compiler knows.\n",
        io_lib:format("pub const MAX_OPCODE: u8 = ~p;~n~n", [Max]),
        "/// Indexed by opcode number. Index 0 is not an opcode.\n",
        io_lib:format("pub static OPCODES: [Op; ~p] = [~n", [Max + 1]),
        "    Op { name: \"\", arity: 0, deprecated: true },\n",
        [Entry(R) || R <- lists:keysort(1, Rows)], "];\n\n",
        [Const(R) || R <- lists:keysort(1, Rows)]]).

is_op(L) -> re:run(L, "^[0-9]+: ") =/= nomatch.

parse(L) ->
    {match, [Op, Dash, Name, Arity]} =
        re:run(L, "^([0-9]+): *(-?)([a-z_0-9]+)/([0-9]+)", [{capture, all_but_first, list}]),
    {list_to_integer(Op), Name, list_to_integer(Arity), Dash =:= "-"}.
