#!/usr/bin/env escript
%% Writes screen/src/wide.rs: the code points OTP's unicode_util:is_wide/1 calls wide, as sorted
%% inclusive ranges, from the pinned OTP this runs on. So the screen buffer's natives measure a
%% grapheme as OTP's line editor and the shell (Redoubt.Term.Width) do: one table, one Unicode
%% version. With --check, compares instead of writing, and fails if the file is not current.
%%
%%   escript tools/gen-width.escript [--check]      (from userland/otp, the pinned OTP on PATH)
-mode(compile).

main(Args) ->
    Out = filename:join([filename:dirname(escript:script_name()), "..", "screen", "src", "wide.rs"]),
    Text = unicode:characters_to_binary(source()),
    case Args of
        ["--check"] ->
            case file:read_file(Out) of
                {ok, Text} -> ok;
                _ -> io:format(standard_error, "out of date: ~s (run tools/gen-width.escript)~n", [Out]), halt(1)
            end;
        [] ->
            ok = file:write_file(Out, Text)
    end.

source() ->
    {Major, Minor} = unicode_util:spec_version(),
    Ranges = ranges(0, none, []),
    Lines = [io_lib:format("    (0x~.16B, 0x~.16B),~n", [A, B]) || {A, B} <- Ranges],
    ["//! The code points OTP's `unicode_util:is_wide/1` calls wide, as sorted inclusive ranges: from\n",
     io_lib:format("//! OTP ~s's Unicode ~b.~b. Generated by tools/gen-width.escript; do not edit.\n",
                   [erlang:system_info(otp_release), Major, Minor]),
     "\n",
     io_lib:format("/// The Unicode version of this table.~npub const UNICODE: (u8, u8) = (~b, ~b);~n~n", [Major, Minor]),
     "/// Wide code points, as `(first, last)`.\n",
     "pub const WIDE: &[(u32, u32)] = &[\n", Lines, "];\n"].

%% Ranges of consecutive wide code points, surrogates skipped.
ranges(C, Open, Acc) when C > 16#10FFFF -> lists:reverse(close(Open, C - 1, Acc));
ranges(C, Open, Acc) when C >= 16#D800, C =< 16#DFFF -> ranges(16#E000, none, close(Open, C - 1, Acc));
ranges(C, Open, Acc) ->
    case {unicode_util:is_wide(C), Open} of
        {true, none} -> ranges(C + 1, C, Acc);
        {true, _} -> ranges(C + 1, Open, Acc);
        {false, none} -> ranges(C + 1, none, Acc);
        {false, _} -> ranges(C + 1, none, [{Open, C - 1} | Acc])
    end.

close(none, _Last, Acc) -> Acc;
close(First, Last, Acc) -> [{First, Last} | Acc].
